### ISSUE TITLE
Panorama hotspots not responsive on iOS

### ISSUE THREAD

**Issue by tonyredhead** [google/marzipano#1]
I've just built a test  [Marzipano Tour](http://tonyredhead.photography/360/social/marzipano-tour/) and as result of testing on different devices I've noticed that Hotspot or Info Buttons applied to individual panoramas don't respond on iOS (iPhone or iPad).

On the Desktop in the latest versions of Chrome, Safari and Firefox the hotspots work as expected.

On Galaxy Tab A in the latest versions of Chrome and Firefox the hotspots work as expected.

On iOS iPhone 6 and iPad Air 2 the hotspots don't work in Chrome or Safari.

Any ideas on how to make that functionality valid for iOS

**Comment by Frankatdinosaur** [comment]
Hi Manuel, I see you did a commit on here that fixes the iOS hotspot issue. Can you confirm if that's now live on the Marzipano site + tool? 
I just generated a pano using the tool and couldn\t get hotspots to respond on an iOS device. Was fine on desktop.

Many thanks. And awesome piece of code!

**Comment by manuelcabral** [comment]
Thanks!

This commit was fixing another issue, which was that the info hotspots were
not scrolling properly. The iOS hotspot issue is not resolved yet.

**Comment by tjgq** [comment]
Fixed by 72a7bcb. Feel free to reopen if the issue persists on any device.
