### ISSUE TITLE
How to get yaw and pitch values after panorama export

### ISSUE THREAD

**Issue by bpdinteractive** [google/marzipano#10]
I see the "yaw" and "pitch" values in my data.js file and recognize it as radians but how do I determine what those values should be after the panorama has been made and exported (for instance, if I wanted to move a hotspot manually)?

**Comment by manuelcabral** [comment]
One way would be to open the equirectangular image and check the pixel coordinates of the point. Alternatively, you could also implement something that prints the coordinates when a point is clicked on the viewer.
