### ISSUE TITLE
Public build

### ISSUE THREAD

**Issue by etki** [google/marzipano#102]
Hi!
I want to create standalone public NPM package that would consist solely of webpack marzipano build - so everyone could use power of unpkg.com and/or copy asset straight from node_modules without build phase.
Would this be ok with you / would this violate any legal concerns / do you have plans to do the same thing in near future?

**Comment by tjgq** [comment]
The latest npm release (0.6.0) includes the compiled marzipano.js and marzipano.swf files under the dist/ subdirectory. Apologies for the long delay!
