### ISSUE TITLE
Image upload problem

### ISSUE THREAD

**Issue by macema02** [google/marzipano#105]
Hello, when I upload 360 degree image to Marzipano tool, error message shows up with sign "Images not 1:1 cube faces or 2:1 spheres". I am new into this, so I want to ask you if you know what is causing the problem, or how I need to set the camera for image capturing. I did not found aspect ratio in camera settings (Niceboy Pano360). Thank you for your help.

**Comment by tjgq** [comment]
The tool expects equirectangular images uploaded into the tool to have an aspect ratio of exactly 2:1 (width is twice the height). Some 360 cameras produce images that are missing pixels at the bottom. In most cases you can use an image editor to pad them with black pixels before you upload them.

**Comment by Ash25-mayday** [comment]
@tjgq but what if we try to upload cube tiles? i tried uploading cube tiles separately but it doesn't accept them. I tried uploading all at once and single at a time, neither worked. Pls suggest something.
