### ISSUE TITLE
Image curvature on the edges

### ISSUE THREAD

**Issue by Logyra** [google/marzipano#106]
Hello guys, some time ago, I've started doing 360 photohraphy and I've noticed that on my images, subject in the center of the image (in focus) is displayed normally, while the same subject, while being on the edge of the image is being distorted. Examples below.

![curved](https://user-images.githubusercontent.com/13264517/31555725-74678978-b042-11e7-931f-da6aaf0a2e7a.jpg)
![not curved](https://user-images.githubusercontent.com/13264517/31555726-7488ef00-b042-11e7-9062-f6942400edad.jpg)

I also noticed that on some other websites and 360 photographies, this isn't the case, or the distortion isn't as extreme as in mine. Zooming the image does affect this, but I don't think that zooming alone is the fix. Examples below.

![lamp edge](https://user-images.githubusercontent.com/13264517/31555728-74ab1f8a-b042-11e7-9a94-23054019d962.jpg)
![lamp center](https://user-images.githubusercontent.com/13264517/31555729-74d13170-b042-11e7-9433-d353e3c90db5.jpg)
Note: Images taken from www.dubai360.com

Now my question here is, how do I get rid of the edge distortion and what is the cause of that? Is it the lens that I'm using? Is it the preview program itself? Is it the stitching program? I'm not sure if I posted the question on the right forum, so excuse me if this isn't the place for it.

**Comment by tjgq** [comment]
What you're seeing is the distortion characteristic of a wide angle lens (this has no relation to the lens you used to take the photo; it's inherent in the way panoramas are rendered). 

The distortion occurs when the field of view (fov) is too large, and it's stronger when the object is wider or closer to the photographer. The blue sign in your panorama is wider than the lamp post in Dubai360, so it gets distorted more. Also note that the Dubai360 panorama is displayed at a smaller fov, which doesn't look as bad.

To prevent the distortion, set a lower value for the maximum fov. Tours generated by the tool have a maximum of 100 degrees vertical and 120 degrees horizontal; you can change the limits by editing this line in index.js:

`var limiter = Marzipano.RectilinearView.limit.traditional(data.faceSize, 100*Math.PI/180, 120*Math.PI/180);`

In a somewhat more technical note: Marzipano displays panoramas using the so-called rectilinear projection. Some other viewers (e.g. krpano, which Dubai360 uses) also implement a hybrid rectilinear/fisheye projection, which trades off this kind of distortion against other kinds; but it's essentially impossible to render a panorama in a way that looks completely "natural" at a large fov.

**Comment by Logyra** [comment]
Ok, it's much clearer now. I'll try to implement the changes you suggested. Thanks for the detailed explanation.

**Comment by kuldip-shukla** [comment]
Hello guys, is there any possibility for different projection modes like dubai360.com?
![Screenshot from 2019-10-17 01-38-48](https://user-images.githubusercontent.com/46015733/66986044-b1066080-f0db-11e9-9b81-587cba534a7c.png)

If yes then please provide me direction. So, I can implement all this mode in mine.
