### ISSUE TITLE
Ignoring empty PNG tiles

### ISSUE THREAD

**Issue by jordyno** [google/marzipano#108]
I am adding transparent PNGs as layers on top of Scenes (panoramas). Many of the tiles are empty and just sit there to take up bandwidth and unnecessary HTTP requests of the viewer. Is there a way to make the viewer ignore loading PNG tiles smaller than certain size and not come up with error? Sure, getting to know the PNG tile size is already an HTTP request. In best case, maybe some array of excluded tiles supplied as an argument? 
This would save a lot of bandwidth and increase performance in such usage scenarios.

**Comment by tjgq** [comment]
The mapping of tiles into URLs occurs the ImageUrlSource. One way to avoid fetching multiple copies of the same transparent tile over and over is to write a custom ImageUrlSource that returns the same URL for every transparent tile. Something like:

```
var source = new Marzipano.ImageUrlSource(function(tile) {
  if (tileIsTransparent(tile)) {
    return "http://www.example.com/transparent.png"; // can be just a 1x1 transparent PNG
  } else {
    // return a "regular" file path, see ImageUrlSource.fromString()
  }
});
```

The `tileIsTransparent` function could either compare against a hardcoded list of transparent tiles, or perform a HEAD request to determine the file size. I'd recommend against the latter because 1) a small file size doesn't guarantee that the PNG is transparent and 2) the browser still has to send a request and receive a small amount of data back for each transparent tile.

**Comment by jordyno** [comment]
Thank you! I would definitely go with comparison against array of transparent tiles, which would be created during layer build. But I am having problems with "return a "regular" file path, see ImageUrlSource.fromString()" How would my syntax look like, if my original syntax for source was:
`				var source = Marzipano.ImageUrlSource.fromString(
					"tiles/pano1/{z}/{f}_y{y}_x{x}.jpg",
					{ cubeMapPreviewUrl: "tiles/pano1/preview.jpg" });
`

**Comment by jordyno** [comment]
Got it, took me a while to get to the tile properties, would be nice to have it in documentation
tile.face
tile.x
tile.y
tile.z

**Comment by jordyno** [comment]
Made it this far, all works except for preview:

`var source = new Marzipano.ImageUrlSource(function(tile) {
	if (tileIsTransparent(tile)) {
		return "http://www.example.com/transparent.png"; // can be just a 1x1 transparent PNG
	} else {
		if(tile.z === 0) { // preview (level 0)
			var y = this.defaultCubeMapFaceOrder.indexOf(tile.face) / 6;
			return {
				url: "tiles/pano/preview.jpg",
				rect: { x: 0, y: y, width: 1, height: 1/6 }
			};
		} else { // level > 1
			return {
				url: "tiles/pano/"+tile.z+"/"+tile.face+"_y"+tile.y+"_x"+tile.x+".jpg",
				rect: { x: 0, y: 0, width: 1, height: 1 }
			};
		}
	}
});
`

don't know how to point to defaultCubeMapFaceOrder variable

**Comment by tjgq** [comment]
For now, please copy the definition of `defaultCubeMapFaceOrder` from ImageUrlSource.js. We should probably export it in the public API.

**Comment by jordyno** [comment]
Hi again, 
at the moment I am returning and empty url path when the `tileIsTransparent` and trying to load layer after layer for better UX. Combining the above with your loading progress code [here](https://groups.google.com/forum/#!msg/marzipano/xszV2UIxeHY/QTiMqS2EBAAJ), I run into a problem with layers which contain empty tiles. A transparent `tile `both `hasAsset `and `hasTexture ` - which is logical - but I can't find a way to test or query `textureStore` if the `tile`'s url is an empty string. 
Do you have any idea?
Many thanks in advance!

**Comment by jordyno** [comment]
Actually ` if(textureStore.query(tileList[i]).hasAsset)` returns `false `for all tiles even though I have the following modification of `TextureStore`:

```javascript
TextureStore.prototype._loadTile = function(tile) {
  var source = this._source;
  var hasAsset = source.hasAsset.bind(source);

  if(hasAsset(tile)) {
    if (this._itemMap.has(tile)) {
      throw new Error('TextureStore: loading texture already in cache');
    }
    var item = new TextureStoreItem(this, tile);
    this._itemMap.set(tile, item);
  }
};
```

and the following mod of ImageUrl:
```javascript
ImageUrlSource.prototype.hasAsset = function(tile) {
  var url = this._sourceFromTile(tile).url;
  return (url === "") ? false : true;
};
```

**Comment by jordyno** [comment]
UPDATE:
Found a solution, using `textureStore.layer.source()._sourceFromTile(tileList[i]).url` works, although not sure if that is the most efficient way to do it.

**Comment by jordyno** [comment]
Another issue I am having is that when trying to output for console inside
`new Marzipano.ImageUrlSource(function(tile) { ...` function, it always gets fired twice? Any explanation for that?

**Comment by tjgq** [comment]
I'm not sure I understand the problem. If you have a `tileIsTransparent` function (which, presumably, takes a tile as an argument), why do you need the tile URL to determine if it's transparent?

The function you pass into the `ImageUrlSource` constructor gets called by the TextureStore whenever it wants to load a texture for the tile. If you haven't made any modifications to TextureStore, this should happen whenever the tile comes into view (in practice, because of the LRU cache, the tile may leave the view, come back in, and not trigger a second call).

**Comment by jordyno** [comment]
The only change I made to textureStore is inside the _loadTile prototype:
```javascript
TextureStore.prototype._loadTile = function(tile) {
  var source = this._source;
  var hasAsset = source.hasAsset.bind(source);

  if(hasAsset(tile)) {
    if (this._itemMap.has(tile)) {
      throw new Error('TextureStore: loading texture already in cache');
    }
    var item = new TextureStoreItem(this, tile);
    this._itemMap.set(tile, item);
  }
};
```
and added following inside ImageUrl.js as you suggested:
```javascript
ImageUrlSource.prototype.hasAsset = function(tile) {
  var url = this._sourceFromTile(tile).url;
  return (url === "") ? false : true;
};
```
So I do not know why it gets called twice.

Regarding the URL tile request I am making to determine if it's transparent: my issue might be quite trivial. I just can't find a property inside the textureStore object that would tell me if a particular tile is transparent or not. Or am I just looking at a wrong object? The textureStore.query(tileList[i]).hasAsset does not seem to help - always returning false.

**Comment by tjgq** [comment]
If `hasAsset(tile)` is false the texture is never loaded, so the TextureStore will repeatedly attempt to load it (follow the code that calls `_loadTile` to understand why). This is suboptimal, but in your case it's better than filling up the LRU cache with lots of identical transparent tiles. And as long as the `hasAsset` function is fast, it shouldn't have a significant impact on performance.

If I understood everything correctly, your loading progress code should look like this:

```
var tileList = [];
layer.visibleTiles(tileList);
for (var i = 0; i < tileList.length; i++) {
  if (tileIsTransparent(tileList[i])) {
    // tile is transparent, so we don't need to check - skip it
   continue;
  }
  if (!textureStore.query(tileList[i]).hasTexture) {
    // loading not finished yet
  }
}
```

i.e. you can tell whether the tile is transparent by calling your `tileIsTransparent` function, so you don't need to get that information from `TextureStore#query`.

**Comment by jordyno** [comment]
You are absolutely right Tiago! I don't know why I chose the more difficult way, but now I am using just `tileIsTransparent` function with one extra param after `tile`, - the `layerData.levels`. All works, you just made me wondering if it is good idea to _cancel the `TextureStoreItem `retry chain? Or maybe increase the retry timeout somehow?
