### ISSUE TITLE
tiles finished loading listener

### ISSUE THREAD

**Issue by jordyno** [google/marzipano#109]
Hello, I am putting several layers per scene onto stage. But some of them I would like to display (opacity: 1.0) only when all of the layer's requested tiles as per current View are loaded. Is there a way to achieve this simply?
Thank you!

**Comment by tjgq** [comment]
Have a look at [this thread](https://groups.google.com/d/msg/marzipano/xszV2UIxeHY/QTiMqS2EBAAJ).
