### ISSUE TITLE
keyboard event listener

### ISSUE THREAD

**Issue by mo3taz-abdallh** [google/marzipano#11]
Hello All
I want to have my own keyboard event listener for navigation and zooming, so is there any documentation fro this section.
Regards

**Comment by manuelcabral** [comment]
Hi,

Take a look at [registerDefaultControls()](https://github.com/google/marzipano/blob/master/src/controls/registerDefaultControls.js) for an example of creating key control bindings. You need to instantiate [KeyControlMethod](http://www.marzipano.net/reference/KeyControlMethod.html) and call [registerMethod()](http://www.marzipano.net/reference/Controls.html#registerMethod) on [Viewer.controls()](http://www.marzipano.net/reference/Viewer.html#controls).

**Comment by navjinder** [comment]
Hi @manuelcabral is there any code example of how this could be achieved?
