### ISSUE TITLE
PNG with (non)pre-multiplied alpha handling [rendering issue?]

### ISSUE THREAD

**Issue by jordyno** [google/marzipano#112]
I suspect there might be a rendering issue when using extra layers with transparent PNGs. The anti-aliased edges get black/grayish look. I made sure I provide a clean PNG without such edges. This issue can be mitigated with using higher resolution tiles, but still, if I pin first level and run out of LRU cache, I will still see the lower resolution. This is what it looks like when hires tiles are not loaded:

![image](https://user-images.githubusercontent.com/32031745/32133156-885e45c0-bbd2-11e7-82d8-9e014bc8e400.png)

**Comment by tjgq** [comment]
Can you provide a link to a working example?

**Comment by jordyno** [comment]
Of course, but please apologize the mess, it's only a test ;)
`http://panotest.noslush.com`

**Comment by jordyno** [comment]
@tjgq Excellent work! Thank you!

**Comment by jordyno** [comment]
@tjgq just for the record: what are the effects on the processing resources?

**Comment by tjgq** [comment]
I wouldn't expect to see a significant difference. There's a very minor change to the fragment shader, and we're now passing UNPACK_PREMULTIPLY_ALPHA_WEBGL which might actually make texture upload faster on some browsers. But I haven't measured anything.
