### ISSUE TITLE
Race condition in switchScene

### ISSUE THREAD

**Issue by etki** [google/marzipano#118]
Hi!
It seems that there is race condition if switchScene is called with tween animation right before old scene destroy. If done so, scene object is depopulated at the end of tween animation and thus doesn't have some expected values.

example: http://jsfiddle.net/mf09yd2L/1/
result: Uncaught TypeError: Cannot read property 'textureStore' of null (in console)

**Comment by tjgq** [comment]
Your code is requesting a transition, then destroying the old scene before the transition has a chance to complete. You should pass a callback to switchScene instead:

```
sceneA.switchTo({ transitionDuration: 1000 }, function() {
  // now the transition is complete and it's safe to destroy the old scene
  viewer.destroyScene(sceneB);
});
```

**Comment by etki** [comment]
Yes, i know, however it is not always possible. We're using Vue for dynamic scene and hotspot control, and the actual actions are taken in response to data change rather than being described in plain statement list.

**Comment by tjgq** [comment]
I'm not familiar with Vue, so without a concrete example it's harder to give further advice. But it seems to me that, if Vue is able to call `switchScene` with the `transitionDuration` argument, you should also be able to pass in the callback?

**Comment by tjgq** [comment]
Going back to the original issue: I agree that `switchScene` should not crash if one of the scenes is destroyed during the transition. However, I think `destroyScene` should always abort an ongoing transition if it involves the scene being destroyed; to do otherwise would make `destroyScene` an asynchronous operation, which is too surprising.

In other words, I think the crash should be fixed, but that won't make the transition work in your case (you still have to wait for it to finish before destroying the scene).

**Comment by etki** [comment]
@tjgq it's certainly not a doomsday error and can be hacked around, i just have a habit of reporting things that happen.
Vue and some other frameworks take data-watching approach: as a developer, i make handlers to mutate application state, and state watchers take actions when data changes (usually that's just HTML rendering). In case something vanishes from state - e.g. scene - application can and should run purge action, which boils down to `destroyScene`. In this scope application doesn't know if transition is in action: all that application knows is that array element has vanished. So it's quite hard to catch with Marzipano (or other third-party library) flow because source of changes is vague.
Again, it's not a blocker / major bug and i'm totally ok if no one ever will fix it because there are more interesting features up on the roadmap.

**Comment by tjgq** [comment]
Since 2835a0d, `destroyScene` no longer crashes when called during a transition.
