### ISSUE TITLE
Licensing 

### ISSUE THREAD

**Issue by jordyno** [google/marzipano#119]
If I would like to include DeviceOrientationControlMethod.js and/or some utility file used in utils and repackage it in my own project.js, how do I acknowledge licensing of these portions of code to Google when in fact it will be all including my own code inside one file?

**Comment by tjgq** [comment]
I would include the [Marzipano license](https://github.com/google/marzipano/blob/master/LICENSE) with the code to acknowledge the portions that came from Marzipano.
