### ISSUE TITLE
Tile load queue

### ISSUE THREAD

**Issue by jordyno** [google/marzipano#120]
With more layers, there are many concurrent tile downloads. Is it possible to postpone loading of a certain layer until first layer's tiles of the current view are loaded?

**Comment by tjgq** [comment]
No, sorry. Each TextureStore has its own load queue; the TextureStores aren't aware of each other, so they can't prioritize between themselves.

**Comment by jordyno** [comment]
How about creating layers per scene separately and timing their creation accordingly - would that be possible? Maybe I could create scenes with first layer only keeping the remaining layers in a waiting stack? The issue would be how to avoid stage running out of sync with viewer?

**Comment by tjgq** [comment]
We've decided to make some changes to the multi-layer API. It now looks like:

```
var scene = viewer.createEmptyScene({ view: view });
for each layer {
  scene.createLayer({ source: source, geometry: geometry, ... });
}
```

With this API a layer can be added at any time (and the stage will be updated accordingly) so I suppose you could try adding the foreground layers at a later time.

**Comment by jordyno** [comment]
Incredible work, Tiago! This API is so much better! Wow!

**Comment by jordyno** [comment]
Would it be a good idea to add some optional identifier to the layer object to make parsing through layers of each scene easier? Right now they are just stacked in an array and selecting them by their index is not reliable, as index gets changed each time a layer is added/removed.

**Comment by tjgq** [comment]
Why not keep a reference to the layer (returned by `Scene.createLayer`) instead of indexing the layer list?

**Comment by jordyno** [comment]
blink! I think that will be enough, thanks! :)
