### ISSUE TITLE
Google Maps / StreetView integration

### ISSUE THREAD

**Issue by jordyno** [google/marzipano#122]
Is there any way or a plan to make it possible to integrate Google Maps / StreetView API into scenes? 
What I am mainly looking for is a way to show paths to other scenes, not just hotspots, just like with StreetView. With enough data, it is quite simple to calculate positions, distances, etc., but to show directions is a more difficult task.

**Comment by tjgq** [comment]
Can you explain what you want to do a little bit better (regardless of the Maps API)?

**Comment by jordyno** [comment]
Basically I am trying to navigate people in a terrain which is inaccessible by car (forrests, mountains). My plan is to use hotspotContainer to give users kind of "checkpoints" for their desired route, displayed on a drone panorama. I should able to achieve this with usable accuracy. The point is, that it would be nice to connect these "hotspots" with bezier curves ideally, but straight lines could work too. It should be simple vector graphics such as lines in StreetView. I know Marzipano does not support vectors, but would there be some way? All I can think of is having a Tree.js vector layer on top of Marzipano, but syncing that with Marzipano Scene's View would be probably impractical, right?

**Comment by tjgq** [comment]
This would be difficult to do with hotspots. I agree it would make sense to put a separate layer on top of Marzipano. I don't think you can accomplish this with the Maps/Streetview API, unless you also use it to render your panorama.

To synchronize your overlay with the view, the projection matrix returned by `RectilinearView#projection` is everything you need to do the appropriate transformation. However, if you're using Three.js, it is easier to create a PerspectiveCamera directly from the view parameters.

I've never tried stacking WebGL contexts on top of each other, so I don't know whether it would have reasonable performance. I would try rendering something simple before investing too much on the actual problem.
