### ISSUE TITLE
npm run dev problem

### ISSUE THREAD

**Issue by Frankling** [google/marzipano#125]
![qq 20171117135046](https://user-images.githubusercontent.com/5674121/32931315-842b944a-cb9e-11e7-83d3-27cdd7f103b1.jpg)
npm run dev, there is something wrong happen.

**Comment by tjgq** [comment]
Is this on Linux?

Can you paste the result of running `./scripts/dev` directly?

**Comment by Frankling** [comment]
![qq 20171117144219](https://user-images.githubusercontent.com/5674121/32933796-bbcd180e-cba5-11e7-9c4b-a17829c2c556.jpg)
@tjgq

**Comment by tjgq** [comment]
Did you run `npm install`? The `mxmlc` invoked by the script, as well as the `.swc` file, are bundled with the `flex-sdk` package.
