### ISSUE TITLE
Level size is not multiple of tile size: 2288 512

### ISSUE THREAD

**Issue by Aykelith** [google/marzipano#128]
I'm using this script https://github.com/mpetroff/pannellum/blob/master/utils/multires/generate.py (which uses `nona`) to generate my multires faces but the script, at the edges, just cut the remaining space so I'm remaining with photos of size like 240x512 and 512x240 and I calculated the size and I'm getting 2288(4*512 + 240) but the library does not accept. How can I resolve the problem? Or if someone can give me a script to generate my images. Thanks

**Comment by tjgq** [comment]
The level size (i.e. the size of a cube face) must be a multiple of the tile size, and all tiles within a resolution level must be the same size (there can't be a shorter tile at the end). So it looks like you need to pass appropriate `--cubesize` and `--tilesize` arguments to the `generate.py` script.

If your input is an equirectangular image, take the cube size to be something like 1/4 of the equirectangular width (this should approximately preserve the resolution). Then find a submultiple of the cube size close to 512 for the tile size. You might have to adjust the cube size up or down a little to find an appropriate submultiple.

**Comment by TaylorDale** [comment]
This script actually wouldn't work for me until I made the original image a ^2 size. Now it is running well.
