### ISSUE TITLE
Animating layer opacity

### ISSUE THREAD

**Issue by jordyno** [google/marzipano#131]
Hi,
is there any simple way to animate layer opacity?

thank you!

**Comment by tjgq** [comment]
Use `Marzipano.util.tween`. For example, to go from 0 to 1 opacity in 1000 ms:

```
function update(x) {
  layer.setEffects({opacity: x});
}

function done() {}

Marzipano.util.tween(1000, update, done);
```

The return value of tween() is a function you can call to abort the animation (in case you need it).

Note that the scene switching logic overrides the layer opacity to perform the scene transition (this is an unfortunate design). So whatever opacity you set will not be preserved when you switch out of the scene and back.
