### ISSUE TITLE
Marzipano tool crashes on large projects

### ISSUE THREAD

**Issue by miladnick** [google/marzipano#137]
Hello everyone
its about a year im using marzipano tool to make Virtual Tours,
its ok when i make tours with points (photos) less than 50 shots, but when i try to make huge (more than 50 photos) Tours suddenly tool page crashes and cant reload it, that cause whole project to vanish.
im living in iran and im using VPN to access your site and tool, is that the cause? (but still im saying i dont have any problem when project has less than 50 photos, and also vpn connection is stable).
what do you suggest to resolve this issue?

Thanks in advance.

**Comment by jordyno** [comment]
50 panoramas is a lot of data. It depends on your browser, your computer specs and actual panorama size to determine how many panoramas is maximum. But if the tool crashes your system at 50 panoramas, I suggest you divide your tour into max. 40 panorama tours max and then combine them manually after each partial tour is generated by the tool.

**Comment by miladnick** [comment]
thanks for advice,
could you please guide me a little bit how to combine 2 different tours exported from marzipano tool to a single file?
is there any manual or guide?

thanks for spending time.

**Comment by jordyno** [comment]
First of all, make sure that particular scenes of each partial tour have a unique name.
Then say you exported `tour1.zip` and `tour2.zip` with your panoramas from the tool.
- extract `tour1.zip` into a folder e.g. `LargeTour`
- open the `tour2.zip` and extract the contents of `app-files/tiles` to `LargeTour/app-files/tiles`
- open `data.js` and `index.html` inside `LargeTour/app-files/` and their counterparts from `tour2.zip` using your favorite code editor
- inside `LargeTour/app-files/data.js` you need to extend the `scenes` variable and inside `index.html` just look for the `<ul class="scenes">` tag where you need to copy/paste tags from your `index.html` inside `tour2.zip`
- do the same for `tour3.zip`, etc...

**Comment by jordyno** [comment]
In general though, I do not think it's the best idea to have over 50 panoramas in one tour. Might be confusing for the user and actually could be better to have tours divided into smaller groups.

**Comment by miladnick** [comment]
i appreciate your kindness,
ive followed your instruction and solved the problem.
about the Tour content and length im agree with you but its a general file for an exhibition here.
after i finished the project ill share it here, perhaps ill receive feedback from you...

Regards.

**Comment by jordyno** [comment]
Glad I could help. Sure would be nice to see  :)

**Comment by miladnick** [comment]
here it is:
[http://enuma.ir/vt/TehranAutoShow2017/](url)
ill just add a sound to it,
im waiting for your feedback's :)

**Comment by jordyno** [comment]
nice work! would love to see it at a higher resolution though :)

**Comment by miladnick** [comment]
i'd like too, but only problem is that im using regular 360 camera's like samsung gear 360 and it doesn't export a higher resolution than 3840*1920, and i guess i should use a DSLR for higher quality like 6k*6k or 12k*12k...

**Comment by TimSG** [comment]
I too suffer the tool crash very often.  Also with a small amount of pano's (13 in my last case). They render properly (16Kx8K, around 15MB each), it's only until I start adding multiple hotspots that the tour crashes. Any other tips to try besides splitting the tour?

**Comment by jordyno** [comment]
Make sure your computer has at least 8GB ram, the more the better. Also, if you are uploading equirectangular panoramas, maybe you can save some memory by converting them to cubefaces offline first and then uploading those.

**Comment by TimSG** [comment]
Enough RAM available so I'll try the second option next time. Thanks!

Op vr 23 mrt. 2018 om 00:05 schreef Jordy <notifications@github.com>:
