### ISSUE TITLE
Layers optimal usage

### ISSUE THREAD

**Issue by jordyno** [google/marzipano#138]
Hi everyone!

My implementation suggests shared identical overlay layers on top of regular panorama layers. That means for example, that one scene will consist of winter and summer version of the same panoramatic view all aligned. My questions in this situation are following:
1. Would it increase system requirements rapidly when compared to panoramas sitting in each scene separately? Especially if I have panorama per each season, ie. 4 panoramas in one scene + extra layers (with only some tiles in place) on top of them?
2. Is it possible to create a transition between specific layers other than opacity animation? Mostly I am interested in a kind of mask animation - mask could be something like a DIV for the transitioning layer and would start with 0% width and 100% height and animate width towards 100% from left to right. Is that or something similar doable?

Of course, I know could always keep each season panorama in a separate scene, but since many of the layers are identical, I would prefer to avoid loading them again each time season is changed i.e. `sceneSwitch(scene)` gets called. Also the transition could be more fluid then?

Thanks for the help in advance and Happy Holidays to all of you!

**Comment by tjgq** [comment]
Whether the layers belong to the same scene or not shouldn't matter for performance; choose what is more convenient (in your case, a multi-layer scene sounds better).

I'm not sure I understand the transition you want to implement. Do you want to translate the top panorama from left to right, maintaining full opacity? Or do you want the top panorama to remain in the same place, but become progressively transparent, starting with the left pixels and ending at the right?

**Comment by jordyno** [comment]
Well, I was wondering about performance, since each layer has certain LRU (usually the default 32 in my case) + pinnedTiles and when we start multiplying this I was afraid it could potentially crash certain mobile browsers.
Maybe better name for the transition I am trying to achieve is blind. No change in opacity. Something like the demo [here](https://api.jqueryui.com/blind-effect/) - just imagine the original layer sitting at the bottom and the transitioning layer on top, appearing from the left. It would not change the position, only the mask would do the effect (like the gray rectangle on above example)

**Comment by jordyno** [comment]
Found a perfect example for the transition: https://codepen.io/ace/pen/BqEer

**Comment by tjgq** [comment]
Set a `rect` effect on the top panorama with a time-varying `relativeX` value:

```
layer.setEffect({ rect: { relativeWidth: 1, relativeHeight: 1, relativeX: /* from 0 to 1 */, relativeY: 0 } });
```

Yes, your point about memory consumption is correct. One layer per scene would ensure that the invisible layers don't take up memory (because TextureStores are cleared when a scene goes out of view).

The only way to achieve this with a single multi-layer scene is if you destroy the layers as they become invisible, and create them again when they become visible. Unfortunately, in your case it won't work: `Scene#createLayer` always creates the layer at the top of the stack, but you want to insert it under the fixed overlay layer.

On second thought, it's also not true that the rendering performance is the same: invisible layers are still "rendered" at zero opacity, because we don't optimize for that case. With separate scenes only a single scene is rendered (or two, during a transition).

**Comment by jordyno** [comment]
Would I be able to do a workaround by creating an empty "placeholder" layer sort of? And populating it with parameters as needed? Or maybe I just change sources on the go of the "other" layer not being shown at the moment? Could something like that work?

**Comment by tjgq** [comment]
Layers are immutable (there's no way to change the underlying source, geometry, etc once they've been created), so no.

I think a reasonable solution would be to modify `Scene#createLayer` to insert the a layer at a position other than the top (or add a `Scene#moveLayer` method to move it around). Then you could do the remove trick on invisible layers. `Stage#addLayer` and `Stage#moveLayer` already do something similar.

Another approach is to make `Stage#render` skip layers with zero opacity, then call `TextureStore#clearNotPinned` manually once the layer becomes invisible (the first part is a good idea anyway, the second is sort of a hack).

**Comment by jordyno** [comment]
Those are great ideas, thank you! Will probably try to implement both, since the "hack" might come in handy for my overlay layers, as they do not take up that much memory.

**Comment by jordyno** [comment]
Would the render skipping hack work and save processing power when used on hotspots too?
