### ISSUE TITLE
Feature request: block the rotation degrees of an image

### ISSUE THREAD

**Issue by nickrivers** [google/marzipano#140]
Hi!,
Is it possible to block the rotation degrees of an image? That is, instead of moving 360 in all directions, you can move, for example 270 only.

I need to visualize images with zones that have nothing, and I would like to be able to block them. It's possible?

Regards!

**Comment by jordyno** [comment]
Hi, please take a look [here](https://github.com/google/marzipano/issues/134)

**Comment by tjgq** [comment]
Duplicate of #134.
