### ISSUE TITLE
Is there a method of adding scroll / pan easing?

### ISSUE THREAD

**Issue by heaversm** [google/marzipano#141]
Similar to the default for [panellum](https://pannellum.org/)

**Comment by jordyno** [comment]
Yes, each [ControlMethod](http://www.marzipano.net/reference/ControlMethod.html) has it's own [Dynamics](http://www.marzipano.net/reference/Dynamics.html)

**Comment by heaversm** [comment]
Great thanks!

**Comment by Joebayld** [comment]
Is it possible to get an example on how to update this?

**Comment by tjgq** [comment]
As I mentioned in https://groups.google.com/g/marzipano/c/41cR4WcFQ4o/m/qjfAFiGHAAAJ, the only way to customize the control acceleration/friction parameters at the moment is by editing the initialization code at https://github.com/google/marzipano/blob/master/src/controls/registerDefaultControls.js#L50.
