### ISSUE TITLE
HotspotContainer#createHotspot is missing documentation for the `opts` parameter

### ISSUE THREAD

**Issue by jordyno** [google/marzipano#142]
Hi all,
could anyone please elaborate what exact params/options are available/expected in the [HotspotContainer#createHotspot](http://www.marzipano.net/reference/Hotspot.html) ?
My intent is to create a `hotspot` which would change in size in respect to the current `view` FOV, i.e. it will cover always the same area in respect to underlying panorama, no matter the FOV. So I guess `perspective.radius` or the `params` might help me?

Many thanks!

**Comment by tjgq** [comment]
The `opts` parameter to `HotspotContainer#createHotspot` has the same meaning as the `opts` parameter to the `Hostpot` constructor (I'll add the missing documentation soon).

For embedded hotspots whose size doesn't change with the fov, use `perspective.radius`. The meaning of the parameter is tied to the CSS 3D transforms spec. The simplest description is this: if `perspective.radius` is equal to the radius of the pano sphere, then a 1-pixel hotspot (as determined by the size of the DOM element) will cover exactly 1 pano pixel.

If you're trying to cover a region of the panorama with the hotspot, you may additionally need to rotate it using the `perspective.extraRotations` parameter. It usually involves some amount of trial and error (but see [this thread](https://groups.google.com/forum/#!topic/marzipano/5-cIAUu8weM) for an alternative approach).

**Comment by jordyno** [comment]
thank you Tiago! I just tried it with the perspective.radius and it's difficult to guess the right parameters. Furthermore, it seemed quite resources intensive, so I would like to try a different approach. Especially with dozens of such hotspots expected, the 3D transforms might cause unnecessary CPU/GPU usage.

I actually do not need to cover a specific region of the panorama exactly. All I need is that the centerpoint of the hotspot element stays on same position all the time. It would be enough if there are no 3D transforms, just the scale of the hotspot element should decrease linearly with fov. One of the reasons is if there are more hotspots next to each other, that they do not overlap when zoomed out.

I am thinking about just creating regular hotspots and listening to `viewChange` and parse through all the hotspots which should have this behavior and scale them accordingly. Do you think that is the most efficient way to do it?

**Comment by lianee** [comment]
> The simplest description is this: if `perspective.radius` is equal to the radius of the pano sphere, then a 1-pixel hotspot (as determined by the size of the DOM element) will cover exactly 1 pano pixel.

Sorry for this probably very basic question, but how do I find the "radius of the pano sphere"?

I found a post [(here)](https://groups.google.com/g/marzipano/c/MEmXVf-h-So/m/lYwQZRhABwAJ) where you told that it was somehow related to the "facesize" parameter, but I am not comfortable using an empirical method of trial and error to find a satisfactory value.
The "embedded-hotspots" demo uses a radius of 1640 with a facesize of 4096? Since the facesize generated with the tool is of 1344 for me, would it be a matter of setting it proportionnaly, that is 1640*1344/4096=538?
