### ISSUE TITLE
Feature request: Changelog

### ISSUE THREAD

**Issue by jimblue** [google/marzipano#148]
Thank you guy for the new Marzipano release, but what is it about?

IMO this repo need a changelog so users can decide to upgrade or not when you push a new release, don't you think?

**Comment by tjgq** [comment]
Yes, that sounds totally reasonable. I'll add one starting with the next release.

In the meantime, you can look at the [commit list](https://github.com/google/marzipano/commits/master) to get an idea of what went in (each release is marked with a commit whose description is just the release number). But I do agree that a high-level summary would be helpful.
