### ISSUE TITLE
Support for save and load a project

### ISSUE THREAD

**Issue by esmadja** [google/marzipano#15]
It would be great if you could save and then load a project or edit an existing zip file created from an export.
This would make working on a project in an incremental basis very easy.

**Comment by manuelcabral** [comment]
That is a good idea, but there are no plans to add new features to the Marzipano tool in the near future.

Closing the issue because this repository is only for the Marzipano viewer library.

**Comment by sreed101** [comment]
If someone reading this ever wants to implement this on their own, they could decompile app.js. Search for:

` var r = ["app-files", "tiles", t.uniqueId()];`

**t** contains all the active state data. The tile data makes the json blob 80mb+, so potentially one could not save the tile data, keep the other settings and save that state information in a json file. The information is already saved in data.js so one could just parse it from that also. Then either load the same pano images and be able to restore the hotspot/info things, or even upload the zip archive and have the tile image data converted into the javascript object (harder difficulty).

**Comment by elik745i** [comment]
Hi any success on save/load project implementation? This would be very handy!!!

**Comment by yashwantrkamath** [comment]
> If someone reading this ever wants to implement this on their own, they could decompile app.js. Search for:
> 
> ` var r = ["app-files", "tiles", t.uniqueId()];`
> 
> **t** contains all the active state data. The tile data makes the json blob 80mb+, so potentially one could not save the tile data, keep the other settings and save that state information in a json file. The information is already saved in data.js so one could just parse it from that also. Then either load the same pano images and be able to restore the hotspot/info things, or even upload the zip archive and have the tile image data converted into the javascript object (harder difficulty).

@ReallyNotARussianSpy Can you please help a little more with this?

I am newbie to js and json etc.

What I could do till now is find the app.js from developer tools, and i could find "var r = ["app-files", "tiles", t.uniqueId()];`" within the code. But then I dint understand what is meant by "decompile"  and the rest
