### ISSUE TITLE
CSS issue with hotspots in FF 58.0.2

### ISSUE THREAD

**Issue by jmiba** [google/marzipano#150]
Info hotspots as generated with the Marzipano tool behave awkwardly in FF 58.0.2: There is a flickering ghost of the textbox in the top left corner of the canvas till the animation has finished.

**Comment by tjgq** [comment]
It should be fixed now. Both the Marzipano Tool and the [demo](http://www.marzipano.net/demos/sample-tour/index.html) have been updated (you might have to clear the browser cache to get the fixed version).

Please reopen if you're still seeing issues.

**Comment by jmiba** [comment]
Thanks, works fine. Weird though, this flickering when using rotateX(90deg).
