### ISSUE TITLE
How to use marzipano in vue

### ISSUE THREAD

**Issue by Ajauregui69** [google/marzipano#155]
Is there any example of how to use this library on VUE?

**Comment by oocpawel** [comment]
in template you can add simple div:

<div ref="test"/>

than use it in script like this:

var element = this.$refs.test;
var viewer = new this.$marzipano.Viewer(element);

**Comment by Ajauregui69** [comment]
Thank you, you are the bes

**Comment by Ajauregui69** [comment]
Thank you

**Comment by Ajauregui69** [comment]
Do you know why i get this error? ERROR: 0:1: '.' : syntax error

**Comment by Ajauregui69** [comment]
> <template>
  <div id="container" ref="test">
  </div>
</template>

<script>
  import marzipano from 'marzipano'

  export default {
    props: {
      image: {
        type: String,
        required: true
      },
      id: {
        type: String,
        required: true
      }
    },
    computed: {
      createPropScene () {
      }
    },
    mounted: function () {
      let element = this.$refs.test
      let viewer = new marzipano.Viewer(element)
      let source = new marzipano.ImageUrlSource.fromString('../../../../static/source_picture.jpg')
      let geometry = new marzipano.CubeGeometry([{tileSize: 1024, size: 1024}])
      let limiter = marzipano.RectilinearView.limit.traditional(4096, 100 * Math.PI / 180)
      let view = new marzipano.RectilinearView(null, limiter)
      let scene = viewer.createScene({
        source: source,
        geometry: geometry,
        view: view
      })
      scene.switchTo()
    }
  }
</script>

<style lang="scss" scoped>
  #container {
    height: 100%;
    position: relative;
    width: 100%;
    .view-container {
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
    }
  }
</style>

**Comment by Ajauregui69** [comment]
<template>
  <div id="container" ref="test">
  </div>
</template>

<script>
  import marzipano from 'marzipano'

  export default {
    props: {
      image: {
        type: String,
        required: true
      },
      id: {
        type: String,
        required: true
      }
    },
    computed: {
      createPropScene () {
      }
    },
    mounted: function () {
      let element = this.$refs.test
      let viewer = new marzipano.Viewer(element)
      let source = new marzipano.ImageUrlSource.fromString('../../../../static/source_picture.jpg')
      let geometry = new marzipano.CubeGeometry([{tileSize: 1024, size: 1024}])
      let limiter = marzipano.RectilinearView.limit.traditional(4096, 100 * Math.PI / 180)
      let view = new marzipano.RectilinearView(null, limiter)
      let scene = viewer.createScene({
        source: source,
        geometry: geometry,
        view: view
      })
      scene.switchTo()
    }
  }
</script>

<style lang="scss" scoped>
  #container {
    height: 100%;
    position: relative;
    width: 100%;
    .view-container {
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
    }
  }
</style>
