### ISSUE TITLE
Scroll

### ISSUE THREAD

**Issue by Ajauregui69** [google/marzipano#156]
Is there a way to cancel the zoom by doing scroll?

**Comment by tjgq** [comment]
You can disable scroll zooming by passing in the `scrollZoom` control option when instantiating Viewer:

```
var viewer = new Marzipano.Viewer(element, { controls: { scrollZoom: false } });
```

**Comment by Ajauregui69** [comment]
You the best!!!!! TY

**Comment by alec87** [comment]
viewer.controls().disableMethod("scrollZoom")
