### ISSUE TITLE
DragCursor

### ISSUE THREAD

**Issue by Ajauregui69** [google/marzipano#158]
How do you set up the dragCursor

**Comment by Ajauregui69** [comment]
i want to change de default cursor config, inset of move i want to show a grab cursor is that possible?

**Comment by tjgq** [comment]
Embarrassingly, there was an undocumented option in the `Viewer` class to override the cursors, but it didn't actually do anything. I've documented it and made it work. Your use case would look like:

`var viewer = new Marzipano.Viewer({ cursors: { drag: { active: 'grab' } });`

**Comment by Ajauregui69** [comment]
`let viewer = new Marzipano.Viewer(pano, {controls: {scrollZoom: this.zoom}}, {cursors: { drag: { active: 'grab' } }})`

i try to override the cursor like this, but nothing happened

**Comment by tjgq** [comment]
Have you compiled a build from the latest version of the code following the instructions in README.md? The fix hasn't made it to a release yet.

**Comment by Ajauregui69** [comment]
How do i can applay the changes?

**Comment by Ajauregui69** [comment]
how can i apply the changes?

**Comment by tjgq** [comment]
Make sure you have Node.js and a Java SDK installed, clone the git repository, and run `npm install` followed by `npm run release`. This will create a `marzipano.js` file in the `dist` directory, which you can use in place of the latest release.

**Comment by Ajauregui69** [comment]
`npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "release"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! marzipano@0.7.1 release: `scripts/release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the marzipano@0.7.1 release script 'scripts/release'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the marzipano package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripts/release
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs marzipano
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls marzipano
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Sandbox\marzipano\npm-debug.log
`

when i write `npm run release` or any script show this error

**Comment by tjgq** [comment]
Can you try running `scripts/dev` directly, instead of invoking it via `npm run`? (This would be issue #3, which is a long-standing issue on Windows).

**Comment by Ajauregui69** [comment]
Still the same :/

**Comment by Ajauregui69** [comment]
i upgrade node and npm, and now the error is `npm ERR! missing script: ./scripts/dev
`

**Comment by tjgq** [comment]
If you're getting an error from npm, you're not running the script directly.

Are you using Git Bash? These are shell scripts, so they require a Unix-like environment to run.
