### ISSUE TITLE
Support for multiple initial views

### ISSUE THREAD

**Issue by esmadja** [google/marzipano#16]
When using the tool to support a virtual tour it would add to the feeling of immersion if your could enter a room view the appropriate initial view.
e.g. when entering the living room from room 1 (rm 1) the initial view setting (iv1) should be different then when enter the living room from room 2 (rm 2) i.e. iv2

|-----------|
| ....iv1....|----------|
| .............|............|
| iv2............rm 2..|
| .............|............|
|..............|----------|
|----- .  -----|
|..............|
|...rm 1... |
|..............|
|------------|

**Comment by manuelcabral** [comment]
We are not planning to add this feature to the tool. The only way to implement this is by editing the exported code.
