### ISSUE TITLE
Small size panorama and quality issue with full screen

### ISSUE THREAD

**Issue by mameara** [google/marzipano#160]
I set small fixed width and height (500x500) for canvas container in sample-tour demo and change it to fullscreen when I click on fullscreen the result was bad quality resolution and the hotspot floats. but everything will be good if you resize the window.
So the function of changing the canvas size work only on resize.
Any solution?

**Comment by tjgq** [comment]
I find it surprising that the browser doesn't emit a window resize event
when it goes to fullscreen, but you can force an update yourself by calling
viewer.updateSize().

**Comment by mameara** [comment]
It work with me thanks
