### ISSUE TITLE
Tripod Cover

### ISSUE THREAD

**Issue by tkdan235** [google/marzipano#161]
I'm looking to implement a tripod cover.  To start with just a black circle to cover the tripod, eventually I'll want to use different images.  I poked around the examples, docs and the source code but didn't see the obvious way to handle this.  Any suggestions?  Thanks!

**Comment by manuelcabral** [comment]
You can do this with an embedded hotspot (see the links below). Another
possibility is to add the tripod cover in the panorama itself before
processing it with the Marzipano tool.

http://www.marzipano.net/demos/embedded-hotspots/index.html
https://github.com/google/marzipano/tree/master/demos/embedded-hotspots

**Comment by tkdan235** [comment]
Thanks for the reply and links to hotspots.  This is definitely the right solution.  After playing with this I am running into one issue, if I move the image around the hotspot won't stay in the same position.  So if I have the hotspot covering the tripod with the photo positioned a certain way, if I move the image then the tripod is no longer covered.  This may make more sense with the screenshots below.  I also included the code I am using in case I am missing something.  Any idea how to force the hotspot to remain in the bottom most position of the 360 photo?

HTML:
```html
<div id="tripodCover">
  <div className="tripodCover" />
</div>
```
CSS:
```css
.tripodCover {
  width: 400px;
  height: 400px;
  background: yellow;
  border: 3px solid red;
  border-radius: 50%;
}
#tripodCover {
  border: 4px green solid;
  border-radius: 50%;
}
```
JS:
```javascript
// Get the hotspot container for scene.
const container = scene.hotspotContainer();

// Create hotspot with different sources.
container.createHotspot(document.getElementById('tripodCover'), {
  yaw: 0,
  pitch: 90,
});
```

![image](https://user-images.githubusercontent.com/3709575/39269139-e44f4780-4886-11e8-89e4-a088c0d75b4e.png)

![image](https://user-images.githubusercontent.com/3709575/39269160-f5630d86-4886-11e8-8957-2e7e3bac837d.png)

![image](https://user-images.githubusercontent.com/3709575/39269183-01b7cee6-4887-11e8-9ea1-06a2c42344c7.png)

![image](https://user-images.githubusercontent.com/3709575/39269204-123b8f82-4887-11e8-83c7-58b548f010e6.png)

**Comment by tjgq** [comment]
You need to set a perspective radius in order to embed the hotspot into the
panorama at a fixed size (as in here
<https://github.com/google/marzipano/blob/master/demos/embedded-hotspots/index.js#L55>).
The right value for the radius parameter, unfortunately, is not
straightforward to determine (see this post
<https://groups.google.com/d/msg/marzipano/MEmXVf-h-So/lYwQZRhABwAJ>). But
trial and error usually works.

**Comment by tkdan235** [comment]
I played with the perspective a bit and was able to get something decent working.  I have to admit though, I have no idea how this works.  The documentation placement for this doesn't exist, I had to look at the source code and the examples you provided to make some guesses.  I'll provide the code below for anyone trying to figure this out in the future.  I just wish I could explain why `pitch: -80.1` ended up being straight down covering the tripod.

```html
<div id="tripodCover">
  <div className="tripodCover" />
</div>
```

```css
.tripodCover {
  width: 400px;
  height: 400px;
  background: #000;
  border-radius: 50%;
}
```

```javascript
// Get the hotspot container for scene.
const container = scene.hotspotContainer();

// Create hotspot with different sources.
container.createHotspot(
  document.getElementById('tripodCover'),
  { yaw: 0, pitch: -80.1 },
  {
    perspective: {
      extraRotations: 'rotateZ(0deg) rotateY(0deg)',
      radius: 1000,
    },
  },
);
```

This results in the following:

![image](https://user-images.githubusercontent.com/3709575/39277350-36fd19a6-48a2-11e8-89ea-a8e70dc1ddc1.png)

![image](https://user-images.githubusercontent.com/3709575/39277367-41d5d426-48a2-11e8-8460-ce40389c265d.png)

![image](https://user-images.githubusercontent.com/3709575/39277388-5054dbd2-48a2-11e8-8322-9137231e7fc5.png)

![image](https://user-images.githubusercontent.com/3709575/39277400-6293dcbc-48a2-11e8-8d4d-72df2983b4be.png)

**Comment by manuelcabral** [comment]
Pitch and yaw and defined in radians rather than degrees. So the pitch for
the point straight down should be -Math.PI/2 or approximately -1.57.

**Comment by tkdan235** [comment]
Ah okay that make more sense, I made the poor assumption it was in degrees.  I'll be researching radians so I get a good understanding of this.  Thank you for your reply, you have been a huge help.

`-Math.PI/2` ended up being straight up.  With `Math.PI/2` my tripod cover is now straight down.

Here is my updated js for anyone who may be trying to do the same thing:

```javascript
// Get the hotspot container for scene.
const container = scene.hotspotContainer();

// Create hotspot with different sources.
container.createHotspot(
  document.getElementById('tripodCover'),
  { yaw: 0, pitch: Math.PI / 2 },
  {
    perspective: {
      extraRotations: 'rotateZ(0deg) rotateY(0deg)',
      radius: 1000,
    },
  },
);
```
