### ISSUE TITLE
Insert 360 Video in the Virtual Tour list

### ISSUE THREAD

**Issue by khookeiwai** [google/marzipano#168]
Hi there, recently I tried to insert the 360 video inside the virtual tour list, but failed. Would like to ask how do I insert it?
![123](https://user-images.githubusercontent.com/30516072/40401732-680d81f0-5e7a-11e8-83ae-b302f57da666.jpg)

I also tried by using Marzipano Tool but it can't upload by video, please help.

**Comment by tjgq** [comment]
The Marzipano Tool doesn't support adding videos, sorry.

It can however be done with some Javascript programming, as shown in [this demo](https://github.com/google/marzipano/tree/master/demos/video).
