### ISSUE TITLE
player errors on wildcard value in Access-Control-Allow-Origin Header

### ISSUE THREAD

**Issue by SlickSwick** [google/marzipano#174]
When accessing content from CDN that has a wildcard value of \*.domain.com in the Access-Control-Allow-Origin header, Marzipano player responds with the following error: Failed to load https://media.domain.com/360_test_video.mp4: The 'Access-Control-Allow-Origin' header contains the invalid value '\*.domain.com'. Origin 'https://test.domain.com' is therefore not allowed access.

**Comment by tjgq** [comment]
This is a browser error, not a Marzipano bug. According to the [CORS spec](https://www.w3.org/TR/cors/#access-control-allow-origin-response-header), the `Access-Control-Allow-Origin` header must contain either a valid URI, or the string `*`. In your case, you must set it to either `*` or `https://test.domain.com`.
