### ISSUE TITLE
Error loading: C:\Program Files\Java\jre1.8.0_77\bin\server\jvm.dll

### ISSUE THREAD

**Issue by kangPrayit** [google/marzipano#175]
I try to execute 
$ ./scripts/dev

but got
Error loading: C:\Program Files\Java\jre1.8.0_77\bin\server\jvm.dll

I already set my JAVA_HOME to C:\Program Files\Java\jre1.8.0_77
![screenshot_26](https://user-images.githubusercontent.com/6687727/42018303-df523fc6-7adb-11e8-9fa5-6d1a32593b93.png)

did i miss some configuration?

someone help me please.

**Comment by tjgq** [comment]
I suspect the issue is that the Flex SDK is incompatible with the 64-bit JRE (as noted in the README file). You must install the 32-bit version instead.

See https://stackoverflow.com/questions/2955280/mxmlc-and-64bit-jre and https://issues.apache.org/jira/browse/FLEX-18407.
