### ISSUE TITLE
Module not found: Can't resolve 'glslify'

### ISSUE THREAD

**Issue by saricden** [google/marzipano#176]
On a fresh installation of ReactJS, using create-react-app, I installed Marzipano via `npm install marzipano --save`.

Then edited the default App.js file generated by create-react-app, like so:
```
import React, { Component } from 'react';
import './App.css';
import Marzipano from 'marzipano'; // Note importing Marzipano here

class App extends Component {
  componentDidMount() {

  }
  render() {
    return (
      <div className="App">
        <h1>Pano Test</h1>
        <div ref={el => this.el = el} />
      </div>
    );
  }
}

export default App;
```

And upon running `npm run start` the following error appears:

Failed to compile
./node_modules/marzipano/src/renderers/WebGlEquirect.js
Module not found: Can't resolve 'glslify' in '/home/kirk/apps/360kirk/node_modules/marzipano/src/renderers'

I checked the [Marzipano npm page](https://www.npmjs.com/package/marzipano), and noted that glslify is a dev dependency.

Could the fix be as simple as changing it to be a normal dependency?

**Comment by saricden** [comment]
Note I just installed glslify as a dependency in my React app and it fixed the error.

**Comment by tjgq** [comment]
Yes. This was fixed in https://github.com/google/marzipano/commit/b4b0000db56b63d25dfa55a9b01e26651ff63b10, but it hasn't made it into a release yet.

**Comment by saricden** [comment]
Brilliant, cheers!
