### ISSUE TITLE
glslify is not compatible with Webpack

### ISSUE THREAD

**Issue by saricden** [google/marzipano#177]
Next problem from my environment (ReactJS / Webpack generated by create-react-app):

I'm trying to integrate ReactJS with Marzipano, however I'm now stuck on an issue of nothing but a white screen being rendered, with no errors in the console.

Marzipano appears to be loading, however, as the div I'm binding it to has been resized, and if you click and drag the cursor changes to a closed hand, which would not be the default behavior. My code looks like this:

```
import React, { Component } from 'react';
import './App.css';
import Marzipano from 'marzipano';

class App extends Component {
  componentDidMount() {
    this.panoViewer = new Marzipano.Viewer(this.pano);

    // Create source.
    var source = Marzipano.ImageUrlSource.fromString(
      "img/test.jpg"
    );

    // Create geometry.
    var geometry = new Marzipano.EquirectGeometry([{ width: 4000 }]);

    // Create view.
    var limiter = Marzipano.RectilinearView.limit.traditional(1024, 100*Math.PI/180);
    var view = new Marzipano.RectilinearView({ yaw: Math.PI }, limiter);

    // Create scene.
    var scene = this.panoViewer.createScene({
      source: source,
      geometry: geometry,
      view: view,
      pinFirstLevel: true
    });

    // Display scene.
    scene.switchTo();
  }
  render() {
    return (
      <div className="App">
        <h1>Pano Test</h1>
        <div ref={pano => this.pano = pano} />
      </div>
    );
  }
}

export default App;
```
I was following the source code of the example [here](http://www.marzipano.net/demos/equirect/index.html). The only thing I changed is the image source, but to be safe I did also test with the original image in the example.

My only thought after looking around on the web is perhaps this is a WebGL texture thing... But I don't think it's a max texture size issue, because if it was then the example I linked above wouldn't work on my device, and it does.

**Comment by saricden** [comment]
If it's of any help, this is the markup that's being generated by React + Marzipano:

```
<div class="App">
  <h1>Pano Test</h1>
  <div style="overflow: hidden; cursor: default;">
    <canvas width="796" height="0" style="position: absolute; height: 100%; width: 100%;"></canvas> 
    <div style="position: absolute; height: 100%; width: 100%; touch-action: none; user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);">
      <div style="position: absolute; height: 100%; width: 100%; background-color: rgb(0, 0, 0); opacity: 0;"></div>
       <div style="position: absolute; pointer-events: none; display: block; transform: translateX(0px) translateY(0px) translateZ(0px); height: 0px; width: 0px; overflow: visible;">
         <div style="position: absolute; pointer-events: all; opacity: 1;"></div>
      </div>
    </div>
  </div>
</div>
```

**Comment by oocpawel** [comment]
The problem is with canvas height="0", i dont know react, I am using marzipano in vue.js, but it looks like 'this.pano' height is 0px, so in the end canvas is generated with height=0px, first find out why this.pano is 0, than everything should be ok

**Comment by saricden** [comment]
Will investigate and post if this solves it, thanks!

**Comment by saricden** [comment]
Hmm, okay, so I first tried applying a height of 100px to the containing div with inline styles, then I tried 100vh, then I tried both again but with a class. Each time I tried I got the following error in my JS console:

Uncaught ERROR: 0:1: '.' : syntax error


Repeated several times, and if I drag the stage it's now rather laggy and throws this error a bunch more times... Not sure what to make of this error. It's coming from WebGlCommon.js:34. The screen is still white, as before, but the div has a height now.

However, despite the div having a height, the canvas still has height="0"... Very odd.
Even though the canvas's height attribute is 0, it has some CSS being applied to it that's causing it to take up the full viewport height when I inspect it using Chrome devtools.

This is all the relevant info I can think of, but if anyone has any ideas or needs some specific details I haven't mentioned, post a reply and I'll get on it ASAP.

**Comment by oocpawel** [comment]
I am not sure if "img/test.jpg" is handled by marzipano correctly, try to use an url to external photo from demo: "//www.marzipano.net/media/equirect/angra.jpg"

**Comment by tjgq** [comment]
Marzipano doesn't set the dimensions of the containing element, so if the height is 0 that points to a problem elsewhere. In addition, you need to call `Viewer#updateSize` whenever the dimensions of the containing element change (except in case of a window resize - those are handled automatically).

WebGlCommon.js:34 is a WebGl shader compilation error, which would suggest either a bug in the Marzipano shader, or a faulty WebGl implementation. Have you checked that the Marzipano demos work correctly on that particular machine/browser combination?

**Comment by saricden** [comment]
@oocpawel I actually tried that as well with the exact image you mentioned from the demo. Forgot to mention that. But it gave me the same results as my own panorama image. Mine's just a bit smaller, but I modified the width being provided to Marzipano.EquirectGeometry.

@tjgq I have checked the demos and they do work correctly on my machine... So I think it's a problem with my setup.

I tried calling Viewer#updateSize, and that did indeed update the canvas' height from height="0" to height="763" (calculated height of my viewport in pixels) which is a step in the right direction, as my CSS is setting the containing div's height to 100vh.

Could it be that the containing div isn't at the root of the HTML body? React wraps everything in a root element (usually a div, as it is in my case), so I wonder if wrapping the containing div is causing issues?

Still not sure how that explains the WebGl shader error though. In all honesty I don't know a ton about WebGl, as I usually use libraries that wrap those functions. It's on my to-learn list!

**Comment by saricden** [comment]
If it's helpful for anyone to replicate my issue, I can push my React project to an orphaned branch on the Marzipano repo or a new repo.

**Comment by saricden** [comment]
Also, would it be worth starting a separate issue? The white screen is still a problem, but the WebGl errors are new.

**Comment by tjgq** [comment]
It would help to have a look at a minimal example.

**Comment by saricden** [comment]
@tjgq For sure. But um, sorry if this is max noob level,  but I created an orphaned branch on Marzipano w/ the react project example, but trying to push my branch results in the following error:

ERROR: Permission to google/marzipano.git denied to saricden.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I thought there was no problem pushing to a new branch on open source projects, but you need to make a pull request to merge into master? Sorry I've used Git a lot but I'm still a noob in the open source scene.

**Comment by tjgq** [comment]
Please make a fork of the repository and push your changes there.

**Comment by pangzineng** [comment]
I had the same WebGlCommon.js error while trying to setup for React, I did what I consider a minimum setup, here is my code:

```
import React, { Component } from 'react';
import './App.css';

const Marzipano = require('marzipano')

class App extends Component {

  constructor (props) {
    super(props)
    this.pano = React.createRef();
  }

  componentDidMount() {
    var viewer = new Marzipano.Viewer(this.pano.current);
    var source = Marzipano.ImageUrlSource.fromString(
      "//www.marzipano.net/media/outdoors/{z}/{f}/{y}/{x}.jpg",
      { cubeMapPreviewUrl: "//www.marzipano.net/media/outdoors/preview.jpg" });
    var geometry = new Marzipano.CubeGeometry([
      { tileSize: 256, size: 256, fallbackOnly: true },
      { tileSize: 512, size: 512 }
    ]);
    var limiter = Marzipano.RectilinearView.limit.traditional(4096, 100*Math.PI/180);
    var view = new Marzipano.RectilinearView(null, limiter);
    var scene = viewer.createScene({
      source: source,
      geometry: geometry,
      view: view,
      pinFirstLevel: true
    });
    scene.switchTo();
  }

  render() {
    return (
          <div id="pano" ref={this.pano}></div>
    );
  }
}

export default App;
```
Basically all copied from the demo scripts.
But when the `scene.switchTo()` function is triggered, it crash with many lines of WebGlCommon error like this:
```
Uncaught ERROR: 0:1: '.' : syntax error

  | createShader | @ | WebGlCommon.js:34
  | createShaderProgram | @ | WebGlCommon.js:42
  | WebGlBaseRenderer | @ | WebGlBase.js:65
  | WebGlCubeRenderer | @ | WebGlCube.js:28
  | ./node_modules/marzipano/src/stages/WebGl.js.WebGlStage.createRenderer | @ | WebGl.js:197
  | ./node_modules/marzipano/src/stages/Stage.js.Stage._updateRenderer | @ | Stage.js:435
  | ./node_modules/marzipano/src/stages/Stage.js.Stage.render | @ | Stage.js:355
  | ./node_modules/marzipano/src/RenderLoop.js.RenderLoop._loop | @ | RenderLoop.js:140
  | requestAnimationFrame (async) |   |  
  | ./node_modules/marzipano/src/RenderLoop.js.RenderLoop.renderOnNextFrame | @ | RenderLoop.js:127
  | ./node_modules/marzipano/src/RenderLoop.js.RenderLoop.start | @ | RenderLoop.js:105
  | Viewer | @ | Viewer.js:187
  | componentDidMount | @ | App.js:17
```

**Comment by tjgq** [comment]
It appears that under the Webpack-based environment set up by `create-react-app`, `glslify` doesn't work properly (which is perhaps not surprising, since it is meant to be used with Browserify, not Webpack). As a consequence, the strings `../shaders/vertexNormal` and `../shaders/fragmentNormal` are interpreted as shader source code instead of paths.

The workaround at the moment is to use a pre-built version of Marzipano (one can be found in the `dist` directory inside the `npm` package). Going forward, we'll need a better solution, since it is obviously desirable to support loaders other than Browserify.

**Comment by tjgq** [comment]
I've removed the dependency on `glslify`, so Marzipano should be compatible with other module loaders now (including Webpack).
