### ISSUE TITLE
Build in Side-by-Side Functionality into Main Tool

### ISSUE THREAD

**Issue by acher249** [google/marzipano#179]
Is it on the roadmap to build in the Side-by-Side Stereoscopic functionality (demo below) into the main tool?  [http://www.marzipano.net/demos/side-by-side/index.html](url)

Could there be a toggle in the settings dialogue to either build in VR/stereoscopic mode or not? similar to the full screen toggle or auto-rotate toggle.

**Comment by tjgq** [comment]
We don't have plans to add more features to the tool.
