### ISSUE TITLE
is there a way to preload the images?

### ISSUE THREAD

**Issue by jacquelinepeh** [google/marzipano#18]
hihi, would like to ask if there is a way to preload the images before the scene shows up. 
Currently I already have the preload function to load all my images, but the moment i init my marzi, the ImageUrlSource.fromString seems to be loading the images again.

**Comment by tjgq** [comment]
If you are preloading the images, I would expect ImageUrlSource to get them from the browser cache. Can you show us your code?

**Comment by manuelcabral** [comment]
Hi. The [Layer#pinLevel()](https://github.com/google/marzipano/blob/master/src/Layer.js#L224) method preloads all the tiles in a level. Does this work for you, or do you need to control exactly which tiles inside a level get preloaded?

**Comment by jacquelinepeh** [comment]
hi @tjgq 
I'm using almost the same set of source as the sample tour. 
`var scenes = data.scenes.map(function(sceneData, index) {
    var source = Marzipano.ImageUrlSource.fromString(
      "images/"+sceneData.id+"/{f}.jpg"
    );

    // Create geometry.
    var geometry = new Marzipano.CubeGeometry([{ tileSize: 2560, size: 2560 }]);

    // Create view.
    var limiter = Marzipano.RectilinearView.limit.traditional(2560, 100*Math.PI/180);
    var view = new Marzipano.RectilinearView(sceneData.initialViewParameters, limiter);

var marzipanoScene = viewer.createScene({
      source: source,
      geometry: geometry,
      view: view,
      pinFirstLevel: true
    });

return {
      data: sceneData,
      marzipanoObject: marzipanoScene
    };
  });
`

And before this, I have a for loop to preload my images by using
`
var img = new Image();
img.onload = function() {};
img.src = src;
`

The for loop preload is working fine, able to preload the images. But when I display the initial scene, it is trying to load all the images again. 

@manuelcabral is there a way to actually know that all the images has been loaded, before I display the initial scene? I only have 1 level to pin. I'm thinking maybe I'll use a preloader screen to cover the scene, and hide the preloader after all images has been loaded.

**Comment by tjgq** [comment]
I think your preload code is missing a `crossOrigin` attribute on the image:

```
var img = new Image();
img.crossOrigin = 'anonymous';
img.src = src;
```

With this change, I don't see any duplicate requests (tested on OSX Chrome only). My guess is that the browser does not consider requests to be equivalent when the `crossorigin` attribute differs. You should probably check on other browsers.

**Comment by tjgq** [comment]
We don't have a dedicated API to wait for all pinned tiles to be loaded, but you could cook something up using the `textureLoad` event emitted by the scene's underlying `TextureStore`:

```
var tileCount = 0;
textureStore.addEventListener('textureLoad', function(tile) {
  tileCount++;
  if (tileCount === numberOfPinnedTiles) {
    // All textures have been loaded.
    scene.switchTo();
  }
});
```

There are better ways to write this (in particular, it will fail if any of the `textureLoad` events are emitted before this code gets to execute), but you get the general idea.

Note that the `pin()` API doesn't merely cause the textures to load; it will keep them in memory until a corresponding `unpin()` call. This may or may not be what you want (although it should be perfectly fine if you only pin the lowest-resolution level).

**Comment by jacquelinepeh** [comment]
hi @tjgq ,
thanks! the crossorigin did work on chrome but not on firefox thou =/
let me try out the method on TextureStore.
thanks thanks!
