### ISSUE TITLE
how i can catch event when the image is loaded  or image not found ? 

### ISSUE THREAD

**Issue by zaherkassem** [google/marzipano#181]

**Comment by tjgq** [comment]
`ImageUrlSource` emits a `networkError` event when one of the images fails to load (code [here](https://github.com/google/marzipano/blob/master/src/sources/ImageUrl.js#L90)). However, note that the error object doesn't carry enough information to distinguish e.g. an HTTP 404 from an unavailable network connection.

Also note that `ImageUrlSource` will retry downloading any failed images, so if you have a transient network failure you might see a `networkError` followed by a successful load.

**Comment by zaherkassem** [comment]
thanks @tjgq  , i catch the error  event now.
the second question is, there is any event or trigger to know if the image is loaded ?

**Comment by tjgq** [comment]
There is no image load event, although we would certainly welcome a patch to add one.

The next best thing is to listen for the `TextureStore#textureLoad` event, which fires once the image has been loaded *and* a texture has been created for it.

If you don't mind me asking, why do you need to listen for these events? There might be a better way to accomplish what you're trying to do.

**Comment by zaherkassem** [comment]
@tjgq 

i want to show loading animation image until loaded the image , may i can change the black background color that shown before loaded the image  ?

**Comment by tjgq** [comment]
Sorry for the delayed reply. That does sound like a reasonable use case for `TextureStore#textureLoad`. [This thread](https://groups.google.com/d/msg/marzipano/xszV2UIxeHY/cXwDP1KyBQAJ) might also be of interest to you.
