### ISSUE TITLE
Preview images for equirectangular scenes

### ISSUE THREAD

**Issue by mjau-mjau** [google/marzipano#185]
Hi, I am looking into Marzipano for a web gallery app. Currently, our app only supports single-file equirectangular images, since multi-file panoramas are more complicated to integrate into the automated gallery logic.

I have successfully created a multi-scene Marzipano viewer for a gallery of images. However, I noticed that Marzipano **preloads ALL images immediately** when the scenes are added. This is unproductive when you might have 20 x 4096 px x 2MB images in a gallery. Not only is this a lot of data to transfer, but it creates some "lag" as 20 massive images are loaded into browser in a single gulp. I can only imagine how it will look/work live, from not-so-fast connections.

Anyway, I looked into several examples, and it seems CubeGeometry gets away with this by using `cubeMapPreviewUrl`. Clearly very useful to load multiple **low-res images** up front, in terms of cpu, memory, bandwidth and functional progressive viewing. Wouldn't something like this be immensely practical also for multi-scene equirectangular views?

Unless the above becomes a reality, we would have two options:

1. Create scenes progressively **after** the Marzipano viewer is initiated, depending on user-navigation (we would build our own nav list/next/previous). Seems dodgy.
2. Implement our own interface/logic for navigating, eg. creating and destroying Marzipano viewer for each image in gallery.

Thanks for any feedback! ❤️Marzipano

**Comment by tjgq** [comment]
Marzipano will preload the first (smallest) resolution level of each
panorama. The solution is to either:

a) disable preloading by passing `pinFirstLevel: false` into
Viewer#createScene.

b) add an additional (smaller) resolution level to your equirectangular
geometry, which will be preoloaded in place of the full-resolution image.

Note that `cubeMapPreviewUrl` is just a shorthand to implement a preview
level from a single image file containing the six faces of a cube. The same
shorthand isn't necessary for an equirectangular geometry because the
entire panorama is already a single image file.

**Comment by mjau-mjau** [comment]
> a) disable preloading by passing `pinFirstLevel: false` into Viewer#createScene.

Ahh, that's cool. Some settings are a bit cryptic.

> b) add an additional (smaller) resolution level to your equirectangular geometry, which will be preoloaded in place of the full-resolution image.

Very interesting. I would initially add the smaller image to `Marzipano.ImageUrlSource.fromString(src)`. Any hints on how to dynamically update the source for a specific scene?

I am also trying to figure out how I can detect src image load event, so I can implement a visual loading indicator. I can only see `textureLoad', but I'm not sure how to access it.

Thanks.

**Comment by mjau-mjau** [comment]
> What do you mean by "dynamically updating the source"?

As mentioned, I am working with equirectangular single-image sources only. If I initially add a low-res image version to the scene, I would somehow need to update the source to high-res version once the scene is active. 

> If you can't make Marzipano.ImageUrlSource.fromString work with your URL format, you can pass a custom function into the ImageUrlSource constructor, e.g.

I don't have a "format", because it's a single ER image. I tried your code, but it seems like this is for multiple tiles. Only the "preview url" is loaded `tile.z === 0`, and the other condition never executes.

> To listen for textureLoad events, install an event handler with e.g.

I will look into this and the google group link, thanks.

**Comment by tjgq** [comment]
An `EquirectGeometry` can contain multiple resolution levels inside it. You don't need to update the scene after it becomes active; you just declare which levels exist and their resolution when constructing the `EquirectGeometry`, and the viewer will load the most appropriate level.

Each level must be a single tile (i.e. image file). The `tile.z === 0` check determines which level is being loaded (`z === 0` should be the low-res preview level, `z === 1` the full-res level).

**Comment by mjau-mjau** [comment]
Wow, now we talking!

I initially created a scene preloader to deal with progressive source loading, that loads neighboring scenes of the current scene (I am using previous/next UI navigation). However, with new knowledge of both `pinFirstLevel` and multiple EquirectGeometry levels, I'll probably revert to pre-create all scenes in some combination.

Please consider this **issue CLOSED** thanks 👏

> and the viewer will load the most **appropriate** level.

I do have a related question, which I will take as a "bonus" if answered: With multiple EquirectGeometry levels, will all levels always load regardless of device/screen, or will `gl.MAX_TEXTURE_SIZE` limit be taken into consideration for the specific device? For example, only some platforms support texture sizes larger than 4096 px. Also, in some cases, it might make sense to not include massive resolution levels for mobile devices with small screens, although that could be handled when adding the levels in JS of course.

**Comment by tjgq** [comment]
`gl.MAX_TEXTURE_SIZE` is a hard limit for the size of an equirectangular level, because it must be loaded into a single WebGL texture. If you need to support larger panoramas, switch to cubemaps.

The viewer picks the most appropriate resolution level for the current zoom value and screen size. It's okay if your geometry contains larger levels; they won't ever load unless the extra resolution is required.
