### ISSUE TITLE
Name Hotspot

### ISSUE THREAD

**Issue by piochon** [google/marzipano#186]
Hi, 
I am using marzipano which is a really good tool ! 
But i got one question : how can I add text under the different hotspot (i would like to add the name of the future view under each hotspot) because it isn't clear at all what the customer is going to see next

thank you !

**Comment by mjau-mjau** [comment]
Don't you see the name of the scene when you hover over the hotspot?
![hotspot hover](https://d.pr/i/FAby7W+)

If you want to extend this with more information, and/or add static info below the hotspot, you will likely need to include some custom html and CSS.

**Comment by piochon** [comment]
Thanks for your answer. 

I do see the name of the scene when i hover the hotspot, but I would like to leave the name permanently (and not only when we hover the hotspot). 

Is there an option in the index.js for example to modify this ? 

Thanks.

**Comment by mjau-mjau** [comment]
Yes. Open the file **style.css** in any text editor, locate the `.link-hotspot-tooltip` class, and REMOVE opacity and transform styles:
`
opacity: 0;
-ms-transform: translateX(-8px);
-webkit-transform: translateX(-8px);
transform: translateX(-8px);
`

Hotspot captions will be permanently shown. You may need to empty your browser cache if you don't immediately see any changes after the edit. CSS may be cached in your browser.

**Comment by piochon** [comment]
Thank you so much !!!
It works great !
