### ISSUE TITLE
Set initial view should be configured per each hotspot in that panorama

### ISSUE THREAD

**Issue by ldanicel** [google/marzipano#187]
In my case the "initial view" should be a different view depending on where I am coming from to the panorama.

Assume there are 3 rooms - A B C and all have hotspot, both A -> B -> C and C -> B -> A
When going into B it matters if you come from A or from C therefore the initial view should be correlated to the used hotspot.

**Comment by mjau-mjau** [comment]
You are creating your viewer from Marzipano tools? Open **data.js**, and you will see each scene has a **linkHotspots** configuration. For example:
`
"linkHotspots": [
        {
          "yaw": -0.6333799649634333,
          "pitch": 0.04287834953571057,
          "rotation": 11.780972450961727,
          "target": "1-angra"
        }
]
`

You would need to manually adjust the yaw, pitch and rotation per scene. I'm pretty sure you can't adjust the view on a per-hotspot basis directly from the marzipano tools.

**Comment by tjgq** [comment]
It's not possible to customize the view on a hotspot basis using the Marzipano Tool, but it can be done using the Javascript API. See [this discussion](https://groups.google.com/forum/#!topic/marzipano/Ta2qr4jcWRI), which is about doing something similar.

**Comment by ldanicel** [comment]
ok... from what I understand it is not possible - reason why I posted here in the first place.
Wouldn't it be easier if you made an extra option in the GUI that would end shipping the proper index.js depending on what the user wants ? "Keep orientation while surfing hotspots?" Yes/No

This would be very hackish of me : to update the javascript from the bundle generated by marzipano for every tour I create.

**Comment by gamebeaker** [comment]
I had the problem and created a little tool to help me: [marzipano-hotspot-view (github)](https://github.com/gamebeaker/marzipano-hotspot-view)
