### ISSUE TITLE
Error on "npm run dev"

### ISSUE THREAD

**Issue by isteven** [google/marzipano#19]
Hi all, 

As what the title says, I'm having problem compiling the viewer in Windows 7 64bit machine.

I tried to follow the workaround explained in issue #3 (running the script from git Bash / Cygwin), but I have error like:

```bash
cd "`dirname $0`/.."
dirname $0

PATH=./scripts:./node_modules/.bin:$PATH

SRC=src
BUILD=build

mkdir -p $BUILD

make-swf $BUILD/marzipano.swf
fatal: No names found, cannot describe anything.
{ [Error: Command failed: git describe --tags HEAD
fatal: No names found, cannot describe anything.
```

Would appreciate any help. Thank you.

**Comment by tjgq** [comment]
Can you give me the output of `git tag -l`?

**Comment by tjgq** [comment]
Weird. Did you clone the repository with `git clone`? It should have fetched the remote tags automatically. Can you try running `git pull --tags` and seeing if that makes a difference?

**Comment by isteven** [comment]
Aha.. Perhaps that's the problem.

Admittedly I did not <code>git clone</code> it.  Instead I downloaded the zip file and did <code>git init</code> afterwards.

I'll try again in a few hours. Thanks for your help so far.

**Comment by tjgq** [comment]
That explains it. You do need to make a proper clone of the repository, because the dev/build scripts rely on the presence of the git tags. Let us know if you run into any other issues.

**Comment by isteven** [comment]
Cool, the demos now work properly. Thanks for the help @tjgq, will now close this issue.

_* Bear with me, I might have a lot of new questions / issues :)_

**Comment by ansarikhurshid786** [comment]
Hello I have same problem but I cannot solve it till now.

**Comment by ansarikhurshid786** [comment]
$ git pull --tags
fatal: No remote repository specified.  Please, specify either a URL or a
remote name from which new revisions should be fetched.

**Comment by ansarikhurshid786** [comment]
I have same problem as below :

$ npm run dev

marzipano@0.5.1 dev D:\marzipano
scripts/dev
'scripts' is not recognized as an internal or external command,
operable program or batch file.
