### ISSUE TITLE
load event on preview / pinned levels

### ISSUE THREAD

**Issue by jordyno** [google/marzipano#190]
Is there a way to check if the preview or pinned level tiles only are loaded?
I am trying to make sure at least low resolution part of the panorama is loaded so that I can start adding layers.
Many thanks in advance!

**Comment by tjgq** [comment]
The only way is to call `TextureStore#query` for every tile in the level, and check whether `hasTexture` is true in the returned object.

If you're only interested in whether the *visible* tiles (not the entire level) have been loaded, the upcoming release will provide a `Stage#renderComplete` event that tells you that.

**Comment by jordyno** [comment]
Does the `TextureStore#query` include the preview as well? Because in the console I only see loaded tiles of the respective level (determined by zoom). But on the screen I see there is always preview displayed on the scene switch and tiles are loaded consequently.

**Comment by tjgq** [comment]
Yes, you should be able to call `TextureStore#query` on a preview level tile (level `z = 0`).

What are you logging to the console?

**Comment by jordyno** [comment]
In my scenario, I am using `Viewer#createEmptyScene` , but yes, I am passing `pinFirstLevel: true` to `Scene#createLayer` as soon as I start adding layers.

I am logging layer.visibleTiles() method output inside a `textureLoad` listener handler, which is added right after calling `Scene#createLayer`.
All I am getting are the tiles of the level 3 as they load.

**Comment by jordyno** [comment]
never mind, I should have used the tile parameter instead of visibleTiles()
