### ISSUE TITLE
Fixed position orientationchange bug

### ISSUE THREAD

**Issue by mjau-mjau** [google/marzipano#191]
I would like to notify that there is a bug on device orientationchange if the marzipano container is **fixed** position or inside an element with fixed position. **Why use fixed position?** Because it is necessary when creating a modal panorama viewer that opens when visitor clicks a link in a scrollable page.

**Example**
Try opening in iOS and rotating device after load:
https://panorama.photo.gallery/test/fixed.html
![landscape](https://d.pr/i/C5Gudq+)

**Current hack**
It seems to work fine when using `width: 100vw; height: 100vh` instead of `width: 100%; height: 100%`. I'd prefer to avoid `vw` and `vh` though, as they do not take scrollbar into consideration. In my production, I am applying this fix only for devices that support orientationchange.
https://panorama.photo.gallery/test/fixed-fixed.html

**Comment by tjgq** [comment]
Interesting. We do listen for the window `resize` event and update the stage size by reading the `clientWidth` and `clientHeight` properties of the viewer element ([code here](https://github.com/google/marzipano/blob/master/src/Viewer.js#L282)).

So either a) window `resize` is not fired when you rotate the phone, or b) our logic produces incorrect width/height values.

I don't have an iOS device to test on at the moment. Could you try and figure out which one is it?

**Comment by mjau-mjau** [comment]
iOS definitely triggers `resize` event on device orientation change. Also, the issue is corrected when executing `viewer.updateSize()` after a timeout on orientationchange, so it's not directly related to Marzipano width/height logic either.
```
window.addEventListener('orientationchange', function() {
  setTimeout(function(){
    viewer.updateSize();
  }, 500);
}, false);
```

I think it's safe to conclude that with `position: fixed`, the `resize` event somehow triggers before the elements `clientWidth` and `clientHeight` are updated. Or to be more precise, the elements relative `width:100%; height: 100%` are updated *after* the resize event triggers. Somehow, this is remedied by using `width:100vw; height: 100vh`.

Considering the above, I was wondering how this was handled in [Photoswipe](https://github.com/dimsemenov/PhotoSwipe), and it seems there is a `_orientationChangeTimeout` fix for iOS devices.
dimsemenov/PhotoSwipe#1315
https://github.com/dimsemenov/PhotoSwipe/issues/1315
https://github.com/dimsemenov/PhotoSwipe/commit/d8762097918bddf4afb45be4414ac6289a9cade8

**Comment by tjgq** [comment]
Thanks for investigating.

I did some testing today and it appears that only iOS 10.x is affected; iOS 11.x and 12.x aren't. This was on the Xcode simulator, so results may differ from an actual device. Did you manage to reproduce this on the latest iOS?

There's also a bug report on Open Radar (https://openradar.appspot.com/radar?id=5040881597939712) suggesting that the required timeout value is dependent on page layout. This puts me on the fence about baking the workaround into Marzipano.

**Comment by tjgq** [comment]
Chrome and Firefox on iOS use Safari's rendering engine. I suspect that they are still using an older version where the bug hasn't been fixed.

I'm closing this bug as this is best worked around by library clients. Thanks for looking into it.
