### ISSUE TITLE
Hotspot Movement as Camera Rotates

### ISSUE THREAD

**Issue by ryanpager** [google/marzipano#192]
So Im running into an issue with the viewer, and the relationship between the hotspot positioning and the camera angle (yaw/pitch). Our implementation is the following,

```js
// Setup the viewer
const geometry = new Marzipano.EquirectGeometry([{ width: 2048 }]); 
const limiter = Marzipano.RectilinearView.limit.traditional(1024, 120 * Math.PI / 180);   
const view = new Marzipano.RectilinearView({
     yaw: (2 * Math.PI) * (initialPositionX),
     pitch: Math.PI * (initialPositionY)
}, limiter);

// Add Hotspots
for hotspot in hotspots
    const yaw = -Math.PI + 2 * Math.PI * (hotspot.position_x + 12) / 4096
    const pitch = Math.PI / 2 - Math.PI * (2048 + 20 - hotspot.position_y) / 2048
    this.scene.hotspotContainer().createHotspot(instance.$el, { yaw, pitch });
```

Is there a way to fix hotspot positions relative to camera so they dont move -- or is there something that I am doing wrong causing this issue?

**Comment by mjau-mjau** [comment]
> or is there something that I am doing wrong causing this issue?

Assuming you are seeing some "issue", but this issue is not made clear. Perhaps you have a link so we can experience the issue? By default from Marzipano tool, hotspots are relative to camera movement.

Your code is a bit unclear also. You are using `const` for variables in a loop?

**Comment by ryanpager** [comment]
Hey @mjau-mjau, sorry about that -- I probably rushed through the code snippet on the for loop by accident (copy and paste mishap).

Anyhow, you can see exactly what I am talking about here --
[https://vrify.com/projects/150/sites/492](https://vrify.com/projects/150/sites/492)

Just rotate the camera and you will see the hotspots move quite a bit from their original location.

**Comment by ryanpager** [comment]
@mjau-mjau You are the best -- this makes complete sense. I will make the adjustments to do the same thing as the lower example. I really really appreciate it.
