### ISSUE TITLE
[Question]: How to accurately calculate max resolution?

### ISSUE THREAD

**Issue by AustinTBiggs** [google/marzipano#193]
I had a quick, (potentially stupid) question.

When using the limit.traditional method, it's required that I set a MaxResolution. How would I calculate the max resolution? My goal is to allow the user to zoom no further than 200%.

Thanks in Advance!

**Comment by mjau-mjau** [comment]
> My goal is to allow the user to zoom no further than 200%.

You mean 200% of the panoramas original resolution? That would make it look pixelated of course. Keep in mind, the zoom level available will depend on the screen of the device. For example a small 1024px screen will have much more zoom threshold than a gigantic iMac 5000px screen, where often there will be no more zoom available. If you want to allow a consistent 200% zoom regardless of device, that would mean your panorama would look very pixelated on high-res screens.

Essentially, it doesn't and shouldn't work like that.

You should consider a panorama zoom as you would consider a normal images displaying in a browser. If for example you have a 2048 px image, it would allow 200% zoom on screens that are 1024px. On screens that are 2048px or larger, the image is already max zoomed and cannot (and should not) be zoomed more.

By default, the `maxResolution` can be set up to the original width of the panorama, thus preventing it from being zoomed in more than it's original size. The zoom threshold will then depend on the screen viewing the panorama, and some large screens will often not be able to zoom at all.

**Comment by AustinTBiggs** [comment]
Thank you both! :)
