### ISSUE TITLE
[Question]: Update Limiter on Zoom In/Out

### ISSUE THREAD

**Issue by AustinTBiggs** [google/marzipano#194]
I'm trying to update the view limiter on zoom in/out. I know that I can detect this change using the `viewChange` event. I'm needing to update the pitch limiter when a user zooms in/out.

`scene.addEventListener('viewChange', function(){
	console.log( 'viewChange' );
});`

My question though is two-fold.

1. Is there a way to limit the console.log() above to only when a user zooms? Can I detect the HFOV/VFOV changes? Or is there a better way to approach this?

2. How would I update the pitch limiter of the viewer?

```
var view = new Marzipano.RectilinearView( initialView, limiter );

// Create scene.
var scene = viewer.createScene({
  source: source,
  geometry: geometry,
  view: view,
  pinFirstLevel: true
});
```

**Comment by AustinTBiggs** [comment]
I've got this partially implemented, however, I'm not sure how to restrict my conditional to only fire if a user is zooming in...

```
scene.addEventListener('viewChange', function( a, b ){
	
	//if( typeof prevView !== 'undefined' ){
	if( true ){
		var newLimiters = {};
		newLimiters.traditional = Marzipano.RectilinearView.limit.traditional( maxResolution, vfov_2, Marzipano.util.convertFov.vtoh( vfov_1, originalWidth, originalHeight ) );
		newLimiters.pitch = Marzipano.RectilinearView.limit.pitch( minPitch, maxPitch );
		
		var newLimiter = Marzipano.util.compose(
			newLimiters.traditional,
			newLimiters.pitch
		);
		
		var newView = new Marzipano.RectilinearView( initialView, newLimiter );
		
		var newScene = viewer.createScene({
			source: source,
			geometry: geometry,
			view: view,
			pinFirstLevel: true
		});
		
		console.log( 'newScene', newScene );
		
		// Create scene.
		//viewer.switchScene(	newScene );
	}
	
	if( typeof prevView !== 'undefined' ){
		console.log( 'viewChange prevView', prevView );
	}
	
	console.log( 'viewChange view', view );
	
	prevView = view; // Keep this at the end
});
```

**Comment by tjgq** [comment]
To answer your questions directly:

1. There is no way to listen for zoom changes specifically. The `viewChange` event is emitted whenever any of the parameters change (yaw, pitch, roll or zoom).

2. You can change the view limiter by calling `View#setLimiter`. This will be a lot more efficient than replacing the scene whenever the view changes.

An alternative way to accomplish your goal is to write a single custom limiter that constrains the pitch differently depending on the zoom level. (A view limiter is just a function that receives an object of view parameters and modifies it in place; check out the implementation of the existing limiters.)

**Comment by AustinTBiggs** [comment]
@tjgq - Thanks for getting back so quickly! I didn't realize there was a function I could use to update the limiter.
