### ISSUE TITLE
Feature request: Radar plugin

### ISSUE THREAD

**Issue by anandpiyush12** [google/marzipano#195]
How can we achieve similar feature in marzipano. 

**Examples:**
- https://krpano.com/tours/bkeller/index.html
- https://bimaire.app/ISI-Kitchen-Tour/

It will be a good to have feature.

**Comment by mjau-mjau** [comment]
Looks cool, but I don't think this feature will be built in to the Marzipano viewer core. It could be created in javascript by reading the Marzipano FOV (field of view) and YAW (rotation) values when they change, to create the "radar" overlaying some custom image. I don't think Marzipano will offer advanced behavior like this, but it is available for developers to create from within Marzipano.

**Comment by anandpiyush12** [comment]
Thanks @mjau-mjau  this info helps :)

**Comment by tjgq** [comment]
As explained above, it would be more appropriate to implement this feature outside of the core Marzipano library. I believe the library already provides the necessary building blocks to implement it, but if not, we can add whatever is required.
