### ISSUE TITLE
Exporting rendered panorama

### ISSUE THREAD

**Issue by jordyno** [google/marzipano#197]
Would it be technically possible to export the rendered panorama including layers with effects and hotspots back into a 2:1 eqr file? I guess it would require to force load all of the tiles at first? And then maybe use something like FileSaver.js?

**Comment by tjgq** [comment]
See [`WebGlStage#takeSnapshot`](https://github.com/google/marzipano/blob/master/src/stages/WebGl.js#L263). It will give you the composited stage (all layers with effects), though not the hotspots. I'm not sure that the latter is technically possible to do.

To wait for a stable render you can now listen for a `Stage#renderComplete` event with a `true` argument.

**Comment by jordyno** [comment]
Thank you Tiago!
So maybe the only way to achieve exporting hotspots could be drawing the `WebGlStage#takeSnapshot` onto a canvas and drawing hotspots manually? Resulting to some issues with hotspots situated near the canvas border, though still manageable.

**Comment by tjgq** [comment]
If the hotspots are just images, it doesn't sound too hard to render them directly on a canvas element prepopulated with the output of takeSnapshot.

If the hotspots have nontrivial HTML structure, that would amount to rendering a DOM element into the canvas, which is not something browsers can natively do. A quick search [1] turned up a few attempts to emulate it in Javascript, but I have no idea how well they work; either way, this is definitely out of scope for Marzipano.

[1] https://stackoverflow.com/questions/12652769/rendering-html-elements-to-canvas

**Comment by jordyno** [comment]
Thanks for your help Tiago!
