### ISSUE TITLE
Hotspot Proximity Detection and Grouping

### ISSUE THREAD

**Issue by jordyno** [google/marzipano#198]
Hi all,
what would be the most efficient way to detect hotspots that are overlapping each other and to set them apart? This should be handled even as the FOV changes and hotspots appear closer to each other on zooming out. I assume they should be grouped together when overlapped and spaced apart on click?

**Comment by tjgq** [comment]
[Hierarchical clustering](https://en.wikipedia.org/wiki/Hierarchical_clustering) would lend itself well to this problem.
