### ISSUE TITLE
`npm install` on Windows fails because of `git://` url in package.json

### ISSUE THREAD

**Issue by christhoph** [google/marzipano#199]
Hi, i execute: `npm install marzipano` but the installation is not complete.

I get this message in console: 

> `npm ERR! Error while executing:`
> `npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t git://github.com/toji/gl-matrix.git`
> `npm ERR!`
> `npm ERR! fatal: unable to look up github.com (port 9418) (The application did not call WSAStartup, or there was an error in WSAStartup. )`
> `npm ERR!`
> `npm ERR! exited with error code: 128`
> `npm ERR!`
> `npm ERR! A complete log of this run can be found in:`
> `npm ERR!     C:\...\npm-cache\_logs\2018-11-24T20_25_15_092Z-debug.log`

What can I do to use Marzinpano with npm, thanks for the help.

**Comment by tjgq** [comment]
This looks like https://github.com/git-for-windows/git/issues/1949. You may be able to fix it by updating your Git installation.

**Comment by christhoph** [comment]
Thanks for the guide, I found this solution that helped me:

https://gist.github.com/taoyuan/bfa3ff87e4b5611b5cbe
