### ISSUE TITLE
Not able to change the source image

### ISSUE THREAD

**Issue by ironplasma** [google/marzipano#2]
I want to replace the source image for the panorama but can't seem to figure out to do it...
I tried everything I think but with no success! The given URL works fine:
var source = Marzipano.ImageUrlSource.fromString("https://storage.googleapis.com/marzipano-demos-media/equirect/angra.jpg"); 
but it's the only thing. If I copy the image locally, it doesn't work.
Can anybody help??

**Comment by tjgq** [comment]
Is the image served from the same domain as the HTML document? If not, then the domain serving the image has to explicitly allow cross-domain loading, as per the CORS policy: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by ironplasma** [comment]
It works! Sorry that was probably a rookie mistake not to try with other browsers.. It just doesn't work with chrome (which apparently has some issues regarding local files fetching).
Thanks for the answer anyway!

**Comment by arunkrish43** [comment]
Hey bro..U cant change the image..bt useing this tool link(http://www.marzipano.net/tool/index.html)
u can use ur image...it ll automatically converted with ur image..thank you
