### ISSUE TITLE
Hotspot position detection

### ISSUE THREAD

**Issue by isteven** [google/marzipano#20]
Hi,

Is there a way to detect if a hotspot is now visible, or at a certain position on the screen?

Example:

1) Let's say the crosshair is the center of the screen. From this position, say I drag the scene to the left..
![step1](https://cloud.githubusercontent.com/assets/5432100/15852491/bea3bb04-2cd3-11e6-9509-8b5c374ec1aa.jpg)

2) ...until the hotspot is now under the crosshair
![step2](https://cloud.githubusercontent.com/assets/5432100/15852494/c1bd95b2-2cd3-11e6-94d1-0e1ffcfe1c37.jpg)

**Comment by tjgq** [comment]
You could pass the hotspot yaw/pitch coordinates into the `View#coordinatesToScreen` method, which returns the corresponding (x,y) position on the viewport.

**Comment by isteven** [comment]
Thanks. Can you point me the doc url regarding this functionality? (I tried browsing the docs and reference http://www.marzipano.net/reference/ but couldn't find it)

Also, which event should I use to trigger this? Is there something similar like.. 

```javascript
theHotspotDOM.onDrag( function( e ) {
    console.log( e.deltaX, e.deltaY, e.newX, e.newY );
});

**Comment by tjgq** [comment]
The documentation for the method is at http://www.marzipano.net/reference/RectilinearView.html#coordinatesToScreen.

You can listen to the `change` event on the View, or equivalently, the `viewChange` event on the Scene, to do something when the view is dragged around.

**Comment by isteven** [comment]
Thanks @tjgq; 

I still have a bunch of question as I'm currently working on a small game utilizing marzipano. Do you think it's better if I open a new issue or keep it here?

**Comment by tjgq** [comment]
Ideally, the issue tracker should only be used to discuss bugs and new features. But you can post your questions to our forum (https://groups.google.com/forum/#!forum/marzipano) and we'll be happy to help.

**Comment by isteven** [comment]
Thank you! Never thought there's a forum about marzipano. Will check it out.
