### ISSUE TITLE
IE11 dragger does not end on mouseleave

### ISSUE THREAD

**Issue by kremin** [google/marzipano#201]
if the user drags outside the viewelement and stops dragging the view keep on moving and stops only if the user klick into the view. 

can i emit an event or call a function so that the scene/view ends the drag

i tried to call lookat on mouseleave but the drag process is still working after the lookat movement

stopMovement doesn't help either

**Comment by tjgq** [comment]
I'm having trouble reproducing this. Can you describe what you're doing in more detail?

Are you dragging the mouse cursor outside of the entire browser window? Or are you dragging it outside of the viewer element, but staying inside the web page?

Is it possible to reproduce it in one of the demos, e.g., [this one](http://www.marzipano.net/demos/cube-single-res/index.html)? If not, can you share a complete example including the Javascript code?

Can it be reproduced on other browsers?

**Comment by kremin** [comment]
It is only in IE11. 

You can use your example, make a small window and leave the window while dragging and do a 'mouseup' outside. Move your mouse back to the window and you will see, that you are still dragging the view. You need to click to get back the mousecontrol. 

It is the same if you have some interface elements in front of the pano. In my webapp i have some thumbnails and a legend element in front of the pano and the pano is not fullscreen so it is easy to leave it while dragging. In Chrome/FF it works perfektly but my client and the most of his clients use ie11 therefore i am looking for possibility to fix this issue. 

thanks in advance.

**Comment by tjgq** [comment]
I was able to reproduce it with an iframe (mouse down inside iframe, move the mouse cursor, mouse up outside iframe).

It looks like IE 11 does not emit a `mouseup` event when the mouse button is released outside the iframe (see this [jsfiddle](https://jsfiddle.net/1byxjpzh/)). Thus, when the cursor returns to the control element, the button is still in the pressed state until the next `mouseup`.

This is a [known bug](https://github.com/hammerjs/hammer.js/issues/721) in hammer.js (which Marzipano uses to implement the controls). I don't see a workaround, short of attempting to fix the problem in hammer.js itself.

**Comment by kremin** [comment]
Is it possible to trigger the action on mouseleave manuelly? Or can i emit an event on the Marzipano Object in order to do the same as an mouseleave would do?

**Comment by tjgq** [comment]
You can call `DragControlMethod#_handleEnd` to trigger the "end drag" the Marzipano size, but hammer.js will remain confused about the mouse button state, and you'll get an unexpected result the next time you try to drag.

One thing that works is to modify hammer.js to handle `pointerleave` the same as `pointerup`. It's a two line change on the `hammer.js` file to add `pointerleave` into the `POINTER_WINDOW_EVENTS` and `POINTER_INPUT_MAP` variables.
