### ISSUE TITLE
Fixed anchor link prevent default after export using tools

### ISSUE THREAD

**Issue by mosleh200989** [google/marzipano#202]
after export when we add this tour in iframe there shows scroll problem when click any controls. every control are html a (anchor) tag with # href. when visitor click any control the page scroll to top. please add prevent default in js file.

**Comment by tjgq** [comment]
I tried embedding the `sample-tour` demo (which is similar to a generated tour) inside an iframe:

```
<div style="height: 100%"></div>
<iframe src="http://www.marzipano.net/demos/sample-tour" width="100%" height="50%"></iframe>
<div style="height: 100%"></div>
```

However, I don't see the parent window scroll when I click the buttons (tested on Chrome, Firefox and Safari on MacOS).

Which browser are you seeing this on? Can you share the HTML/CSS you're using to embed the iframe?

**Comment by tjgq** [comment]
Please reopen if you have more information.

**Comment by tjgq** [comment]
This was also reported in https://groups.google.com/forum/#!topic/marzipano/Z-tXEklC3gc. I think it's safe to implement the workaround mentioned there, namely replacing `href="#"` with `href="javascript:void(0)"` in `<a>` elements.

**Comment by tjgq** [comment]
This has now been fixed both in the `sample-tour` demo and tours created by the Marzipano Tool.
