### ISSUE TITLE
ReferenceError: Can't find variable: YP

### ISSUE THREAD

**Issue by NtZyr** [google/marzipano#203]
When I try to use Marzipano in my project this return this error, but it works correctly when I run examples. In project I use builded Marzipano (I disabled other scripts, styles, DOM-elements on page, but it still doesn't work).

**Comment by tjgq** [comment]
This looks like a minification issue.

Are you able to provide a complete example with instructions on how to make it throw the error?

**Comment by tjgq** [comment]
I've checked that there isn't a variable named `YP` in the latest published build, so this is almost certainly a bug in the minifier you are using.
