### ISSUE TITLE
Is it possible to make transition effect like google street view?

### ISSUE THREAD

**Issue by dreamhero418** [google/marzipano#204]
I was gonna add transition effect like google street view, but seem to be not transition function.
that is; fade zoom in and replacing scenes...
Hope any help , if possible , how to use google street view api transition effect?

**Comment by tjgq** [comment]
For simple fade in/out transition effects, see [this demo](http://www.marzipano.net/demos/transitions/index.html) ([source code](https://github.com/google/marzipano/tree/master/demos/transitions)). The zoom effect can be implemented by calling `RectilinearView#setFov` in a loop during the transition.

However, note that tours generated by the Marzipano Tool (or, in general, tours using the `Viewer#switchScene` API to switch between scenes) already implement fade in/fade out transitions.

**Comment by ReubenMru** [comment]
Hello tjgq, 

I was just looking into the demo that you sent - this one doesn't seem to work:
![image](https://user-images.githubusercontent.com/48220856/54082789-4c5c7980-4334-11e9-8c92-19ef49ce45d0.png)

Clicking the Go button resets it... is there any way to fix it?

Thanks for all that you're doing :-)

**Comment by tjgq** [comment]
Thanks - there was a bug in the demo, but it has been fixed in the master branch. It will be uploaded to our website with the next release.
