### ISSUE TITLE
installing Marzipano

### ISSUE THREAD

**Issue by fedestampini** [google/marzipano#205]
HI, I'm not a programmer but a 3Ddesigner, i found Marzipano really nice but i have a problem installing the exported file.

I'm strugling to understand how to install it in the browser,
I've downloaded the latest version, but what am i supposed to do to Include the marzipano.js file in body section of your HTML code? there is any video explaining this?

I've created my 360 panorama scena and exported but there is no .exe file. only licese, app-files-read me, i guess that is realated not having installed it correctly before.

I would apreciate if someone could explain me how to solve this issue. thanks

**Comment by tjgq** [comment]
There is no executable. The tool produces a full web application (the contents of the `app-files` folder) which must be uploaded into a web hosting service.
