### ISSUE TITLE
Screenfull not working with Chrome 71

### ISSUE THREAD

**Issue by jordyno** [google/marzipano#207]
This has been fixed with the latest or previous version of screenfull.js, please update for the demos to work correctly. Thank you.

Details:
"Chrome v71 has new fullscreen API that requires a parameter in the code."

**Comment by tjgq** [comment]
Thanks. I've updated both the screenfull.js on the Marzipano website (used by the demos) and the one shipped with generated tours to the latest version (4.0.0). It might take a couple of hours for the caches to expire.
