### ISSUE TITLE
Broken builds with Webpack

### ISSUE THREAD

**Issue by nikolakanacki** [google/marzipano#21]
It appears that the problem originates within `glslify` package and its `/browser.js` file, throwing an error:
```
Error: It appears that you're using glslify in browserify without its transform applied.
Make sure that you've set up glslify as a source transform:
https://github.com/substack/node-browserify#browserifytransform
```
Tried using both `ify-loader` (automatically applying browserify transforms on each and every required package from the modules tree, reading `browserify.transform` from its `package.json`) and `glslify-loader` (transform the files when required - only they are not required but loaded with `glslify('file-name')`) - all without any luck.

Any ideas on how to fix this, or what exactly is causing the problem? Webpack is the other major browser javascript compiler, we should be able to make it work with such an awesome lib.

**Comment by nikolakanacki** [comment]
Ok, quick and dirty solution was to:
1) Remove all instances of `require` calls to `glslify`,
2) Replace calls to it with normal `require` calls (add `.glsl` extension to a path argument where needed),
3) Add `glslify-loader` loader package inside of `webpack.config.js` file in conjunction with `raw-loader` like so:
```
{ test: /\.(glsl|frag|vert)$/, loader: 'raw' },
{ test: /\.(glsl|frag|vert)$/, loader: 'glslify-loader' }
```
or prefix every path argument in those (to be replaced with `require`) `glslify` calls with `raw!glslify-loader!`...

This is wrong on so many levels, but the build does work.
I am looking for a better solution tho, so if anyone can add his two cents on this one, would be highly appreciated.

**Comment by nikolakanacki** [comment]
Finally found a problem:

Using the `ify-loader` for `webpack` you can assure that each and every required module will have its `package.json` specified browserify transforms applied before being flushed back to your code.

However, it seams that you haven't specified `glslify` transform in your `package.json` > `browserify.transforms` array, and are instead calling it in your build script directly via the command line argument (`scripts/build:33`). This prevents the library from being imported into other projects without having the host codebase execute `glslify` transform, which breaks the atomicity principle.

I'll send a pull request in a bit.

**Comment by tjgq** [comment]
Thanks for fixing this.
