### ISSUE TITLE
How to combine with reactjs? HELP!

### ISSUE THREAD

**Issue by ManhCuong303** [google/marzipano#210]
After using the Marzipano Tool, I received a folder  App-files, how did it work on new project reactjs (npx create-react-app my-app) ?.
I really need this, please help me if possible.

p / s: I am using reactjs on nodejs

**Comment by tjgq** [comment]
This is a question about reactjs, not Marzipano. I don't have experience with reactjs, but if you explain what kind of modifications you want to make to the generated tour, we might be able to point you in the right direction.

**Comment by ManhCuong303** [comment]
> Đây là một câu hỏi về Reacjs, không phải Marzipano. Tôi không có kinh nghiệm với Reacjs, nhưng nếu bạn giải thích loại sửa đổi nào bạn muốn thực hiện cho chuyến tham quan đã tạo, chúng tôi có thể chỉ cho bạn đi đúng hướng.

Thank you, so how do I have all the hot spot effects here? 
http://www.marzipano.net/demos/hotspot-styles/index.html
How do I do when using the Marzipano Tool that I want to embed videos and photos to show when the user clicks on the hotspot?

**Comment by ManhCuong303** [comment]
> This is a question about reactjs, not Marzipano. I don't have experience with reactjs, but if you explain what kind of modifications you want to make to the generated tour, we might be able to point you in the right direction.

Thank you, so how do I have all the hot spot effects here? 
http://www.marzipano.net/demos/hotspot-styles/index.html
How do I do when using the Marzipano Tool that I want to embed videos and photos to show when the user clicks on the hotspot?
And can I re-upload the zip file after exporting to the Marzipano Tool to correct what I did wrong?

**Comment by tjgq** [comment]
It's not possible to add hotspot effects, or to embed images and videos in hotspots, directly on the Marzipano Tool. You will have to edit the generated source code.

To add an image or video to the dialog that appears when clicking a hotspot, you can edit the `text` property of an `infoHotspot` in the generated `data.js` file. This property can contain arbitrary HTML, not just text, so it can contain an `<img>` or `<video>` tag.

Adding the hotspot effects requires enough familiarity with CSS to copy the appropriate definitions from the `hotspot-styles` demo into the generated `style.css` file.

**Comment by ManhCuong303** [comment]
> Không thể thêm hiệu ứng điểm nóng hoặc nhúng hình ảnh và video vào các điểm nóng, trực tiếp trên Công cụ Marzipano. Bạn sẽ phải chỉnh sửa mã nguồn được tạo.
> 
> Để thêm hình ảnh hoặc video vào hộp thoại xuất hiện khi nhấp vào điểm nóng, bạn có thể chỉnh sửa thuộc `text`tính của tệp trong tệp `infoHotspot`được tạo `data.js`. Thuộc tính này có thể chứa HTML tùy ý, không chỉ văn bản, vì vậy nó có thể chứa một thẻ `<img>`hoặc `<video>`thẻ.
> 
> Việc thêm các hiệu ứng hotspot đòi hỏi đủ sự quen thuộc với CSS để sao chép các định nghĩa phù hợp từ `hotspot-styles`bản demo vào `style.css`tệp được tạo .
> 
> Cuối cùng, thật không may là không thể tải lại tệp zip vào công cụ để chỉnh sửa thêm. Xin lỗi vì điều đó.

**Comment by ManhCuong303** [comment]
> It's not possible to add hotspot effects, or to embed images and videos in hotspots, directly on the Marzipano Tool. You will have to edit the generated source code.
> 
> To add an image or video to the dialog that appears when clicking a hotspot, you can edit the `text` property of an `infoHotspot` in the generated `data.js` file. This property can contain arbitrary HTML, not just text, so it can contain an `<img>` or `<video>` tag.
> 
> Adding the hotspot effects requires enough familiarity with CSS to copy the appropriate definitions from the `hotspot-styles` demo into the generated `style.css` file.
> 
> Finally, it's unfortunately not possible to re-upload a zip file back into the tool for further editing. Sorry about that.

I am using the Marzipano Tool on your website, can I still fix it?

**Comment by ManhCuong303** [comment]
> It's not possible to add hotspot effects, or to embed images and videos in hotspots, directly on the Marzipano Tool. You will have to edit the generated source code.
> 
> To add an image or video to the dialog that appears when clicking a hotspot, you can edit the `text` property of an `infoHotspot` in the generated `data.js` file. This property can contain arbitrary HTML, not just text, so it can contain an `<img>` or `<video>` tag.
> 
> Adding the hotspot effects requires enough familiarity with CSS to copy the appropriate definitions from the `hotspot-styles` demo into the generated `style.css` file.
> 
> Finally, it's unfortunately not possible to re-upload a zip file back into the tool for further editing. Sorry about that.

Thank you for your help, Can you have the Marzipano Tool improvements like I mentioned in the future? I think it's quite necessary :)

**Comment by tjgq** [comment]
As explained in other threads, we don't have any plans to add more features to the Marzipano Tool. Sorry.
