### ISSUE TITLE
Minor typo mistakes on www.marzipano.net

### ISSUE THREAD

**Issue by ayshiff** [google/marzipano#211]
It looks like there are some typo mistakes in the [`Create Scene`](http://www.marzipano.net/docs.html#create-scene) part of the **Getting Started** Section.

<img src="https://user-images.githubusercontent.com/32459935/51382983-7c4b8580-1b18-11e9-804e-8dfe7a0672f5.jpg" width="300" />

<img src="https://user-images.githubusercontent.com/32459935/51383166-f67c0a00-1b18-11e9-9ae8-18d0451e8cfb.jpg" width="450" />

**Comment by tjgq** [comment]
Sorry, I don't see the typos (just inconsistent syntax highlighting). Can you clarify?

**Comment by tjgq** [comment]
Fixed.
