### ISSUE TITLE
positionAbsolutely overrides other hotspot transforms

### ISSUE THREAD

**Issue by jordyno** [google/marzipano#213]
Hi all,
not sure if an issue or an intended feature by design, but on each `view` change the `positionAbsolutely ` drops any CSS transform properties set on hotspots and updates only `translateX`, `translateY` and `translateZ`. 
In my implementation, I would like to set scale transform property on the entire `hotspot` element. This might be useful in other applications as well, where hotspots should be scaled as the FOV changes. 
1. If scale transform property support was implemented, would it increase CPU usage significantly?
2. I understand that in case of no CSS transforms support, scale transform would be dropped. That makes me suggest if Marzipano should not drop IE < 11 support, which accounts to less than 1% usage nowadays. Basically every browser from 2011 on supports CSS transforms. We could still keep the IE8 supported version of Marzipano in a separate branch, maybe?

**Comment by tjgq** [comment]
Pass the `extraRotations` option to `HotspotContainer#createHotspot` (which is incorrectly named; it should be called `extraTransforms`) to perform additional CSS transforms after the translation. This is how the [embedded hotspot demo](https://github.com/google/marzipano/blob/master/demos/embedded-hotspots/index.js#L55) works. My experience is that you can rely on CSS transforms to be pretty efficient.

Support for old browsers (with "old" defined as anything that does not support WebGL) will go away sooner or later. However, regardless of when we make that decision, I'm not generally opposed to adding features that only work on modern browsers, as long as there's a way for clients to "opt out".

**Comment by jordyno** [comment]
Thank you, Tiago! I tried it and if I do not specify the `radius` in perspective parameters (which is my case, as I do not need it), the `extraRotations` aka `extraTransforms` do not get applied. This line seems to be causing it:  [hotspot.js](https://github.com/google/marzipano/blob/0b4e32c7d3565aa4d60f126374b52bcbe09768ac/src/Hotspot.js#L188)

**Comment by tjgq** [comment]
Sorry, I misremembered it.

Can you send a PR to plumb `this._perspective.extraRotations` through into `positionAbsolutely` and append the transforms (when supported)?

**Comment by jordyno** [comment]
Sure, shall I also fix the naming of `extraRotations` to `extraTransforms`?
