### ISSUE TITLE
Hotspots inside a video 

### ISSUE THREAD

**Issue by aljabr** [google/marzipano#217]
Hi,
Is it possible to do this
I want to make a looping video 
And adding some hotspots 
🙏🏻

**Comment by tjgq** [comment]
Yes, a looping video should work by setting the `loop` attribute in the `<video>` element.

Hotspots work in the same way as for regular scenes. However, when you add a hotspot, you place it in a fixed position in the 360 sphere. If you want it to follow around an object visible in the video, you'll have to write some Javascript to adjust the hotspot position over time.
