### ISSUE TITLE
How to get coordinates of mouse position on real picture

### ISSUE THREAD

**Issue by pakorn33** [google/marzipano#220]
Hi,
I can use `console.log('clientX = ',e.clientX,',clientY = ',e.clientY);`
but it is a screen pixel-coordinates.

I would like to get coordinates of mouse position on real picture that i click on panorama picture.

Thank you.

**Comment by jordyno** [comment]
Hi,
I think `coordinatesToScreen` and `screenToCoordinates` is what your are [looking for](http://www.marzipano.net/reference/RectilinearView.html) .

**Comment by pakorn33** [comment]
> Hi,
> I think `coordinatesToScreen` and `screenToCoordinates` is what your are [looking for](http://www.marzipano.net/reference/RectilinearView.html) .

No, This is not correct.
I want to do in this link below but I don't know how to do that with marzipano. 
[https://krpano.com/forum/wbb/index.php?page=Thread&threadID=9276](url)

Thank you so much for the speedy reply.

**Comment by tjgq** [comment]
`screenToCoordinates` is the Marzipano equivalent of krpano's `screentosphere`. However, the coordinates are in radians (not degrees). So the formulas you need are:

```
sourceX = (0.5 + 0.5 * yaw / Math.PI) * sourceWidth
sourceY = (0.5 + pitch / Math.PI) * sourceHeight
```

where `yaw` and `pitch` are the coordinates returned by `screenToCoordinates`.

**Comment by pakorn33** [comment]
> `screenToCoordinates` is the Marzipano equivalent of krpano's `screentosphere`. However, the coordinates are in radians (not degrees). So the formulas you need are:
> 
> ```
> sourceX = (0.5 + 0.5 * yaw / Math.PI) * sourceWidth
> sourceY = (0.5 + pitch / Math.PI) * sourceHeight
> ```
> where `yaw` and `pitch` are the coordinates returned by `screenToCoordinates`.

Yes, This is correct.
Thank you very much for your help.
