### ISSUE TITLE
viewChangeComplete event

### ISSUE THREAD

**Issue by jordyno** [google/marzipano#224]
Hi all,
is there an event I can listen to that fires each time the view stops rotating? That is, whenever the view is being changed by either user or `scene#lookTo` and the animation is complete and the view stands still. If not, any ideas in which class is it most efficient to implement it?
Thank you!

**Comment by tjgq** [comment]
There isn't an event you can listen for directly, but you can wait until enough time has passed since the last `viewChange` event. The `Viewer` class already does something like that to implement autorotation. Search for uses of `this._idleTimer` in `Viewer.js`.

**Comment by jordyno** [comment]
@tjgq : Wouldn't it make sense to add viewChangeComplete? Would be very helpful to have this so that we can, for example, update url hash with yaw/pitch/fov information every time the view stands still, so we can share a specific view of the panorama with other users.

**Comment by jordyno** [comment]
@tjgq : To take advantage of your proposed solution, I would need to have the Timer exported in public API. I could then set it to a few miliseconds and have my own idle handler. Otherwise the `idleTimer` interferes with autorotate timer.
