### ISSUE TITLE
How to destroy all Hotspot

### ISSUE THREAD

**Issue by pakorn33** [google/marzipano#225]
Hi, 
I have many Hotspot from scene.hotspotContainer().createHotspot(element, { yaw: hotspot_add.yaw, pitch: hotspot_add.pitch });
and I want to remove all of them. How to call function destroyHotspot or destory all hotspot on the scene.

thank you

**Comment by tjgq** [comment]
Call `scene.hotspotContainer().destroyHotspot(h)`, where `h` is the `Hotspot` object returned by `createHotspot`.

If you want to avoid storing the `Hotspot` objects yourself, you can also call `scene.hotspotContainer().listHotspots()` to get an array with all of them.

**Comment by pakorn33** [comment]
> Call `scene.hotspotContainer().destroyHotspot(h)`, where `h` is the `Hotspot` object returned by `createHotspot`.
> 
> If you want to avoid storing the `Hotspot` objects yourself, you can also call `scene.hotspotContainer().listHotspots()` to get an array with all of them.

Thank you so much.

**Comment by pakorn33** [comment]
> Call `scene.hotspotContainer().destroyHotspot(h)`, where `h` is the `Hotspot` object returned by `createHotspot`.
> 
> If you want to avoid storing the `Hotspot` objects yourself, you can also call `scene.hotspotContainer().listHotspots()` to get an array with all of them.

![image](https://user-images.githubusercontent.com/47946379/54342201-708ac400-466e-11e9-969a-72ff77a46f55.png)

I found this error when trying to delete hotspot.

**Comment by tjgq** [comment]
Sorry, I can't reproduce it. Can you identify the exact line in the source code where the crash is happening?

**Comment by apiwat33** [comment]
> 
> 
> Sorry, I can't reproduce it. Can you identify the exact line in the source code where the crash is happening?

Now the program can work normally. Using the code below instead.

removeElementsByClass("hotspot info-hotspot");

function removeElementsByClass(className){
    var elements = document.getElementsByClassName(className);
    while(elements.length > 0){
        elements[0].parentNode.removeChild(elements[0]);
    }
}

Thank you for help.

**Comment by pakorn33** [comment]
> 
> 
> Sorry, I can't reproduce it. Can you identify the exact line in the source code where the crash is happening?

At first I wanted to loop through to delete all hotspots. 
Now the program can work normally. Using the code below instead.

removeElementsByClass("hotspot info-hotspot");

function removeElementsByClass(className){
var elements = document.getElementsByClassName(className);
while(elements.length > 0){
elements[0].parentNode.removeChild(elements[0]);
}
}

Thank you for help.

**Comment by tomyitav** [comment]
Hi, I called ```scene.hotspotContainer().destroyHotspot(h)``` and looking at the console output for ```scene.hotspotContainer()``` I see that the hotspot was removed. But it still appears on the screen. Is there anything else required for removing it?
