### ISSUE TITLE
View based on previous scene

### ISSUE THREAD

**Issue by marauder2k7** [google/marzipano#229]
This would be an enhancement more than anything else. Instead of having one default view position for each scene, have a default view linked to the previous scene, for example in one 360 degree tour i have created the viewer starts at the main entrance, then into a hallway and then into a conference room. When the person moves from the main entrance into the hallway the hallways default view is towards the conference room. When they come back from the conference room into the hallway the default view is still towards the conference room, it would be great to be able to say okay the viewer is coming from the conference room to the hallway and so the hallway default view should now be towards the main entrance.

**Comment by campmdabt** [comment]
Hey marauder, this is already possible by setting the view parameters when changing your scene. Each hotspot I create has a 'lookat' key, and I check if I've set it to 'current' telling the view to stay looking the same direction.

````
let viewParams;
if (lookat === 'current') {
	viewParams = viewer.view().parameters();
} else {
	viewParams = {pitch: 0, yaw: 0, fov: rad(90)};
}

mSceneObj.view().setParameters(viewParams);
mSceneObj.switchTo();
````

**Comment by marauder2k7** [comment]
i dont see that in my version, i created my tour using the online tool, is that supposed to be in data.js?

**Comment by campmdabt** [comment]
No, you have to implement the above code in your implementation of the viewer.

**Comment by marauder2k7** [comment]
so in index.js after the viewer is initialized like this : 

// Initialize viewer.
  var viewer = new Marzipano.Viewer(panoElement, viewerOpts);
  
	let viewParams;
	if (lookat === 'current') {
	viewParams = viewer.view().parameters();
	} else {
	viewParams = {pitch: 0, yaw: 0, fov: rad(90)};
	}

mSceneObj.view().setParameters(viewParams);
mSceneObj.switchTo();

**Comment by campmdabt** [comment]
Sorry, it'll take a little more than that to get everything setup the way I have it.

It sounds like you're not too familiar with javascript and are looking for a more off the shelf solution. You won't be able to customize very much without knowing the marzipano architecture or JS, but fortunately this is easy to use.

Change index.js line 187 from 

`scene.view.setParameters(scene.data.initialViewParameters);`

to

`scene.view.setParameters(viewer.view() && viewer.view().parameters() || scene.data.initialViewParameters);`

This uses the current view parameters (if they exist) and the default ones if they don't.

**Comment by marauder2k7** [comment]
i do know javascript just when u said the implementation of the viewer i thought u meant when it was initialized, no problem thanks for the help ill make those changes and get it sorted :)

**Comment by mpvlc** [comment]
Hi campmdabt,

my skills in JS are very low , but I am on way of learning.
I would like to solve this issue with scene heading.
I've already changed line 187 in index.js as you mentioned above.
I also tried to copy this:
```
// Initialize viewer.
  var viewer = new Marzipano.Viewer(panoElement, viewerOpts);
  
	let viewParams;
	if (lookat === 'current') {
	viewParams = viewer.view().parameters();
	} else {
	viewParams = {pitch: 0, yaw: 0, fov: rad(90)};
	}

mSceneObj.view().setParameters(viewParams);
mSceneObj.switchTo();
```

but it doesn't work for me. Did I miss something?
As I said, I'm a beginner and I would like to ask to for help (little bit more detailed explanation where should I write the code).


There is also one more thing that I would like to achieve. If you look closer how Google SV's scene change works, you will notice that the yaw and pitch parameters depends not on the hotspot but on the actual view parameters. For example if you're looking almost straight down, and you move forward to the next scene, you will land also looking down as in previous scene.

Is your code modification working like this ?

Thank you very much for any advice in advance.


> Sorry, it'll take a little more than that to get everything setup the way I have it.
> 
> It sounds like you're not too familiar with javascript and are looking for a more off the shelf solution. You won't be able to customize very much without knowing the marzipano architecture or JS, but fortunately this is easy to use.
> 
> Change index.js line 187 from
> 
> `scene.view.setParameters(scene.data.initialViewParameters);`
> 
> to
> 
> `scene.view.setParameters(viewer.view() && viewer.view().parameters() || scene.data.initialViewParameters);`
> 
> This uses the current view parameters (if they exist) and the default ones if they don't.

**Comment by campmdabt** [comment]
Try to log out the parameters to make sure you're getting good values, something like `console.log(viewer.view().parameters())` should give you `
{yaw: -1.2356951808288663, pitch: 0.3191500167387211, roll: 0, fov: 1.3089969389957472}`.

Once you know you're getting the right value, pass it to `scene.view.setParameters()` and it should work. This doesn't do any error checking or give a default value, but it will keep the same view between scenes as you mention. Sorry I can't be of more help right now, work deadlines.

**Comment by mpvlc** [comment]
Hi , thanks for your advice. I am still trying , but it is not working. Probably I haven't set the "lookat" key correct, as you mentioned above.
So could you please explain how to set it right ?
Or maybe do you have any sample files that I could download and look at the whole working code ? 
Thank you very much

**Comment by Cragsand** [comment]
This would be great to see implemented into the tool for easier use!
