### ISSUE TITLE
lookTo animation abort

### ISSUE THREAD

**Issue by jordyno** [google/marzipano#234]
Is it possible abort an ongoing `scene#lookTo` animation when user tries to control the view with the mouse?

**Comment by tjgq** [comment]
No. It's a long-standing [TODO](https://github.com/google/marzipano/blob/master/src/Scene.js#L268).

**Comment by jordyno** [comment]
How to do it? I guess we would need to listen for controls input inside the movement function? Isn't this related to the difficulty you mentioned in your comment [here ](https://github.com/google/marzipano/issues/206) ?

**Comment by tjgq** [comment]
There's existing logic in Viewer to cause control inputs to interrupt the "idle movement" (autorotate):

https://github.com/google/marzipano/blob/master/src/Viewer.js#L225
https://github.com/google/marzipano/blob/master/src/Viewer.js#L666

I'm thinking that maybe we should let the controls interrupt any ongoing movement, not just the idle one. `Scene#lookTo` could then receive an option indicating whether the controls should be disabled during the transition. If they're not disabled, the logic in Viewer would take care of interrupting it.

Would you like to take a crack at implementing this?

**Comment by jordyno** [comment]
Makes sense!
Sure, I can try! Will test it on my application first and then create a PR.

**Comment by tjgq** [comment]
Fixed in d3051cd.
