### ISSUE TITLE
Device Orientation control method bug in webkit browsers

### ISSUE THREAD

**Issue by jordyno** [google/marzipano#235]
After turning on device orientation in [DEMO](http://www.marzipano.net/demos/device-orientation/index.html) and switching to another tab in the browser and then returning back to the original tab, the view ends up pointing directly down. 
This is observed with latest Opera and Chrome browsers, not with IE11 nor latest Firefox. 
Probably related only to Windows PCs without gyro sensors.
UPDATE: The same problem happens if I just turn on and off the device orientation and then re-visit the tab.

**Comment by campmdabt** [comment]
Does that demo work correctly for others anymore? I'm investigating another bug and attempted to test the device orientation demo, but none of the phones or browsers I tried worked. I know a recent iOS Safari update [recently disabled](https://www.macrumors.com/2019/02/04/ios-12-2-safari-motion-orientation-access-toggle/) device orientation access by default, but other browsers should still work.

Here's an [example ](http://tours.atlasbayvr.com/tp/solisbrightleaf/test.html)of a KRPano tour orientation working (must be on mobile for gyro button to show up). For Safari in iOS 12.2 access to the gyro must be enabled. I can't get this functionality to work with the demo or with our own implementation.

Any help would be greatly appreciated. Thanks!

**Comment by tjgq** [comment]
@campmdabt: the demo at http://www.marzipano.net no longer works on Chrome because device orientation events are unavailable over plain http. It will work if you serve it over https. (We'll move the website to https soon.)

@jordyno: does the device you're testing on have an orientation sensor or not? If it doesn't, is the browser somehow emitting bogus `deviceorientation` events? Without events, the demo won't do anything when device orientation is turned on.

**Comment by tjgq** [comment]
I'm going to consider this resolved as the Marzipano website is now served over https. Please reopen (with reproduction instructions including browser and device) if the demo still doesn't work for you.

**Comment by campmdabt** [comment]
Can confirm device orientation demo works on Android Chrome and iOS Chrome out of the box. Demo also works on iOS Safari after enabling [Motion and Orientation Access](https://www.macrumors.com/2019/02/04/ios-12-2-safari-motion-orientation-access-toggle/) in the settings menu on the mobile device. Thanks for the update.

**Comment by jordyno** [comment]
@tjgq the demo still works incorrectly on devices without gyro sensor as I described above. Probably the browser sends bogus events on tab switch. Any idea how to deal with this?
