### ISSUE TITLE
Not working in latest chrome browser

### ISSUE THREAD

**Issue by denseacat** [google/marzipano#237]
panorama image itself not displaying, black screen and dom objects only shown.
Was trying to open panorama from hard drive, localy.
![изображение](https://user-images.githubusercontent.com/3787889/56118778-800e6d00-5f8c-11e9-82e3-9c31f9baf02d.png)

**Comment by jordyno** [comment]
have you tried opening developer tools for some clues?

**Comment by tjgq** [comment]
Are you opening a file:// URL directly on the browser? WebGL doesn't work with file:// URLs - you need to serve the tour files with a webserver.

**Comment by tjgq** [comment]
Please reopen with instructions to reproduce, if it's not the file:// issue mentioned above.

**Comment by dzolotor** [comment]
@tjgq  Hi Tiago, I'm experiencing this issue as well, but with multi-res video, and I am serving the file. This is happening on both MacOS and Windows in ALL browsers. This can be reproduced by using Chrome on the demo video-multi-res [https://www.marzipano.net/demos/video-multi-res/](https://www.marzipano.net/demos/video-multi-res/)

If it the screen isn't immediately black, refreshing should quickly reproduce the problem.

<img width="1792" alt="Screen Shot 2020-02-18 at 12 30 17 AM" src="https://user-images.githubusercontent.com/18335310/74709925-f51e8480-51e5-11ea-95f2-21806b234398.png">

<img width="758" alt="Screen Shot 2020-02-18 at 12 32 15 AM" src="https://user-images.githubusercontent.com/18335310/74710285-db317180-51e6-11ea-88d3-1b76000e4e59.png">

Thanks!
