### ISSUE TITLE
Link to navigate to a specific panorama scene inside a tour.

### ISSUE THREAD

**Issue by sgouver** [google/marzipano#239]
Hello all,

I would like to know if it is possible with JavaScript to manipulate if a user can start the tour in a specific page/panorama instead of the default/initial one.

This feature is currently exists for example in [Walkinto](https://walkinto.in/tour/b1VVHcEo1Q-yeEEr9No1Q?).
However, they use the Google location to specify the exact panorama you want to target inside the tour ([Link](https://walkinto.in/tour/b1VVHcEo1Q-yeEEr9No1Q?scene=49.28742659946266|-123.1137304008007|23.495085371866324|-3.0281579897237534|0.5999552151966289|CAoSLEFGMVFpcE5zamhZRmFfalBEWkgwS05Bazk4blpTNVlpU2JhSGx3ZWo0bUlK|false|GOOGLE)).

![dedicated-link](https://user-images.githubusercontent.com/25384759/56871289-a106a180-6a13-11e9-95d4-f2ddc2c094e8.JPG)

However, I don't know if this can be done with Marzipano.

Thank you for your support.

Best regards,
Stefanos

**Comment by campmdabt** [comment]
It is definitely possible! However it's not currently implemented in the output from the Marzipano tool if that's what you're looking for.

I'm doing this currently in our implementation by checking the 'sceneId' query parameter within the URL and using the Marzipano 'Scene.switchTo()' function to show that scene with the associated ID (from my specific implementation) when the page is opened. This will require web development knowledge and is not an off-the-shelf solution, however Marzipano makes it easy to implement if you have that knowledge.

**Comment by Ristophonics** [comment]
next... how to do can we generate a link to a specific hotspot in a given scene.. then using LookTo() etc etc
