### ISSUE TITLE
360 video demos don't work on iOS

### ISSUE THREAD

**Issue by aelmahalawey** [google/marzipano#24]
Hi,
I tried to open the video demo posted on marzipano site on ios 9.3.1 (Iphone) and ios 9.0.2 (Ipad) without any success, The video doesn't play on both devices with the same behavior; it loads the video player bar and when I press the play button nothing happens.

Note: I made sure that both devices support webgl and all other demos that holds a panoramic image works fine

**Comment by tjgq** [comment]
The `video` and `video-multi-res` demos are known not to work on iOS devices. Unfortunately, playing 360 video on iOS isn't as straightforward as on other browsers, but there is a known technique (see https://github.com/Jam3/ios-video-test). However, nobody has done the work to include it in the demos.

**Comment by HollandRisley** [comment]
Is anyone working on this? Does anyone have any pointers on where we can start with this? Can anyone foresee any major challenges? Any advice would be appreciated? We can push this back in afterwards.. if we can get it to work!

**Comment by hay** [comment]
This might be able to work on iOS 10 with the `playsinline` attribute. I've tried that in the `video` demo and at least the video doesn't go to fullscreen. There is something happening (i get feedback in the console) but nothing is happening on the `canvas`.

**Comment by calatador** [comment]
I got same problem with you , I get solve it using http://krpano.com/video/

**Comment by ahmedelmahalawey** [comment]
@calatador Yeah I also used krpano for this problem as it seems there is a problem with playing inline videos in IOS and krpano uses a hack to achieve that task.

**Comment by wwallace** [comment]
Any progress on this?

**Comment by theroyaltyclub** [comment]
With ARKit allowing for 360 content to be displayed in Safari, is it possible now?

**Comment by tjgq** [comment]
The video demos have been fixed to work on iOS 10 and above (see 00843fd). This fix will be part of the next release (note that the website hasn't been updated yet).

Please reopen if playback issues persist.
