### ISSUE TITLE
Changing device orientation breaks panning on large screen resolutions

### ISSUE THREAD

**Issue by campmdabt** [google/marzipano#240]
Found this bug when testing on Pixel 3 (1080 x 2160), changing device orientations. Changing to the opposite orientation from page load, panning is broken on the right/bottom half of the screen.

1. Load the [sample tour demo](http://www.marzipano.net/demos/sample-tour/index.html) either on a similar resolution device, or using Chrome Developer Tools and the Mobile/Tablet toolbar with the resolution set to 1080x2160. 
2. Change the orientation of the device (or use the 'rotate' button on dev tools).
3. Try to move the pano using either the right half of the screen if landscape, or bottom half if portrait. Observe the tiny movement on every second touch/click.
4. Move the pano on the left half of the screen in landscape, or top half if portrait. Observe correct functionality.
5. Change the orientation back. Observe all functionality restored.

It looks like the input event is still firing the correct code path, but then input is being released too soon? It also doesn't happen on smaller resolution screens, even of the same aspect ratio. 

After doing some more troubleshooting, it looks like anytime the screen size grows after the viewer loads, any parts of the screen bigger than that original viewer size have this issue.

**Comment by tjgq** [comment]
Thanks for reporting.

This looks like a Chrome bug. After the orientation change, touch gestures on the previously invisible part of the page end prematurely with a `pointercancel`.

A viable workaround is to set `touch-action: none` on the viewer element.

**Comment by campmdabt** [comment]
Crushed it, per usual. Thanks for the workaround.

I'm ignorant about `touch-action` in general, but Mozilla seems to tell me it's a way to divide touch event handling between the browser and the application. Do you know of any use cases where Marzipano would be relying on the default browser handling where `style="touch-action:none;"` would possibly cause unintended issues?

**Comment by tjgq** [comment]
It shouldn't make a difference, as Hammer.js (the library Marzipano uses internally to listen for touch events) already sets `touch-action: none` on the controls element, which is a child of the viewer element and occupies the same space.

The mystery is why that isn't enough to prevent triggering the default handling - and why device orientation would make a difference, since the DOM layout remains exactly the same apart from the element dimensions.
