### ISSUE TITLE
[Question]: How to create draggable hotspot

### ISSUE THREAD

**Issue by olivbau** [google/marzipano#249]
I want to create a tour creator (like the Marzipano Tool)
I can't figure out how to create a draggable/movable Hotspot

Do you know how I can do that ?

**Comment by campmdabt** [comment]
I do it by registering a mousedown event handler on the hotspot, disabling the Marzipano controls temporarily (so dragging doesn't move the pano), register a mousemove event handler on the document which re-locates the hotspot on every frame: 

		// calculate the new cursor position:
		deltaX = lastX - event.clientX;
		deltaY = lastY - event.clientY;
		lastX = event.clientX;
		lastY = event.clientY;

		// set the element's new position:
		element.style.left = (element.offsetLeft - deltaX - parseInt(window.getComputedStyle(element).marginLeft)) + "px";
		element.style.top = (element.offsetTop - deltaY - parseInt(window.getComputedStyle(element).marginTop)) + "px";

I also register a mouseup event handler that gets the new element position, uses `screenToCoordinates()` to get the new location on the pano, and then re-saves the hotspot position to that location. Then it re-enables the Marzipano controls, clears the mousemove & mouseup handlers, and resets the element style.left and sytle.top to null.

**Comment by olivbau** [comment]
Thank you for these awesome tips !
I almost succeeded, could you tell me what coordinates do you pass to `screenToCoordinates()` in the mouseup event ?

**Comment by campmdabt** [comment]
Here's what I do to get the right location: 

```
const elPos = $(element).position();
const newHsPos = curView.screenToCoordinates({elPos.left, elPos.top});
```

Then on the Marzipano hotspot object I call `setPosition(newHsPos);`

Don't forget to reset the element styles after you set the position, otherwise it will add that to the new position of the hotspot:

```
element.style.left = null;
element.style.top = null;
```

**Comment by tombzbk** [comment]
Hello #olivbau
Possible to show your code drag event to me.
please.

**Comment by hlmountan** [comment]
> I do it by registering a mousedown event handler on the hotspot, disabling the Marzipano controls temporarily (so dragging doesn't move the pano), register a mousemove event handler on the document which re-locates the hotspot on every frame:
> 
> ```
> 	// calculate the new cursor position:
> 	deltaX = lastX - event.clientX;
> 	deltaY = lastY - event.clientY;
> 	lastX = event.clientX;
> 	lastY = event.clientY;
> 
> 	// set the element's new position:
> 	element.style.left = (element.offsetLeft - deltaX - parseInt(window.getComputedStyle(element).marginLeft)) + "px";
> 	element.style.top = (element.offsetTop - deltaY - parseInt(window.getComputedStyle(element).marginTop)) + "px";
> ```
> 
> I also register a mouseup event handler that gets the new element position, uses `screenToCoordinates()` to get the new location on the pano, and then re-saves the hotspot position to that location. Then it re-enables the Marzipano controls, clears the mousemove & mouseup handlers, and resets the element style.left and sytle.top to null.

Hello #campmdabt 
I do precisely your tip but the hotspots element didn't recognize mousedown event when I touch and drag hotspot, it comes only when single touch.  
One more question: how do I disabling the Marzipano controls temporarily, the documentation does not mention it. 
  controls.disable(); 
controls.enable(); 
right ?  
 I'm developing an Android VR app to view a 360 image. it able to create hotspots, drag/drop hotspot and does teleport to other  360 images when clicking on hotspots.
Thanks,

**Comment by campmdabt** [comment]
If you're using touch vs mouse input, you'll probably have to listen for a different event. I haven't really worked through our mobile version yet so I don't have any guidance.

But here's how I enable & disable the controls:
```
const viewer = new Marzipano.Viewer(panoDivElement, {
		stage: {
			antialias: true,
			generateMipmaps: true
		}
	});

/**
 * Enables or disables the viewer controls
 * @param {boolean} newEnableBool 
 */
export function setControlsEnabled(newEnableBool) {
	newEnableBool ? viewer.controls().enable() : viewer.controls().disable();
}
```

**Comment by hlmountan** [comment]
I finally figure out the 'touchmove', 'touchstart', 'touchend' events. 
 So Thanks, u bro! 

i just wondering why the documentation is so sketchy like that.

**Comment by calacianu** [comment]
Hi, can someone copy/paste the source code for dragging and dropping the hotspot?

**Comment by angularbinh2020** [comment]
> Hi, can someone copy/paste the source code for dragging and dropping the hotspot?

const addEventDragable = element => {
    let isDragging, lastPosX, lastPosY;
    element.classList.add('cursor-grab');
    const handleDrag = function (ev) {
      const elem = ev.target;
      if (!isDragging) {
        isDragging = true;
        lastPosX = elem.offsetLeft;
        lastPosY = elem.offsetTop;
        element.classList.add('cursor-grabbing');
        viewer.controls().disable();
      }
      const posX = ev.deltaX + lastPosX;
      const posY = ev.deltaY + lastPosY;
      elem.style.left = posX + 'px';
      elem.style.top = posY + 'px';
      if (ev.isFinal) {
        isDragging = false;
        const anotherPosition = $(elem).position();
        const currentPosition = {
          x: anotherPosition.left,
          y: anotherPosition.top,
        };
        const newHsPos = currentView.screenToCoordinates(currentPosition);
        hotSpot.setPosition(newHsPos);
        onChangeHotPosition &&
          onChangeHotPosition({
            id: id,
            ...hotSpotDefaultConfig,
            ...newHsPos,
          });
        elem.style.left = '0px';
        elem.style.top = '0px';
        element.classList.remove('cursor-grabbing');
        viewer.controls().enable();
      }
    };
    const dragObject = new Hammer(element);
    dragObject.add(
      new Hammer.Pan({ direction: Hammer.DIRECTION_ALL, threshold: 0 }),
    );
    dragObject.on('pan', handleDrag);
  };

  addEventDragable(domElement);

i use hammerjs to create drag action. domElement is the html element you use to create hotspot

**Comment by ZuperZee** [comment]
> Hi, can someone copy/paste the source code for dragging and dropping the hotspot?

Javascript
```js
import Marzipano from "marzipano";

function createScene(viewer) {
  const source = Marzipano.ImageUrlSource.fromString("ImageURL.jpg");

  const geometry = new Marzipano.EquirectGeometry([{ width: 4096 }]);

  const limiter = Marzipano.util.compose(
    Marzipano.RectilinearView.limit.vfov(0, 3),
    Marzipano.RectilinearView.limit.hfov(0, 3),
    Marzipano.RectilinearView.limit.pitch(-Math.PI / 2, Math.PI / 2)
  );
  const view = new Marzipano.RectilinearView(
    {
      yaw: 0,
      pitch: 0,
      fov: (100 * Math.PI) / 180,
    },
    limiter
  );

  const scene = viewer.createScene({
    source: source,
    geometry: geometry,
    view: view,
    pinFirstLevel: true,
  });

  return scene;
}

function createHotspot(scene, hotspotElement) {
  const hotspot = scene.hotspotContainer().createHotspot(hotspotElement, {
    yaw: 0,
    pitch: 0,
  });

  return hotspot;
}

function addDrag(element, hotspot, viewer) {
  let lastX, lastY;

  function onMouseDown(event) {
    lastX = event.x;
    lastY = event.y;

    viewer.controls().disable();

    window.addEventListener("mousemove", onMouseMove);
    window.addEventListener("mouseup", onMouseUp);
  }

  function onMouseMove(event) {
    const { x: offsetX, y: offsetY } = viewer
      .domElement()
      .getBoundingClientRect();

    const { x: elementX, y: elementY } = element.getBoundingClientRect();

    const deltaX = event.x - lastX;
    const deltaY = event.y - lastY;

    const x = deltaX + elementX - offsetX;
    const y = deltaY + elementY - offsetY;

    lastX = event.x;
    lastY = event.y;

    hotspot.setPosition(viewer.view().screenToCoordinates({ x, y }));
  }

  function onMouseUp() {
    viewer.controls().enable();
    console.info("Hotspot position", hotspot.position());

    window.removeEventListener("mousemove", onMouseMove);
    window.removeEventListener("mouseup", onMouseUp);
  }

  element.onmousedown = onMouseDown;
}

const panoramaContainer = document.querySelector("#panorama-container");
const hotspotElement = document.querySelector("#hotspot");

const viewer = new Marzipano.Viewer(panoramaContainer);
const scene = createScene(viewer);
const hotspot = createHotspot(scene, hotspotElement);
addDrag(hotspotElement, hotspot, viewer);

scene.switchTo();
```

HTML
```html
<div id="panorama-container" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%">
  <div id="hotspot">Drag me</div>
</div>
```
