### ISSUE TITLE
WebVR using same source

### ISSUE THREAD

**Issue by Aykelith** [google/marzipano#252]
I want to implement WebVR, but I don't know how to transform my panoramas for the left/right eye. For the moment I'm using this script [https://github.com/mpetroff/pannellum/blob/master/utils/multires/generate.py](https://github.com/mpetroff/pannellum/blob/master/utils/multires/generate.py) but I don't know if `nona` can generate the a panorama for left/right eye.

Also, it is not possible to use the same source but to change the projection in order to be correct for the left/right eye?

**Comment by tjgq** [comment]
It's possible to adapt the WebVR demo for a monoscopic image (same panorama for both eyes). See [this thread](https://groups.google.com/forum/#!topic/marzipano/KONiV98nPbY).

I haven't used the Pannellum generation scripts before, so I can't provide advice there.
