### ISSUE TITLE
When I'm trying to load marzipano.js in ionic framework it says "GET http://localhost:8100/marzipano.js net::ERR_ABORTED 404 (Not Found)". Is there any possibility to add marzipano in Ionic Framework?

### ISSUE THREAD

**Issue by Superman-India** [google/marzipano#253]
![Screenshot (116)](https://user-images.githubusercontent.com/35029650/60807439-5b98ea00-a1a3-11e9-8dd8-e34344abc99f.png)
![Screenshot (117)](https://user-images.githubusercontent.com/35029650/60807440-5b98ea00-a1a3-11e9-9d30-cc5b873d1e9c.png)

![Screenshot (118)](https://user-images.githubusercontent.com/35029650/60807492-7d926c80-a1a3-11e9-924d-bc86e11d4dbd.png)

When I press CTRL + Link over <script src="marzipano.js" ></script> in VSCode i'm able to open it.

I even tried : type="text/javascript">

Thanks in advance!♥

**Comment by tjgq** [comment]
What happens when you go to `http://localhost:8100/marzipano.js` in your browser?

**Comment by Superman-India** [comment]
![Screenshot (120)](https://user-images.githubusercontent.com/35029650/60822892-f1447180-a1c3-11e9-8af9-ebbb629aa4f2.png)

**Comment by Superman-India** [comment]
Thanks for your response.
I'm new to angular and ionic.
Help me to resolve this.
♥Thanks♥

**Comment by tjgq** [comment]
The issue seems to be that your development server isn't configured to serve the `marzipano.js` file. I'm not familiar enough with Angular to be able to help. Sorry.
