### ISSUE TITLE
Only demo image works on iOS, not other equirectangular images

### ISSUE THREAD

**Issue by calbear47** [google/marzipano#261]
I have create a very brief video demo of the issue I am experiencing. The demo Equirectangular image loads on Chrome and iOS...but other equirectangular images don't. I'm reading both of the images from my local machine. Please see video:

https://youtu.be/rd26dC9BUCk

I have also included screen shots of the info details for both the demo image and my image, see below: 
![Screen Shot 2019-07-30 at 9 14 26 AM](https://user-images.githubusercontent.com/16049160/62147317-1d777d80-b2ac-11e9-8618-fc235d847107.png)
![Screen Shot 2019-07-30 at 9 13 55 AM](https://user-images.githubusercontent.com/16049160/62147331-210b0480-b2ac-11e9-8f3a-6df92cf8cdba.png)

Finally, I have included the very basic demo code for each case. 

Here is the code I'm using with the demo image you have provided: 

```js
    var viewer = new Marzipano.Viewer(document.getElementById('pano'));

    // Create source.
    var source = Marzipano.ImageUrlSource.fromString(
      "/images/angra.jpg" // THIS CHANGES
    );

    // Create geometry.
    var geometry = new Marzipano.EquirectGeometry([{ width: 4000 }]); // THIS CHANGES

    // Create view.
    var limiter = Marzipano.RectilinearView.limit.traditional(1024, 120*Math.PI/180);
    var view = new Marzipano.RectilinearView({ yaw: 0, pitch: 0, fov: Math.PI/2 }, limiter);

    // Create scene.
    var scene = viewer.createScene({
      source: source,
      geometry: geometry,
      view: view,
      pinFirstLevel: true
    });

    // Display scene.
    scene.switchTo();
```

Here is the code for my image: 

```js
    var viewer = new Marzipano.Viewer(document.getElementById('pano'));

    // Create source.
    var source = Marzipano.ImageUrlSource.fromString(
      "/images/8_50.jpg" //THIS CHANGES
    );

    // Create geometry.
    var geometry = new Marzipano.EquirectGeometry([{ width: 6912 }]); //THIS CHANGES

    // Create view.
    var limiter = Marzipano.RectilinearView.limit.traditional(1024, 120*Math.PI/180);
    var view = new Marzipano.RectilinearView({ yaw: 0, pitch: 0, fov: Math.PI/2 }, limiter);

    // Create scene.
    var scene = viewer.createScene({
      source: source,
      geometry: geometry,
      view: view,
      pinFirstLevel: true
    });

    // Display scene.
    scene.switchTo();
```
I can send you the image if you would like? This seems like a bug, but maybe I'm doing something wrong that I'm oblivious to. Thanks for you help.

**Comment by tjgq** [comment]
The most likely explanation is that the image are too big to fit in a single WebGL texture. Check the value of `gl.MAX_TEXTURE_SIZE`.

I'd recommend using a cubemap instead.

**Comment by calbear47** [comment]
Ok great, thank you for your quick response. I will check that and get back to you.
