### ISSUE TITLE
marzipano can't init when it display none

### ISSUE THREAD

**Issue by Richardo8** [google/marzipano#262]
hello,

I hide my marzipano block at began of my project, and use button to change it show, but it not work, how can I init it, Thanks~

**Comment by tjgq** [comment]
I'm sorry, I don't understand the question. Do you have a link to your source code that I can take a look at?

**Comment by Richardo8** [comment]
> I'm sorry, I don't understand the question. Do you have a link to your source code that I can take a look at?

hello, I had resolve this issue, use "viewer.updateSize()", THX~
