### ISSUE TITLE
The demo of deviceOrientationControlMethod is working only on marzipano.net on Chrome

### ISSUE THREAD

**Issue by bulesz** [google/marzipano#267]
Hello,

I have cloned the Device Orientation demo to my host, all the same except:

on demo index.html:

<script src="../../build/marzipano.js" ></script> 

(is it using a newer / different version than the 0.9.0 ?)

on my site (copy of the demo package)

<script src="vendor/marzipano.js" ></script>
(using the available marzipano.js 0.9.0)

The clone demo is not working on Chrome.

http://ultratek.hu/bubi/device-orientation/ - not working on Chrome

https://www.marzipano.net/demos/device-orientation/ - working on Chrome

What could be the issue?

No console error was got in dev tool.

Many thanks,
Bulcsu

**Comment by campmdabt** [comment]
Needs to be hosted on a secure site using https for the orientation api to
work.

**Comment by bulesz** [comment]
Thank you for the quick response, I will check it.

**Comment by bulesz** [comment]
With FireFox and Safari it is working fine, only with Chrome not working (without any error message)

Thanks again, I will try with HTTPS too.

**Comment by bulesz** [comment]
Thank you for your quick help and reply!
