### ISSUE TITLE
i didn't see exe file

### ISSUE THREAD

**Issue by haein8244** [google/marzipano#272]
i wanna make exe file. 
i saw only css, html.
what's wrong with you? 

![issue](https://user-images.githubusercontent.com/55757239/65530445-d624fc00-deac-11e9-9db4-c4409b8a90ad.JPG)

**Comment by tjgq** [comment]
There's no exe file. To display the generated tour, you need to either deploy the files to a web hosting service, or run a web server on your local machine.
