### ISSUE TITLE
Vue-Cli & Webpack - Images not loading

### ISSUE THREAD

**Issue by elliot86** [google/marzipano#273]
Hi all - this is a call for support not an issue with Marzipano.

I'm having a lot of difficulty rendering the images using Vue-Cli and webpack. Images are being returned with a 200 code, yet previewed as white in console (and not loading in browser).

My vue project is using the Marzipano package from NPM and I'm using the index.js from exported files from Marzipano Tool. 

This is the function that seems to be failing through Webpack:
`var scenes = data.scenes.map(function(data) {
    var urlPrefix = "tiles";
    var source = Marzipano.ImageUrlSource.fromString(
      urlPrefix + "/" + data.id + "/{z}/{f}/{y}/{x}.jpg",
      { cubeMapPreviewUrl: urlPrefix + "/" + data.id + "/preview.jpg" });
}`

Any help would be greatly appreciated. Alternatively a small Vue-Cli project (using webpack) with Marzipano working would be incredible (I'll totally shout you a beer).

**Comment by elliot86** [comment]
I'm going to try with React instead.

**Comment by leonard081119** [comment]
how to do this with react

**Comment by cesasol** [comment]
You need to put all the generated images on a static route, for example @elliot86  in a traditional vue/cli app you would put all the images on the public folder, the same goes for react or any webpack based build tool @leonard081119 

For example this [site](https://www.andressiegel.com/recorrido) is made with nuxt and all the images are in the static folder
