### ISSUE TITLE
Image view is cube not 360

### ISSUE THREAD

**Issue by dev-ahmad** [google/marzipano#275]
<img width="1440" alt="Screen Shot 2019-10-04 at 11 21 15 PM" src="https://user-images.githubusercontent.com/30356286/66237472-cbb10080-e6fd-11e9-9804-5ec50243c9fa.png">

Hi can you please help me in this issue? 

Why the image is cube not 360? it's from samsung gear 360 image..
Thanks .. 
@tjgq @manuelcabral @jordyno @nikolakanacki

**Comment by jordyno** [comment]
Can you provide us the source image you used?

**Comment by tjgq** [comment]
It looks like some of your cube faces are swapped.
