### ISSUE TITLE
How to implement view mode(fisheye, pannini, etc.)?

### ISSUE THREAD

**Issue by kuldip-shukla** [google/marzipano#276]
Hello guys, is there any possibility for different projection modes like dubai360.com?
![Screenshot from 2019-10-17 01-38-48](https://user-images.githubusercontent.com/46015733/66986044-b1066080-f0db-11e9-9b81-587cba534a7c.png)

If yes then please provide me direction. So, I can implement all this mode in mine.

_Originally posted by @kuldip-shukla in https://github.com/google/marzipano/issues/106#issuecomment-543040720_

**Comment by tjgq** [comment]
For each projection type you would need to implement a new `View` subclass (to parameterize the view) and a `Renderer` to do the actual rendering. I would suggest trying to understand how the geometry, view and renderer work together first. I can answer concrete questions if you have them.
