### ISSUE TITLE
Cannot hide/show layers

### ISSUE THREAD

**Issue by joao-cesar** [google/marzipano#277]
Hi.

I cannot properly hide or show layers. When I try changing the layer's corresponding DOM element style it seems there is no effect.

Is there a property or method to accomplish this task?

Thanks.

**Comment by tjgq** [comment]
What do you mean by "the layer's DOM element"? Unless you're using the CSS renderer, all layers are rendered into the WebGL canvas, which is a single DOM element. There are other elements on top that Marzipano uses to implement the controls, hotspots, etc, but they're managed by Marzipano and shouldn't be touched by other code.

You can show or hide a layer (the entity represented by the `Layer` class) by adding or removing it from the `Stage` with the `Stage#addLayer` and `Stage#removeLayer` methods. Is that what you need?

**Comment by joao-cesar** [comment]
Thanks for answering.

OK. So I understand the part that all layers are rendered into a single WebGL canvas element.

But I still cannot achieve what I want. Because I succesfully use the _removeLayer_ method. But when I use the _addLayer_ method to bring the layer back again, it's not always readded in the correct perspective.

Is there a way I can readd the layer with the correct transformation or can I simply change its opacity or visibility?

**Comment by tjgq** [comment]
The perspective is determined by the `View` associated with the `Layer`, so it should not change when removing the layer and adding it back.

Adding and removing will, however, put the layer on top of existing layers, which matters when layers have transparency. If necessary call `Stage#moveLayer` to move the layer into the correct stacking order.

To change the layer opacity call `Layer#setEffects`.
