### ISSUE TITLE
how to use own tiles jpg files instead of demo jpg

### ISSUE THREAD

**Issue by ehertogh** [google/marzipano#284]
In het index.js (from the demo hotspot-styles) I want to change the default demo jpg:
`//www.marzipano.net/media/furnace/{z}/{f}/{y}/{x}.jpg"`
into my own generated tiles that I have created with the marzipano tool.

So I thought to copy the index.js from the generated one of the marzipano tool but then the view is disordered and without the images.

How can I do that properly?

**Comment by ehertogh** [comment]
I just solved it myself: simply change the root //www.marzipano.net/media/furnace/ into my own root where furnace is the tiles folder.
emptying the cache of the browser helped

**Comment by Eda87** [comment]
Hello. sorry for the inconvenience but I can't complete this step ... do I have to change the whole root? or just the name furnace? thanks
