### ISSUE TITLE
Hotspots look blurry

### ISSUE THREAD

**Issue by un0btanium** [google/marzipano#288]
Hello,

I am currently working on a project using the Marzipano library and I noticed that the hotspot html elements all look kind of blurry. It is espacially obvious with text.

The left one is the normal html element and on the right it is a hotspot. I would like the hmtl element to be tracked when the user drags the panorama, however I am not sure if I like the blur. Is there any solution to this or is that just a sideffect that cant be resolved easily?

![image](https://user-images.githubusercontent.com/4930282/72569452-ca759f00-38ba-11ea-9cad-474031f2c49c.png)

**Comment by campmdabt** [comment]
I find that it has to do with the browser. In Edge, DOM elements inside the canvas look much clearer than in Chrome for some reason. Maybe someone with more rendering expertise knows more.

![image](https://user-images.githubusercontent.com/15316009/72570875-13fac580-388c-11ea-9105-531ec3a0421e.png)
![image](https://user-images.githubusercontent.com/15316009/72570769-c9794900-388b-11ea-88c9-4d9d552be362.png)

**Comment by un0btanium** [comment]
I can confirm, this does happen in Chrome. However, I currently cant test it in other browsers (using JS features only chrome supports :S)

**Comment by tjgq** [comment]
A bit of a wild guess: does removing the `translateZ(0)` from https://github.com/google/marzipano/blob/master/src/util/positionAbsolutely.js#L32 solve this issue?

**Comment by campmdabt** [comment]
Looks like this does solve the issue on Chrome, which is the only place I really noticed it:

Old:
![image](https://user-images.githubusercontent.com/15316009/74656830-edff6400-515c-11ea-9ed0-4018aa6c36e5.png)

New:
![image](https://user-images.githubusercontent.com/15316009/74656906-1b4c1200-515d-11ea-9e13-7bc0c523f509.png)

Thanks for the fix!

**Comment by un0btanium** [comment]
Yep that fixes it.
