### ISSUE TITLE
Firefox for Android: cannot move, "Bad WebGL context"

### ISSUE THREAD

**Issue by ondrej-vipo** [google/marzipano#289]
There is an issue that you cannot move left/right nor up/down on Firefox for Android.
I have tested that same error occures in "Firefox", "Firefox beta" and also "Firefox preview" apps.

Tested website: https://www.marzipano.net/demos/sample-tour/
Here is error from console:
![marzipano-err](https://user-images.githubusercontent.com/57705534/73354579-56fa6700-4296-11ea-9c78-cdc1402c160d.png)

**Comment by tjgq** [comment]
Which device is this? I tried Firefox on a Google Pixel 3 and it works.

**Comment by ondrej-vipo** [comment]
ASUS Zenfone ZE551ML
Android 7.1.2 (LineageOS 14.1)

**Comment by ondrej-vipo** [comment]
OK, I have same issue with other WebGL apps, this is propably a Firefox bug. I'm closing this.

**Comment by ondrej-vipo** [comment]
Reported on bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1612262
