### ISSUE TITLE
[Question] Can Marzipano be used to display non 360° panoramas?

### ISSUE THREAD

**Issue by twatzl** [google/marzipano#290]
Hello,

I am looking for a panorama viewer for my blog which supports cardboard, so I stumbled upon Marzipano. However Marzipano Tool seems to requires my panoramas to be 360°. Most of my panoramas are not 360 degrees, so this is kind of an issue.

So far I have experience with Google Cardboard Camera and it is able to display non 360 degree panorama images. The rest of the background is just blurred repetition of the image. Is it possible to do the same thing also with Marzipano?

Kind regards.

**Comment by twatzl** [comment]
Ok. So I made it work using Gimp for adding a blurred background (and thus extending the pano to 360 by 180 degrees). So I will probably write a tool at some point in the future which will handle the preprocessing.

I still wonder where Google Cardboard takes the HFOV and VFOV values from though. I just cannot imagine that they parse the string in the exif comment left behind by Hugin.

Question still remains: Does Marzipano have integrated support for preprocessing like this?

**Comment by tjgq** [comment]
Not supported, sorry. The Marzipano Tool requires the panoramas to be complete (2:1 aspect ratio) and ignores the EXIF metadata.
