### ISSUE TITLE
Black screen on video-mulit-res

### ISSUE THREAD

**Issue by dzolotor** [google/marzipano#294]
I'm experiencing a black screen with audio running the video-multi-res demo locally and deployed, and I am serving the file. This is happening on both MacOS and Windows in Chrome and Safari at least. This can also be reproduced by using the demo video-multi-res at https://www.marzipano.net/demos/video-multi-res/

If it the screen isn't immediately black, refreshing should quickly reproduce the problem.

<img width="1792" alt="Screen Shot 2020-02-18 at 12 30 17 AM" src="https://user-images.githubusercontent.com/18335310/74749516-e52b9280-522f-11ea-801c-bc5160690d79.png">

<img width="758" alt="Screen Shot 2020-02-18 at 12 32 15 AM" src="https://user-images.githubusercontent.com/18335310/74749536-e8268300-522f-11ea-864f-b6de363f9b61.png">

**Comment by tjgq** [comment]
A search for "video visible size is empty" turns up some interesting results. For me, this only occurs in Chrome (I can't reproduce in Safari nor Firefox) and seems to be due to https://bugs.chromium.org/p/chromium/issues/detail?id=898550.
