### ISSUE TITLE
`npm run dev` fails on Windows

### ISSUE THREAD

**Issue by SkylarKitchen** [google/marzipano#3]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.6.0
3 info using node@v5.6.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle marzipano@0.5.0~predev: marzipano@0.5.0
6 silly lifecycle marzipano@0.5.0~predev: no script for predev, continuing
7 info lifecycle marzipano@0.5.0~dev: marzipano@0.5.0
8 verbose lifecycle marzipano@0.5.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle marzipano@0.5.0~dev: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Skylar\documents\web\marzipano\node_modules.bin;C:\Users\Skylar\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Skylar\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\Common Files\Autodesk Shared;C:\Program Files (x86)\Autodesk\Backburner;C:\Program Files\nodejs;C:\Users\Skylar\AppData\Local\atom\bin;C:\Users\Skylar\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle marzipano@0.5.0~dev: CWD: C:\Users\Skylar\documents\web\marzipano
11 silly lifecycle marzipano@0.5.0~dev: Args: [ '/d /s /c', 'scripts/dev' ]
12 silly lifecycle marzipano@0.5.0~dev: Returned: code: 1  signal: null
13 info lifecycle marzipano@0.5.0~dev: Failed to exec dev script
14 verbose stack Error: marzipano@0.5.0 dev: `scripts/dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid marzipano@0.5.0
16 verbose cwd C:\Users\Skylar\documents\web\marzipano
17 error Windows_NT 10.0.10586
18 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "dev"
19 error node v5.6.0
20 error npm  v3.6.0
21 error code ELIFECYCLE
22 error marzipano@0.5.0 dev: `scripts/dev`
22 error Exit status 1
23 error Failed at the marzipano@0.5.0 dev script 'scripts/dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the marzipano package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     scripts/dev
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs marzipano
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls marzipano
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by tjgq** [comment]
Are you able to run `./scripts/dev` directly from the shell? The dev script is written in Bash, so on Windows you need to have Cygwin (or some equivalent) installed.

**Comment by SkylarKitchen** [comment]
Tiago,

I am able to run ./scripts/dev but I am not able to run "npm run dev"

Thank you for your help!

**Comment by tjgq** [comment]
Unfortunately, it seems you're a victim of this npm issue: https://github.com/npm/npm/issues/9420. Running the script directly may be the only option on Windows at the moment.

If you happen to find a workaround, be sure to let us know.

**Comment by SkylarKitchen** [comment]
Will do, thanks again for your help.

**Comment by ansarikhurshid786** [comment]
I have same problem as below : 

$ npm run dev

> marzipano@0.5.1 dev D:\marzipano
> scripts/dev

'scripts' is not recognized as an internal or external command,
operable program or batch file.

**Comment by wwallace** [comment]
@ansarikhurshid786 and anyone else having this issue in Windows. Prepend `sh`  to `scripts/dev` in your packages.json (`"dev": "sh scripts/dev",`) . Also,  as mentioned above, you need to be able to execute bash scripts.
