### ISSUE TITLE
White screen Angular integration with marzipano

### ISSUE THREAD

**Issue by 08BRYLL23** [google/marzipano#300]
I tried making an app using angular. I followed the documentation on creating a basic scene but it looks like the scene is not showing properly. It is only showing a white screen but the drag icon is showing so I think the viewer loaded?

Are there any advices on this?

#edit 
upon checking, it looks like the cause was Angular material. But I'm still curious why did this happen?

**Comment by tjgq** [comment]
I understand very little about Angular, but usually this sort of problem occurs when you don't set the necessary CSS properties on the viewer element (width, height, etc)

**Comment by beshad** [comment]
@08BRYLL23 can you explain how did you fix this? i am having the exact white screen but no console errors and everything seems to be loaded. i dont have any other libraries like Material in my project. thanks

**Comment by beshad** [comment]
anyone else having problem integrating this with Angular here is a working example https://github.com/beshad/angular-marzipano-sandbox

**Comment by BaoSkyFall** [comment]
> anyone else having problem integrating this with Angular here is a working example https://github.com/beshad/angular-marzipano-sandbox

_Thanks @beshad so much!!  I follow to your repo then I can apply this lib. You save my day <3
