### ISSUE TITLE
Add ImageUrlSource#fromString equirectangular preview support

### ISSUE THREAD

**Issue by jordyno** [google/marzipano#303]
I have added the equirectangular preview support because it comes handy when quickly adding equirect geometries - user doesn't need to manually build the cubface preview, just resize the equirectangular image. This is the changed code, let me know if PR desired.

```
ImageUrlSource.fromString = function(url, opts) {
  opts = opts || {};

  var faceOrder = opts && opts.cubeMapPreviewFaceOrder || defaultCubeMapFaceOrder;

  var urlFn = opts.cubeMapPreviewUrl || opts.equirectPreviewUrl ? withPreview : withoutPreview;

  return new ImageUrlSource(urlFn, opts);

  function withoutPreview(tile) {
    var tileUrl = url;

    for (var property in templateProperties) {
      var templateProperty = templateProperties[property];
      var regExp = propertyRegExp(property);
      var valueFromTile = tile.hasOwnProperty(templateProperty) ? tile[templateProperty] : '';
      tileUrl = tileUrl.replace(regExp, valueFromTile);
    }

    return { url: tileUrl };
  }

  function withPreview(tile) {
    if (tile.z === 0) {
      if(opts.equirectPreviewUrl) {
        return {
          url: opts.equirectPreviewUrl
        };
      } else {
        return cubeMapUrl(tile);
      }
    } else {
      return withoutPreview(tile);
    }
  }

  function cubeMapUrl(tile) {
    var y = faceOrder.indexOf(tile.face) / 6;
    return {
      url: opts.cubeMapPreviewUrl,
      rect: { x: 0, y: y, width: 1, height: 1/6 }
    };
  }
};
```

**Comment by tjgq** [comment]
This would be useful - can you send the PR?

**Comment by tjgq** [comment]
On second thought: this can already be done by passing a custom `tileToUrl` function to the `ImageUrlSource` constructor:

```
const source = new Marzipano.ImageUrlSource((tile) => {
    const url = (tile.z === 0) ? "preview.jpg" : "full_resolution.jpg";
    return { url };
});
```

Therefore, I'm no longer convinced that the `equirectPreviewUrl` parameter is worth adding.

(Note that, if you use an equirectangular preview, the main panorama must also be equirectangular; you can't mix and match. If we added support for heterogeneous geometries, then this FR would become more interesting. Unfortunately, it's not a trivial change.)

**Comment by jordyno** [comment]
@tjgq would it still make sense to add actual level support for equirect geometries though?

**Comment by tjgq** [comment]
This already works - you can pass multiple levels to the `EquirectGeometry` constructor, and pin the first (preview) level as you would for a cube map.
