### ISSUE TITLE
[FEATURE] Support HDR input

### ISSUE THREAD

**Issue by polarathene** [google/marzipano#308]
The tool mentions it supports equirectangular inputs, but doesn't seem to accept a common format like HDR? The file I tried to load is [Machine Shop 02 - HDRI Haven](https://hdrihaven.com/hdri/?h=machine_shop_02).

Any chance of that being supported? (The smaller JPG tone mapped version is fine, this is just about HDR file support in general)

**Comment by tjgq** [comment]
Only plain JPEG or TIFF images are supported. We're not planning to add any new features to the Marzipano Tool, sorry.
