### ISSUE TITLE
Marzipano tool import

### ISSUE THREAD

**Issue by stegeron** [google/marzipano#309]
Currently the tool does not allow me to import previously created tour. I would like to have a possibility to export the sources and later to import it back and continue or modify the tour.

Consider allowing this, even as a payed feature. Thanks.

**Comment by tjgq** [comment]
We're not planning to improve the Marzipano Tool any further, sorry.

**Comment by goatmessi10** [comment]
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Trial</title>
   

</head>
<body>
    <div id="domID"></div>
    <script src="marzipano.js"></script>
    <script type="text/javascript">
        var panoElement = document.getElementById("domID");
        var opts = {
            controls: {
                mouseViewMode: "drag"
            }
        }
        console.log("Reached !");

        var viewer = new Marzipano.Viewer(panoElement, opts);

        var levels = [
            { tileSize: 512, size: 512 },
            { tileSize: 512, size: 1024 }
        ];

        var geometry = new Marzipano.EquirectGeometry(levels);
        var source = Marzipano.ImageUrlSource.fromString("base.jpg");
        var view = new Marzipano.RectilinearView();
        console.log({source});
        console.log({view});
        console.log({geometry});
        console.log({viewer});
//         panoElement.addEventListener("click", function (e) {
//             var vi= viewer.view();
// console.log(vi.screenToCoordinates({x: e.clientX, y: e.clientY}));
// })


        var scene = viewer.createScene({
            source: source,
            geometry: geometry,
            view: view
        });

       scene.switchTo({ transitionDuration: 1000});
    </script>
     
</body>
</html>

**Comment by goatmessi10** [comment]
why this is not showing image on browser

**Comment by svk014** [comment]
@tjgq you should consider opensourcing the tool. You have created a very useful product, if you cannot maintain it and don't have intentions to monetize it, you would be helping a lot of people by monetising it.

**Comment by tunnaduong** [comment]
As of 2025, you guys can try out my new Marzipano Importer tool: https://marzipano-importer.tunnaduong.com/
Vibe-coded with Cursor anyway....

**Comment by neuhaus** [comment]
> As of 2025, you guys can try out my new Marzipano Importer tool: https://marzipano-importer.tunnaduong.com/ Vibe-coded with Cursor anyway....

Very cool. First minor issue I noticed: During import, it says "export".
