### ISSUE TITLE
View Offset Per Scene

### ISSUE THREAD

**Issue by campmdabt** [google/marzipano#315]
Some images we have are rotated with respect to other images in our set, and we'd like to be able to rotate the underlying image tiles irrespective of the hotspot container, keeping the view params the same. Is there an easy way to do that without having to artificially change the view by an offset every time we navigate to these scenes and then spawn the hotspots in the negative offset direction?

I didn't see anything in the reference besides addOffset… functions for the view which just offset the current view params in general and don't accomplish an underlying image transformation.

Any ideas appreciated.

**Comment by tjgq** [comment]
If I understand correctly, you'd like the origin of the view coordinates to be somewhere other than the center of the panorama.

This is not something Marzipano currently supports, but we'd accept a contribution to implement it.

**Comment by campmdabt** [comment]
Yes, that's what I'm looking for; way better way to say it.

I've implemented it for now at my application layer but I'll see about putting it into Marzipano at some point.
