### ISSUE TITLE
Marzipano stand alone  viewer

### ISSUE THREAD

**Issue by 0721499615** [google/marzipano#317]
It only seems that, what marzipano can do is to generate cubes of each photo. The only function it has is generation of 1..Generated Cube All this other capabilities which Marzipano has are not working 2.Simple Tour 3. Single Resolution Cube 4.Multiresolution Cube 5.Multiresolution Flat 6. Equirectangular 6.Video 7.Hotspot Styles 8.
Embedded Hotspots 8.Layers look at demo, after much testing I found those capabilities are missing.You mean it can't play jpeg, jpg or PNG file format which all photos are based on. In their website look at demo and they say its possible to Display a single resolution cubic image with Marzipano, Display an equirectangular image with Marzipano. A normal image will be uploaded into where images are being stored. That's why we were developing this application.The images are hosted in my server

**Comment by 0721499615** [comment]
It's a stand alone Marzipano viewer

**Comment by tjgq** [comment]
I'm sorry, I don't understand the point are trying to make. The features you mention are all illustrated by the demos at http://www.marzipano.net/demos.html. Do you mean they're not working for you? What happens when you open them?

**Comment by 0721499615** [comment]
I am facing issues  relating to open source viewer after following the
stand alone viewer API docs and installation of all software's
successfully. generations of  cubes is all I can see whereby each photo is
generated to so many cubes of  itself.

**Comment by tjgq** [comment]
If this is still a problem, please reopen with a link to a demo so we can see what is working incorrectly.
