### ISSUE TITLE
How can I rotate my scene from one point to another point

### ISSUE THREAD

**Issue by kartik1997EB** [google/marzipano#318]
Hello good evening, I want to rotate my screen from the current view to another certain point with an animation fashion same as autorotate animation, How could I do that? please share some info .

**Comment by campmdabt** [comment]
You can call lookTo() on either the viewer or the scene:

https://www.marzipano.net/reference/Scene.html#lookTo
https://www.marzipano.net/reference/Viewer.html#lookTo

**Comment by kartik1997EB** [comment]
Hey thanks a lot !
