### ISSUE TITLE
Hard to embed video

### ISSUE THREAD

**Issue by voibietbay** [google/marzipano#32]
Very hard to me when adding Embedded Hotspots, like video (own video or youtube).
Any suggestion about size of video and how to find yaw, pitch and perspective value.

**Comment by manuelcabral** [comment]
One way to do this is to use the Chrome Devtools to inspect the hotspot DOM element and edit the CSS transform there. The code for [RectilinearView.coordinatesToPerspectiveTransform()](https://github.com/google/marzipano/blob/master/src/views/Rectilinear.js#L827) shows how the transforms map to the hotspot parameters.
