### ISSUE TITLE
Mobile Rendering Broken

### ISSUE THREAD

**Issue by deadvcr** [google/marzipano#326]
My project works just fine on every browser (except IE), however trying to view the panorama on mobile shows a white screen and it never loads. Is there anything special you have to do to make it work on mobile?

Here's what my js code looks like:
```javascript
 // Detect desktop or mobile mode.
  if (window.matchMedia) {
    var setMode = function() {
      if (mql.matches) {
        document.body.classList.remove('desktop');
        document.body.classList.add('mobile');
      } else {
        document.body.classList.remove('mobile');
        document.body.classList.add('desktop');
      }
    };
    var mql = matchMedia("(max-width: 500px), (max-height: 500px)");
    setMode();
    mql.addListener(setMode);
  } else {
    document.body.classList.add('desktop');
  }

  // Detect whether we are on a touch device.
  document.body.classList.add('no-touch');
  window.addEventListener('touchstart', function() {
    document.body.classList.remove('no-touch');
    document.body.classList.add('touch');
  });

  
  // Use tooltip fallback mode on IE < 11.
  if (bowser.msie && parseFloat(bowser.version) < 11) {
    document.body.classList.add('tooltip-fallback');
  }


// Create viewer.
var viewer = new Marzipano.Viewer(document.getElementById('pano'));

// Create source.
var source = Marzipano.ImageUrlSource.fromString(
  "pano/blp-pano.jpg"
);

// Create geometry.
var geometry = new Marzipano.EquirectGeometry([{ width: 8192 }]);

// Create view.
var limiter = Marzipano.RectilinearView.limit.traditional(1024, 100*Math.PI/180);
var view = new Marzipano.RectilinearView({ yaw: Math.PI }, limiter);

// Create scene.
var scene = viewer.createScene({
  source: source,
  geometry: geometry,
  view: view,
  pinFirstLevel: true
});

// Display scene.
scene.switchTo();
```

**Comment by deadvcr** [comment]
Seems to be an issue with RectilinearView. Taking an output of https://www.marzipano.net/tool/ and modifying it with RectilinearView produces the same result: it works on desktops but does not work on mobile

**Comment by tjgq** [comment]
What do you mean by "modifying it with RectilinearView"? Do projects exported from the Marzipano Tool (with no local modifications) work for you? And if not, which mobile device(s) are affected?

**Comment by Scriptim** [comment]
I had the same issue. In my case, it was because the image file was too big. After reducing the resolution, it also worked on mobile devices. I suggest you either try that or use CubeGeometry instead.

Unfortunately, Marzipano does not print an error message here that would help you tracing the problem.

**Comment by elditea** [comment]
I also have issue with EquirectGeometry rendering on mobile. I've tried using images from the server up to 658KB, before failed to render on 840KB image on mobile (moto g5s plus. Android 7.1).

Going to use CubeGeometry instead, but have to figure it how to convert equirectangular images to cubefaces using JS first

**Comment by Novezeil** [comment]
To be specific, it's not about file size, instead it's about image resolution. For example iOS just can't take 8K image (for now).

**Comment by tjgq** [comment]
The issue is probably that your equirectangular image is too big to fit in a single WebGL texture in those devices. You should see an error in the developer console if that's the case.
