### ISSUE TITLE
Restrict viewing to X axis only

### ISSUE THREAD

**Issue by unofficialmatt** [google/marzipano#327]
Sorry to raise this as an issue but I couldn't see a better way to get in touch.

Is there a way to restrict a scene to only allow the viewer to pan horizontally, along the X axis, rather than in full 360 space? We have a 360 image, so I don't want to use the flat image example, rather, we don't want the user to be able to scroll up and see a ceiling, or down and see a floor!

**Comment by campmdabt** [comment]
You should be able to set up your `[RectilinearViewLimiter](https://www.marzipano.net/reference/global.html#RectilinearViewLimiter)` to limit the pitch min and max both to 0.

**Comment by unofficialmatt** [comment]
> You should be able to set up your [RectilinearViewLimiter](https://www.marzipano.net/reference/global.html#RectilinearViewLimiter) to limit the pitch min and max both to 0.

Amazing - problem solved, thankyou!

**Comment by ismaildkc** [comment]
how can i use this?
