### ISSUE TITLE
Marzipano Tool - Save Project

### ISSUE THREAD

**Issue by stijncalis** [google/marzipano#328]
Started using Marzipano last week and I really like it!
https://cohackreality.be/virtualtour/luca-gent-stlucas

Is there a feature planned to save a project in the online Marzipano Tool? 
Looking at the code, if the index.html & data.js could be imported again in the online tool, I could reposition hotspots in the (handy) interface instead of code-based.

**Comment by tjgq** [comment]
We're not planning to add any new features to the Tool, sorry.

**Comment by stijncalis** [comment]
Ok, thanks for the reply. I had my computer on for a couple of days, so I did not need to save. Worked out just fine :-) Nice piece of web software you've created!
