### ISSUE TITLE
ImageUrl.js, Line 146

### ISSUE THREAD

**Issue by ralphtee** [google/marzipano#33]
From ImageUrl.js, Line 146

`
var valueFromTile = tile[templateProperties[property]] || '';
`

If tile.x == 0, or tile.y == 0, or tile.z == 0, where (numeric) 0 is a valid tile number, then the r-value becomes '' (i.e., empty string). Hence the code below 

`
Marzipano.ImageUrlSource.fromString("/{z}/{x}{y}.jpg"); 
`

produces

`
"//.jpg"
`

**Comment by tjgq** [comment]
Oops. I unwittingly introduced this bug when fixing something else. Commit 6ad8a96 fixes this issue.
