### ISSUE TITLE
How can i customize faceRotation in Cube.js

### ISSUE THREAD

**Issue by jeonyeonbin** [google/marzipano#330]
Hello marzipano team

We want to change our preview image to be different from the rotation of your image.
 Can i change your field faceRotation in /src/geometries/Cube.js

Thanks in advance.

**Comment by tjgq** [comment]
You can set a different face order by passing a `cubeMapPreviewFaceOrder` option when calling `ImageUrlSource.fromString`:

```
const source = ImageUrlSource.fromString(..., { cubeMapPreviewUrl: ..., cubeMapFaceOrder: 'bdflru' });
```

However, the cubemap must always be laid out vertically, not horizontally.

**Comment by jeonyeonbin** [comment]
thanks  :D 👍
