### ISSUE TITLE
problem with marzipiano tool

### ISSUE THREAD

**Issue by kiki20202020** [google/marzipano#334]
the jpg loads perfect and it looks the 360 good, but when I export it and unzip the file i have a problem. when I open it in chrom it is all black. I don't know why this happens if it is supposed to be fine before exporting it. I would like to know why this os happening. 
![Sin título](https://user-images.githubusercontent.com/68263511/87383371-b5728380-c55e-11ea-9754-6e971e879669.png)

**Comment by kamillasak** [comment]
same problem here, dont work on chrome and firefox, only edge

**Comment by tjgq** [comment]
See https://github.com/google/marzipano/issues/92.
