### ISSUE TITLE
.swf file

### ISSUE THREAD

**Issue by miguelbofi** [google/marzipano#338]
I am surprised for the SWF file in the Vendor folder. I understand that the technology used is WebGL, but, what is the function of the flash file? What will happen with marzipano at the end of the year when Flash loses the support of the browsers?

**Comment by tjgq** [comment]
Marzipano does not require Flash except on very old browsers without WebGL support (IE 8 and 9). We no longer claim to support these browsers - we just haven't deleted the Flash code yet.
