### ISSUE TITLE
Side by side Hotspot

### ISSUE THREAD

**Issue by Omar-Flayyih** [google/marzipano#340]
Dear all,

I have a question about how I can create a hotspot in side by side rendering.

[https://www.marzipano.net/demos/side-by-side/](url)

I managed to put my panorama image in side by side :) but I couldn't create a hotspot in both layers :(

So if anyone gave me and code example about that, it will be very helpful.

Thanks in advance

**Comment by jordyno** [comment]
@tjgq What needs to be done to add this to Marzipano exactly? I think it's a very much needed feature for Marzipano to be able to work with hotspots within "VR-mode" the same way
