### ISSUE TITLE
Touchscreen bug (Google Chrome)

### ISSUE THREAD

**Issue by nobe1996** [google/marzipano#348]
If I try to scroll/drag in the hotspot text boxes on a touchscreen(or Google Chrome -> Device toolbar touch emulator) after the second touch event the view jumps away by itself by a determined degree (upwards to the left) from the actual hotspot.

The same issue happens on the Marzipano demo pages.

**Comment by tjgq** [comment]
Thanks for reporting. I found a fix and I'm going to update the `sample-tour` demo and the Marzipano Tool momentarily.
