### ISSUE TITLE
Creating the viewer requires the DOM element to already exist in the page.

### ISSUE THREAD

**Issue by r3db** [google/marzipano#35]
Hi.
I'm taking the `Single Resolution Cube` demo as a starting point.
And I noticed something.

Creating a `DOM` element on the fly and appending it to the `Document` works just fine.

```javascript
// Create element
var element = $('<div class="panorama">')[0];

// Append element to document
document.body.appendChild(element);

// Single Resolution Cube Demo Code
var viewer = new Marzipano.Viewer(element);
var source = Marzipano.ImageUrlSource.fromString("http://www.marzipano.net/media/cubemap/{f}.jpg");
...
```

But if I try to do the same into a fragment nothing happens, not even an error.

```javascript
// Create element
var element = $('<div class="panorama">')[0];
		
// Single Resolution Cube Demo Code
var viewer = new Marzipano.Viewer(element);
var source = Marzipano.ImageUrlSource.fromString("http://www.marzipano.net/media/cubemap/{f}.jpg");
var geometry = new Marzipano.CubeGeometry([{ tileSize: 1024, size: 1024 }]);
var limiter = Marzipano.RectilinearView.limit.traditional(4096, 100*Math.PI/180);
var view = new Marzipano.RectilinearView(null, limiter);

viewer.createScene({ source: source, geometry: geometry, view: view, pinFirstLevel: true }).switchTo();

// Append element to document
document.body.appendChild(element);
```
Is there a way to "render" to a fragment first and later append to the document?

**Comment by r3db** [comment]
The "issue" is here:
https://github.com/google/marzipano/blob/master/src/stages/Stage.js#L159

```javascript
Stage.prototype.updateSize = function() {
  this._width = this._domElement.parentElement.clientWidth;
  this._height = this._domElement.parentElement.clientHeight;

  this._updateSize(); // defined by subclasses

  this.emit('resize');
  this.emitRenderInvalid();
};
```

`clientWidth` and `clientHeight` always return 0 until they are part of a document.
I wonder if there's any way to circumvent this.

**Comment by tjgq** [comment]
Unfortunately, there's no API to set the stage size. I believe this is an oversight; it would be nice to support the off-page rendering case.

I think `Stage#updateSize` should take an explicit width and height as arguments, and `Stage#updateSize` should be the one reading the size from the DOM and passing it along. This way, regular clients wouldn't be forced to set the size explicitly, but your use case would be possible by instantiating the stage directly.

Pull request #36 gives the general idea. It's not ready to be merged yet - I need to fix some of the demos and test it more thoroughly.

**Comment by r3db** [comment]
Thank you very much,
Came up with a similar solution, but I prefer yours and I'll incorporate it until Pull request #36 is ready.

Thanks for the help :)
