### ISSUE TITLE
Remove Adobe Flash fallback

### ISSUE THREAD

**Issue by bernb** [google/marzipano#350]
As Adobe Flash goes EOL end of this year ([source](https://www.adobe.com/products/flashplayer/end-of-life.html#)), Marzipano should not use Flash as a fallback for older browsers any longer (documentation mentions IE8 and IE9 explicitly). I propose that support for browsers that rely on the flash fallback is simply dropped.

**Comment by tjgq** [comment]
Agreed that this is long due; I plan to remove both the Flash and CSS renderers soon.
