### ISSUE TITLE
Black screen 

### ISSUE THREAD

**Issue by MadMitch3566** [google/marzipano#352]
I have launched a panotour through a Web host, the tour loads but only the menu and direction arrows show. The rest of the screen is black, no images. Can anybody help please

**Comment by Junofok** [comment]
![WhatsApp Image 2020-10-23 at 8 28 38 AM](https://user-images.githubusercontent.com/73320152/96943663-6055ee80-150b-11eb-9fca-1531c08a46f2.jpeg)

I got the same problem and shows "javascript:void(0)"
Any ideas about this?

**Comment by MadMitch3566** [comment]
I've given up, using lapentour now, more hot-spot functions, really easy to use and instant URL.
You can subscribe for Web hosting for £15 ish per month

**Comment by MadMitch3566** [comment]
Resolved, ditched marzipano for Lapentour.
