### ISSUE TITLE
Couldn't Open the tour, black screen and shows "javascript:void(0)"

### ISSUE THREAD

**Issue by Junofok** [google/marzipano#354]
Using Mac OS

24 Oct: tested on PC still shows "javascript:void(0)"

failed

24 Oct: saw @tjgq mentioned that it is about problem of WebGL
https://github.com/google/marzipano/issues/92

tired to turn on Google Chrome WebGL on Mac, 
https://help.crossbrowsertesting.com/live-testing/faq/enabling-webgl-chrome/

failed

**Comment by tjgq** [comment]
When you click the address bar, does the address start with `file://`? If it does, that's the problem - WebGL won't work when you open a local html file in the browser. The file must be served by a web server and visited through an `http://` or `https://` URL.

**Comment by tjgq** [comment]
Please reopen if my suggestion above didn't help.
