### ISSUE TITLE
Equirectangular image is loading slow

### ISSUE THREAD

**Issue by neetudas24** [google/marzipano#355]
Hi!
I am using an equirectangular image and followed the examples in demo. But the initial image loading is very slow. The size of the image is 2.2 MB. Is there any way to first load a smaller image and then a large image with equirect?

**Comment by tjgq** [comment]
Unfortunately, there's no easy way to do this with equirectangular images until #303 is implemented.

If your panorama is a cube map, you can specify a smaller preview image as shown in [this demo](https://github.com/google/marzipano/blob/master/demos/cube-multi-res/index.js#L30). It's a good idea to use a cube map for high-resolution panoramas anyway, as they make it possible to load only the portions of the scene that are viewed.
