### ISSUE TITLE
canvas.toDataUrl() returned blank image. How to save rendered scene as image?

### ISSUE THREAD

**Issue by KramRul** [google/marzipano#363]
Hi. I faced with the next problem. I am trying to save the page to pdf format. I am using html2canvas package to create screeshoot of the page and save it as pdf. But when the screenshoot creates I am geting the blank space where must be rendered scene. In the screenshoot above you can see the page and created pdf file without rendered scene.

![image](https://user-images.githubusercontent.com/32257436/103100484-6ce5e880-461b-11eb-9b9d-f590846574d1.png)

![image](https://user-images.githubusercontent.com/32257436/103100499-7e2ef500-461b-11eb-93ce-8fb568b2b4c9.png)

And here is the screenshoot where I am using window.print() and it contains rendered scene.

![image](https://user-images.githubusercontent.com/32257436/103100631-293fae80-461c-11eb-893d-4f28f6249c88.png)

When I try to get base64 of the canvas that contains rendered scene I am geting transparent image. As I understand it is the problem with the origin. But I didn`t find any working solution that can fix it.

Here are parts of code

```
let data = document.getElementById("printSceneWrapper");
        let mainCanvas = document.querySelector("canvas");
        let gl = mainCanvas.getContext("webgl");
        console.log(gl.getContextAttributes());
        gl = mainCanvas.getContext("webgl", { preserveDrawingBuffer: true });
        console.log(gl.getContextAttributes());
        /*, {
          logging: true,
          foreignObjectRendering: true,
          allowTaint: true,
          useCORS: true
        } */
        html2canvas(data).then((canvas) => {
          // Few necessary setting options
          var imgWidth = 208;
          var pageHeight = 295;
          var imgHeight = (canvas.height * imgWidth) / canvas.width;
          var heightLeft = imgHeight;

          const contentDataURL = canvas.toDataURL();
          let pdf = new jsPDF("p", "mm", "a4"); // A4 size page of PDF
          var position = 0;
          pdf.addImage(contentDataURL, "PNG", 0, position, imgWidth, imgHeight);
          pdf.save("new-file.pdf");
        });
        // let doc = new jsPDF("p", "px", "a4");
        // await doc.html(this.wrapper.nativeElement);
        // doc.save(`scene.pdf`);
      }, 6000);
```
```
public getImageFromCanvas(): string {
    console.log("getImageFromCanvas");
    this.loader.start();
    const canvas = document.querySelector("canvas") as HTMLCanvasElement;
    let data = canvas ? canvas.toDataURL("image/jpg", 0.4) : "";
    this.loader.stop();
    return data;
  }
```
Can anyone helps?

Angular version - 10.0.2
Marzipano version - 0.9.1

**Comment by tjgq** [comment]
Try calling `viewer.stage().takeSnapshot()`.

**Comment by tjgq** [comment]
Sorry, I misread your question - `takeSnapshot` would give you a data URL with the contents of the Marzipano WebGL canvas, but you want to capture the entire page.

This appears to be an issue with `html2canvas`, not Marzipano. Perhaps opening an issue in their GitHub repository will help you get an answer?

**Comment by KramRul** [comment]
> Try calling `viewer.stage().takeSnapshot()`.

Thanks a lot. viewer.stage().takeSnapshot() works as I expected. It saved my time)
