### ISSUE TITLE
Maximum call stack size exceeded after calling startMovement on Scene#lookTo tween done callback 

### ISSUE THREAD

**Issue by jordyno** [google/marzipano#364]
Trying to start `autorotate `after the `scene#lookTo` tween finishes via the `done`parameter. It looks like the movement has not yet finished when the `done` function is called and render is broken entirely.
Temporary fix: used tween function to call autorotate after 100ms delay.

**Comment by tjgq** [comment]
Yes, the movement must be considered "finished" when the `done` callback runs, otherwise the callback gets stuck in a loop trying to cancel the old movement before starting the new one. The patch above should have fixed it.

Thanks for reporting!
