### ISSUE TITLE
Firefox doesn't show preview.jpg correctly

### ISSUE THREAD

**Issue by kobalt22** [google/marzipano#369]
Here is an example: http://sfera360.lv/tours/t/
When I open it in Firefox (Windows, Ubuntu, Android), the preview.jpg doesn't show panorama correctly and as tiles are loaded, the panorama becomes correct.
In my example I have removed all the tiles from second panorama, so only preview.jpg is shown.
My example was made using https://www.marzipano.net/tool/
![marzipano](https://user-images.githubusercontent.com/9315136/104705132-34b95d80-5722-11eb-82ed-33bd6cc3073d.jpg)

**Comment by tjgq** [comment]
Thanks for reporting. It appears that `createImageBitmap` (used for cropping the preview image) is broken on Firefox. I will commit a fix momentarily.

**Comment by stephan-tfi** [comment]
Hi @tjgq  
is it possible that this problem still exists in all current Safari versions? (tested macOS/iOS)
