### ISSUE TITLE
How to get Marzipano non-minified version js file

### ISSUE THREAD

**Issue by RameshLamani** [google/marzipano#37]
How to Marzipano non-minified version js file?. I need to implement drag and drop functionality for  the hotspot. I Want to see whole code of marizpano.js file.

**Comment by manuelcabral** [comment]
To make changes to the Marzipano source code, clone the repository and run `npm run dev`. This will use browserify to build an unminified file to build/marzipano.js.

**Comment by RameshLamani** [comment]
Hi manuelcabral, I tried same way what you have mentioned but getting error. I have attached screen shot within for more reference. 
![marzipanoerror](https://cloud.githubusercontent.com/assets/3736336/18577879/4c8e9760-7c0a-11e6-8939-20c3856755b5.PNG)

**Comment by RameshLamani** [comment]
Hi manuelcabram

I tried same way what you have mentioned but getting error. I have attached
screen shot within for more reference. Please can you tel me whats the
wrong.

[image: Inline image 1]

**Comment by manuelcabral** [comment]
This is the problem in #3 related to `npm run` on Windows. Instead of `npm run dev` run the script directly with the command `scripts\dev`.

**Comment by RameshLamani** [comment]
Hi Author,

Still I am getting error for more details I have attached log within.
Please help me out to generate unminified version file.
[image: Inline image 1]

**Comment by VisualExt** [comment]
Hi first run 
npm install 
npm run dev
