### ISSUE TITLE
How can I solve this error when I type npm lodash/get, can you help me?

### ISSUE THREAD

**Issue by beatrzd** [google/marzipano#370]
npm ERR! code 1
npm ERR! command failed
npm ERR! command git ls-remote ssh://git@github.com/lodash/get.git
npm ERR! 'git' is not recognized as an internal or external command,
npm ERR! operable program or batch file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ACER\AppData\Local\npm-cache\_logs\2021-01-15T22_50_51_865Z-debug.log

**Comment by tjgq** [comment]
You need to install Git in addition to Node.js. See e.g. https://github.com/nodejs/help/issues/786.
