### ISSUE TITLE
Firefox 85: preview.jpg tiles not correctly placed on cube

### ISSUE THREAD

**Issue by AndrasDF** [google/marzipano#377]
When loading a cube-multi-res scene like the demo https://www.marzipano.net/demos/cube-multi-res/ in Firefox the six sides of the preview.jpg are not distributed over the six sides of the cube, but the whole image is squezed on each side of the cube. This happens only in Firefox. 
You can see the problem with slower internet connections until the tiles are loaded.

**Comment by derryberni** [comment]
same problem with i'm using Mozilla Firefox 85.0.1 (64-bit)

**Comment by mhilgefort** [comment]
I have also experienced this issue with Firefox.
It seems like it was introduced with v0.10.0, since downgrading to  v0.9.1 solved it for me. I'll keep it at that until the issue has been fixed.

**Comment by pitayita** [comment]
Hello, I am unfortunately having the same issue on Firefox 85.0.2.

It is a shame to see continuous flashes of wrong tiles while panning around, really ruins the immersive experience! If anyone has any solutions or thoughts, please let me know.

**Comment by tjgq** [comment]
This should have been fixed in 684f9fd which was just released as part of v0.10.2.

**Comment by la-pitayita** [comment]
Hello Tiago @tjgq, thank you so much for working on this and for fixing this issue. The preview tiles load perfectly in Firefox now and it looks great across all browsers. Thanks for all your awesome work!
