### ISSUE TITLE
Sphere picture

### ISSUE THREAD

**Issue by franciscop-sc** [google/marzipano#379]
Hi I find Marzipano to be amazingly built! The reference image I see Marzipano uses [in this example](https://github.com/google/marzipano/blob/master/demos/equirect/index.js) looks more like the one in the left. I'm trying to render an image like the one in the right, which is a sphere with the data. However I'm failing to do so. :

<table>
  <tr><th>Official Example</th><th>Spherical Image</th></tr>
  <tr>
    <td>
      <img width="500" src="https://user-images.githubusercontent.com/47550791/109805495-d9f2ab80-7c66-11eb-910d-2d7693551e91.png" />
    </td>
    <td>
      <img width="500" src="https://user-images.githubusercontent.com/47550791/109805627-0d353a80-7c67-11eb-9a8b-90beaf79a6e9.png" />
    </td>
  </tr>
</table>

Is there a way to use a "spheric" image instead of a stretched image? I've tried to change the parameters inside `RectilinearView` to no avail, is that even the right place to change parameters? Or is it more involved than just changing some parameters?

```js
    // ...

    const source = Marzipano.ImageUrlSource.fromString("/images/cam1.jpg");

    // Create geometry.
    const geometry = new Marzipano.EquirectGeometry([{ width: 2880 }]);

    // Create view.
    const limiter = Marzipano.RectilinearView.limit.traditional(1080, (100 * Math.PI) / 180);
    const view = new Marzipano.RectilinearView({ /* ?? */ }, limiter);

    // ...
```

**Comment by tjgq** [comment]
It's not supported, sorry. My suggestion is to use an image processing tool to convert the panorama into cubemap or equirectangular format before using it with Marzipano.

Note: I'm assuming you're referring to *input* images in spherical format. If you have an input image in equirectangular/cube format, but want to display it as shown in the picture - a "little planet projection" - that's not supported either, but it's a different feature request :)

**Comment by franciscop-sc** [comment]
Thanks! I could make it work with https://github.com/legokichi/three-fisheye in the end (yes, I meant a spheric image as an _input_ image).
