### ISSUE TITLE
Set max and min zoom level for marzipano

### ISSUE THREAD

**Issue by MunishTXL** [google/marzipano#38]
Hi

I want to set max and min zoom level for marzipano.  I am using this code to set min and max but it doesn't work.

var viewer = new Marzipano.Viewer(document.getElementById('pano'));
var source = Marzipano.ImageUrlSource.fromString(
  imagesPath
);
var geometry = new Marzipano.CubeGeometry([{ size: 1024, tileSize: 1024 }]);
var limiter = Marzipano.RectilinearView.limit;
limiter.traditional(1024, 120 * Math.PI / 180);
limiter.vfov(startFov, startFov)
limiter.hfov(startFov, startFov);
view = new Marzipano.RectilinearView(initialView, limiter);
scene = viewer.createScene({
    source: source,
    geometry: geometry,
    view: view,
    pinFirstLevel: true
});

If I am using limiter as below it works fine but do not set limit in zoom.
var limiter = Marzipano.RectilinearView.limit.traditional(1024, 120 * Math.PI / 180);

Please help me to to set this.

Thanks

**Comment by tjgq** [comment]
To use several limiters at the same time, compose them with `Marzipano.util.compose` and pass the result into the `View` constructor. For example, to limit both hfov and vfov above and below:

```
var limiter = Marzipano.util.compose(Marzipano.RectilinearView.limit.hfov(a, b),
                                     Marzipano.RectilinearView.limit.vfov(c, d));
var view = new Marzipano.RectilinearView(initialView, limiter);
```

**Comment by MunishTXL** [comment]
Hi

I have used this code to set min and max zoom level and it works fine. But now I am facing new issue now it rotates 360 degreee from up to down.
var geometry = new Marzipano.CubeGeometry([{ size: 1024, tileSize: 1024 }]);
var limiter = Marzipano.util.compose(Marzipano.RectilinearView.limit.vfov(0.698131111111111, 2.09439333333333), Marzipano.RectilinearView.limit.hfov(0.698131111111111, 2.09439333333333)); 

previousely I was using.
var limiter = Marzipano.RectilinearView.limit.traditional(1024, 120 * Math.PI / 180);
In this case rotation works fine.

Please help me if there is any error.

**Comment by manuelcabral** [comment]
You can add a pitch limiter to prevent this from happening:

```js
var limiter = Marzipano.util.compose(
  Marzipano.RectilinearView.limit.vfov(0.698131111111111, 2.09439333333333),
  Marzipano.RectilinearView.limit.hfov(0.698131111111111, 2.09439333333333),
  Marzipano.RectilinearView.limit.pitch(-Math.PI/2, Math.PI/2));
```

**Comment by Bagmaz** [comment]
Hi, i'm amateur and i want change limit zoomIn and zoomOut, Please help me
