### ISSUE TITLE
Uncaught RangeError: Array buffer allocation failed

### ISSUE THREAD

**Issue by drennenb** [google/marzipano#384]
Uncaught RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at new Uint8ArrayWriter (zip.worker.js?4b26ffb:14)
    at JSZip.generate (zip.worker.js?4b26ffb:14)
    at zip.worker.js?4b26ffb:14

After pressing export, this error shows in the console when I use more than 28 panos in the Marzipano Tool.
Reducing the files sizes with jpg compression had no effect.
Have not tried reducing resolution.

Looking for remedies and work arounds if this is not a bug.

**Comment by tjgq** [comment]
Unfortunately, this just means that you imported too many panos, and the browser ran out of memory. JPEG compression won't help, because the tool must decompress the images to process them.
