### ISSUE TITLE
Bower installation

### ISSUE THREAD

**Issue by kingrollo** [google/marzipano#39]
Hi folks,

Any chance of a bower installation for Marzipano? It behaves reasonably well with bower install "git://github.com/google/marzipano" if you download a built version of the library and drop "main": "build/marzipano.js" into the .bower.json, but that feels a lot like cheating.

Alternatively any advice on how to hook it up so it builds with my standard gulp build?

... or should I just give up and push a built version through in the gulp file?

Thanks!
Roland.

**Comment by tjgq** [comment]
A Bower package is only a reference to whatever is in the repository at a given tag, so publishing to Bower would require checking the builds into the repository (which we would prefer not to do).

Unless your project is already using npm as the package manager (in which case you can simply require Marzipano as a module), I'm afraid you'll have to vendorize the build.

**Comment by kingrollo** [comment]
Thanks. Could you expand on "vendorize"? It's not a term I'm familiar with, and Google wasn't a lot of help.

**Comment by tjgq** [comment]
Oh, sorry. Vendorizing just means copying a library into your project's
directory (as opposed to using some kind of package manager to take care of
dependencies for you).

**Comment by kingrollo** [comment]
No worries - thanks again.
