### ISSUE TITLE
can we autorotate in anti clockwise direction?

### ISSUE THREAD

**Issue by neetudas24** [google/marzipano#392]

**Comment by jordyno** [comment]
yes, you just use negative yawSpeed when setting up autorotate. For example:

// Set up autorotate, if enabled.
var autorotate = Marzipano.autorotate({
    yawSpeed: -0.03,
    targetPitch: 0,
    targetFov: Math.PI/2
});

**Comment by neetudas24** [comment]
Thanks for the quick reply. It worked
