### ISSUE TITLE
multiresolution with equirectangular images

### ISSUE THREAD

**Issue by ironplasma** [google/marzipano#4]
Is it possible to have a multi-resolution with equirectangular images?
How would you do it?

**Comment by tjgq** [comment]
Yes, it should be possible. The `EquirectGeometry` constructor accepts a list of level sizes as its argument. You also have to provide an `ImageUrlSource` that knows how to resolve each level into the respective URL. Something along these lines (disclaimer - I haven't tested this code):

```
var source = new Marzipano.ImageUrlSource(function(tile) {
  return { url: "http://www.example.com/path/to/equirect" + tile.z + ".jpg" };
});

var geometry = new Marzipano.EquirectGeometry([
  { width: 1024 },
  { width: 2048 },
  { width: 4096 }
]);
```

However, note that equirectangular geometries can't be tiled - each level must be a full equirectangular image. If you are planning to serve very high-resolution images this way, I strongly suggest you use a cube geometry instead.
