### ISSUE TITLE
Progress bar with marzipano

### ISSUE THREAD

**Issue by MunishTXL** [google/marzipano#40]
Hi,

I want to show progress bar with marzipano while my view is getting ready for display. Is there any way in marzipano which will help me to show progress bar.

Thanks

**Comment by manuelcabral** [comment]
There isn't any way to do this currently I'm afraid.

One way to implement this might be to add a function to [Stage](https://github.com/google/marzipano/blob/master/src/stages/Stage.js) to get the tiles that need to be rendered for a layer and add some functions to [ImageUrlSource](https://github.com/google/marzipano/blob/master/src/sources/ImageUrl.js) to get the loading status.
