### ISSUE TITLE
Marzipano multiple hotspot issue

### ISSUE THREAD

**Issue by MunishTXL** [google/marzipano#43]
Hi,

I have added multiple hotspots (15000) on my scene and start auto rotation. Now panorama doesn't work smoothly it starts vibrating. I don't understand what's wrong with my code this even I didn't find any example related to this.

var iconWrapper = document.createElement('div');
iconWrapper.classList.add('info-hotspot-icon-wrapper');
var icon = document.createElement('img');
icon.src = 'images/blue_droneview.png';
icon.classList.add('info-hotspot-icon');
iconWrapper.appendChild(icon);
 var position = {  yaw: view.yaw(),    pitch: view.pitch(),  fov: view.fov()};
scene.hotspotContainer().createHotspot(iconWrapper, position);

Is there any way to handle this situation.

Thanks

**Comment by manuelcabral** [comment]
Each hotspot creates a DOM element whose position has to be updated on every frame, so it is expectable that a very large number of hotspots slows things down.
