### ISSUE TITLE
Get rid of the tiles

### ISSUE THREAD

**Issue by AdrienPoupa** [google/marzipano#44]
Hello,

Is it possible to get rid of the tiles and use a full 3d image as is, without resizing it?

Thanks

**Comment by manuelcabral** [comment]
Hi,

What do you mean by 3d image? A 2:1 equirectangular image like [this](http://www.marzipano.net/media/equirect/angra.jpg)? If so, the [Equirectangular](https://github.com/google/marzipano/tree/master/demos/equirect) demo is an example of how to do it.

**Comment by AdrienPoupa** [comment]
That is what I meant, thank you!
