### ISSUE TITLE
Is there any open source for the export function used by the Marzipano tool?

### ISSUE THREAD

**Issue by hina9** [google/marzipano#442]
I saw that the function to export a VR site is included in the 'Mazipano Tool'.
Is this function open?

https://www.marzipano.net/tool/#

**Comment by WilbertWalrus** [comment]
See https://github.com/google/marzipano/issues/435 — Google says NO!

**Comment by samuelgirardin** [comment]
I've made a try last year to develop a tiling tool, as I was not sure that marzi tool will be kept online.
Here is a small video : https://youtu.be/I2QhUxe1hkQ . This is a very alpha version. I will consider to put it online when I get more time.

**Comment by neuhaus** [comment]
Dương Tùng Anh has vibe-coded a version of Marzipan Tool that allows importing a previous export and editing! A highly requested missing feature of Marzipan Tool.

He mentioned it at
https://github.com/google/marzipano/issues/309#issuecomment-3626747731
and you can find it hosted at
https://marzipano-importer.tunnaduong.com/
with the source code at 
https://github.com/tunnaduong/marzipano-importer
