### ISSUE TITLE
Image Url Source fromString explained

### ISSUE THREAD

**Issue by v-hung** [google/marzipano#453]
![image](https://user-images.githubusercontent.com/33823245/232462101-26f9b167-7034-4b10-8f44-b1ccfb5ea68d.png)
I don't understand how to sort image content in ImageUrlSource fromString. f is direction and xzy is? I can't find any documentation or tutorials about it

**Comment by etfut** [comment]
https://www.marzipano.net/reference/ImageUrlSource.html#.fromString

**Comment by v-hung** [comment]
Reading the above documentation didn't help me much but I found out how it works
