### ISSUE TITLE
Is there any way to enable/add the controls and allow full screen buttons after a tour is published/complete?

### ISSUE THREAD

**Issue by TonyNJFPV** [google/marzipano#467]
Is there any way to enable/add the controls and allow full screen buttons after a tour is published/complete?

I'm not really a coder but did scrape through the code looking for a way to enable the arrow controls and allowfullscreen and could not find it. Any guidance would be appreciated. Thank you.

**Comment by neuhaus** [comment]
Dương Tùng Anh has vibe-coded a version of Marzipan Tool that allows importing a previous export and editing! A highly requested missing feature of Marzipan Tool.

He mentioned it at
https://github.com/google/marzipano/issues/309#issuecomment-3626747731
and you can find it hosted at
https://marzipano-importer.tunnaduong.com/
with the source code at 
https://github.com/tunnaduong/marzipano-importer
