### ISSUE TITLE
Stop panaroma movement on drag of hotspot

### ISSUE THREAD

**Issue by zgmunshi** [google/marzipano#48]
I am trying out to stop the panaromic movement on dragging of my hotspot element.

I have one hotspot with slider but whenever i move slider it rotates panaroma also.

Can anyone suggest any solution for this.

Thanks.

**Comment by tjgq** [comment]
I would try calling `stopPropagation()` on mouse events to prevent them from reaching the parent element. Check out the code for `stopTouchAndScrollEventPropagation` in the sample tour demo:

https://github.com/google/marzipano/blob/master/demos/sample-tour/index.js

**Comment by zgmunshi** [comment]
I tried but it didn't worked,i tried adding `stopPropagation()` on mousedown and mousemove.

Basically i am trying to integrate Round Slider (http://roundsliderui.com/) with marzipano but on dragging the panaroma also moves.

Hopefully i am clear this time. Can you please guide me with this.

Thanks.

**Comment by zgmunshi** [comment]
Thanks that's working fine for slider but i have another control that is Wheel color picker https://github.com/fujaru/jquery-wheelcolorpicker

Adding `stopPropagation()` to color picker restricts colorpicker movement and i am unable to move the color picker slider

How to handle this.

Kindly guide 
Thanks.

**Comment by calacianu** [comment]
how do you drag hotspots?
I'm trying like this
`  eleMouseMove = ev => {
    var pX = ev.clientX;
    var pY = ev.clientY;

    this.imgHotspot.style.left = pX + "px";
    this.imgHotspot.style.top = pY + "px";
    document.addEventListener("mouseup", this.eleMouseUp, false);
  }
`
but the problem is that ev.clientY and ev.clientX does not correspond with yaw and pitch and when I try to move the element, it jumps hundreds of pixels away.
Can anyone share the drag functionality?
thank you!

**Comment by mianmianxixi** [comment]
```  /**
   * 禁用拖拽
   */
  public disableDrag() {
    if (!this.hammerEvent) {
      this.hammerEvent =
        this.viewer._hammerManagerMouse.manager().recognizers[0];
    }
    this.viewer._hammerManagerMouse.manager().recognizers = [];
  }

  /**
   * 启用拖拽
   */
  public enableDrag() {
    if (this.hammerEvent) {
      this.viewer._hammerManagerMouse.manager().recognizers = [
        this.hammerEvent,
      ];
    }
  }
```
