### ISSUE TITLE
Cant install 

### ISSUE THREAD

**Issue by virgiltu** [google/marzipano#51]
I honestly tried everything but it always seem to fail to install dependencies or get from git. Any ideas?

**Comment by tjgq** [comment]
Please explain what you're trying to accomplish. To use Marzipano as a library, you can download a pre-built version from our website, or install it with npm. You don't need to check out the git repository unless you want to make changes to the source code.

**Comment by virgiltu** [comment]
It was the not script it was my computer. No really sure but here are the
two ways I tried.

1. Download the files from git and unzip in a folder. Then run NPM install.
Lots of errors. Did not install.
2. Tried to pull from Git, but every time the same issues.

Finally it seems to install but I did the NPM install from inside the Git
CMD rather than normal CMD and that worked :)

Amazing plugin.
   I am guessing the creator is not part of the GIt repository, am I
correct.

**Comment by tjgq** [comment]
For future reference, the issues when running the scripts under cmd.exe may be related to bug #3.

The Marzipano Tool (I'm guessing that's what you meant by "creator") isn't part of the open source release, so you won't find the source code for it in the repository.
