### ISSUE TITLE
what kind of video can be supported by marzipano?

### ISSUE THREAD

**Issue by tudinger** [google/marzipano#53]
Hi

Lot of 360 camera provider generate videos and can be displayed on their website and application. 
I tried to play a video generated by insta360 device. I got an error "index.html:1 Uncaught (in promise) DOMException: Failed to load because no supported source was found."

Here are my video stream links: 
https://goo.gl/XOEzLH
https://goo.gl/zv4Rqm

What kind of camera can make a video for marzipano?

Thanks

**Comment by tjgq** [comment]
Discussion in https://groups.google.com/forum/#!topic/marzipano/c2wFa7JO8S4.
