### ISSUE TITLE
e.stopPropogation not working for touchevents on marzipano

### ISSUE THREAD

**Issue by zgmunshi** [google/marzipano#55]
I have slider on marzipano as hotspot which is working fine with click and mousedown that is when i slide the slider panaroma doesn't move but similar thing is not working for touchstart as it moves with the touch movement

Can anyone suggest how to restrict panaromic movement on hotspot on mobile devices also.

**Comment by manuelcabral** [comment]
I couldn't quite understand the issue. In any case, the best place to discuss this is the [Google Group](https://groups.google.com/forum/#!forum/marzipano). Please post a link to your application there so we can take a look.
