### ISSUE TITLE
Fix view with projectionCenter, failed?

### ISSUE THREAD

**Issue by chrispcb** [google/marzipano#58]
Hello,

I update with 5.2 version and  I have a big deformation on on top and bottom view when I use a display an equirectangular image .

Look attached files:
![v5 1](https://cloud.githubusercontent.com/assets/10771054/20830093/41e0bcba-b87f-11e6-8e71-e07102360672.jpg)
![v5 2](https://cloud.githubusercontent.com/assets/10771054/20830092/41e01274-b87f-11e6-9e21-f1c6e2a46dfe.jpg)

**Comment by tjgq** [comment]
Was this tour generated by the Marzipano tool? Did you make any changes to the code?

**Comment by chrispcb** [comment]
You can try it with your Equirectangular demo (http://www.marzipano.net/demos/equirect/index.html).
In this demo, marzipano version is 0.50. Replace to the last version (0.52). Move up or down, You can see this issue.

**Comment by tjgq** [comment]
Thanks for noticing this. I've just released v0.5.3 containing a fix for this bug.

**Comment by chrispcb** [comment]
Yes good job. Fixed. Thanks.
