### ISSUE TITLE
is there a way to set the canvas size?

### ISSUE THREAD

**Issue by jacquelinepeh** [google/marzipano#6]
Hihi, as mentioned in the subject. Reason being, my page is one-pager kind with a few sections. And this 360 tour will be in one of the section. I looked through the documentation and there isn't any options for me to set the canvas and it will just take up 100% width height of the browser.
Is there a way to set the size?

**Comment by manuelcabral** [comment]
Hi. You can do this by setting the height of the element that contains Marzipano with CSS. Let me know if that doesn't work.

**Comment by jacquelinepeh** [comment]
Hi @manuelcabral , oh yes.. sorry my bad. Forgot to add position relative to the parent container.
Thanks!!
