### ISSUE TITLE
Device Orientation

### ISSUE THREAD

**Issue by Erwin-Cino** [google/marzipano#60]
I'm a newbie in javascript. The thing is how can I implement device orientation on the VR tour I made using the marzipano tool. Thank you.

**Comment by manuelcabral** [comment]
The [web-vr](https://github.com/google/marzipano/tree/master/demos/webvr) demo uses the device's orientation to control the view. However, note that this demo is still using an older version of WebVR and needs to be updated, so it may not be working currently.

If you have any other questions, please send them to the [group](https://groups.google.com/forum/#!forum/marzipano). We use the group for questions about using Marzipano and GitHub issues for bugs.
