### ISSUE TITLE
Center view

### ISSUE THREAD

**Issue by gop-aroy** [google/marzipano#63]
Hi :) 

I'm sorry for opening this second issue or improvement, but i wanted to know if it's possible to center the view to its original coordinates.

After turning and turning around, the user might want to re-center the view on this point. I tried using a watcher on a event and updating the pitch and the yaw to 0 after the event is triggered, but it only works on the first scene and it's not fluid. Then, when i change my scene, i can't do it anymore (even on the first scene). Maybe i do it wrong, please tell me if this is possible :)

Thank you a lot.

**Comment by manuelcabral** [comment]
Hi. This should be possible. Can you send a link to the example to the [group](https://groups.google.com/forum/#!forum/marzipano) please? We use the group for questions about how to use Marzipano and GitHub issues for bugs.
