### ISSUE TITLE
Add Resistance To Device Orientation Handler

### ISSUE THREAD

**Issue by alecrubin** [google/marzipano#67]
Is it possible to add "resistance" or decrease the sensitivity on the Device Orientation Control Method?

**Comment by manuelcabral** [comment]
The DeviceOrientationControlMethod should change the view by the same amount that the device is rotated. However, it should be possible to decrease the sensitivity by multiplying the offset in [these lines](https://github.com/google/marzipano/blob/006327747449daf034f5bd2cc172747e219af4eb/demos/device-orientation/DeviceOrientationControlMethod.js#L78) by some value between 0 and 1

**Comment by tjgq** [comment]
Closing this for now, since we have no plans to add this feature.
