### ISSUE TITLE
Marzipano VR issue

### ISSUE THREAD

**Issue by MunishTXL** [google/marzipano#69]
Hi

I have implemented marzipano functionality for Google cardboard (split screen and device orientation). Now I want to switch between the scenes from one hotspot to other when you seen from google card board. I have implemented this functionality. But now we are facing strange issue in iphone only. When we shift from one scene to other after 5-6 jumps our page crashes. 

Please help me so that I will complete my functionality.

Thanks

**Comment by manuelcabral** [comment]
Hi,

It may be that there is a memory leak that causes the crash. Do you have a
link to an example?

**Comment by MunishTXL** [comment]
Hi

I have created a sample project below is the link. There is a VR button on top of screen on that click you will move to VR view and vice versa. But after 2-3 moves our page get refreshed in iphone only in window and mac it's working fine.

http://india.fastout.com/marzipano/MarzipanoTest.aspx

If you find any solution please share it with me.

Thanks

**Comment by MunishTXL** [comment]
Hi

I am still struck with this issue can anyone help me to resolve this memory issue.


Thanks

**Comment by manuelcabral** [comment]
I noticed that you already have some code to destroy the current Marzipano viewer when the button is pressed and a new viewer is created. It is a good idea to do this. However, this code is not being called, since it is commented out. This might be what is causing the problem.

**Comment by MunishTXL** [comment]
Hi,

Thanks for sharing your views with me. As per your suggestion I have already tried that code but it doesn't work. After that I have commented my dispose method. 
I am looking into marzipano source code also but still did not get any way to resolve this issue.

**Comment by manuelcabral** [comment]
I think that might be happening because the HTML is being modified before the Marzipano viewer is destroyed, which causes the destroy to fail. Try destroying the viewer at the beginning of the `displayVrView()` and `displayNormalView()` functions and remove the `$('#pano').html('')`, like so:

```js
function displayVrView() {
    viewer.destroy();
    $('#VRTogglesTour2').hide();
    $('#HideVRTogglesTour2').show();
    (...)
}
function displayNormalView() {
    viewer.destroy();
    $('#HideVRTogglesTour2').hide();
    $('#VRTogglesTour2').show();
   (...)
}
```

**Comment by MunishTXL** [comment]
Hi,

Thanks, it work's. I destroy my object then clear my pano div. 

Great job.

Thanks
