### ISSUE TITLE
Marzipano Tool offline?

### ISSUE THREAD

**Issue by MarcoNko** [google/marzipano#72]
Hi there,

I need to work on a lot of images to be converted from equirectangular to cubemap, the problem is that images are so many, revisions of this work will be many too and i don't like the idea of working online on Marzipano Tool (also because I can't save and open to edit projects).
I also searched for a Photoshop action to convert images from equirectangular to cube map on my own, but without any good result.
By the way i might also need to work with transparent pngs and the current Tool flats everything in jpgs, I'd like to custom this part.
Is there a Git, opensource, sourcecode, draft or something of this great tool to work on?

Thank You

**Comment by flyer299** [comment]
We are also searching for the same kind of solution.  To date the best option we have found is to use KR Pano (commercial software) to covert to a Cube Map.   They have a command line tool that will do the work.

**Comment by Ankit-Solanki** [comment]
but only license version of KR Pano worked well, in free version KR pano signature stick with pano images....

**Comment by alexishida** [comment]
+1

**Comment by claytonrothschild** [comment]
Its been a year since this initial discussion. Anyone find any better open source tools that offer similar functionality to Marzipano Tool and KR Pano?
