### ISSUE TITLE
Low Res images from S3

### ISSUE THREAD

**Issue by nittygritty** [google/marzipano#75]
I copies the Tiles folder to S3 and amended the amended index.js to point to S3 for the source images,  but the images returned are very low resolution.

Example, 100% quality http://quick360tours.com/tours/Cloverdale/

Example, 50% quality http://quick360tours.com/tours/Cloverdale/index2.html

Looking forward to your feedback

TIA,

Fred

**Comment by manuelcabral** [comment]
It seems that the server is returning a 403 (Forbidden):
https://p1og-360-videos.s3.amazonaws.com/cloverdale/tiles/0-the-entrance/3/f/0/3.jpg.
Probably some configuration needs to be changed on the server.

**Comment by jmprovencher** [comment]
The problem is that S3 is allowing the first level images to be loaded but not the rest. Simply make public the entire tour folder in Amazon Console.
