### ISSUE TITLE
Work on InternetExplorer but not in WindowsForm

### ISSUE THREAD

**Issue by malecos** [google/marzipano#77]
Hi. I use Marzipano Tool to create a html file (index.html) with my 360 picture. File woks fine on internet explorer 9, and I can move the picture using mouse, but when I create a WindowForm application, using VisualStudio and its Webbrowser function to open index.html file inside WindowsForm, the image opens but I can't move it with mouse, only with the controllers on the bottom of screen.
Is there a solution to image move works on WindowsForm, with Webbrowser function?
Sorry poor english.
Thanks!

**Comment by tjgq** [comment]
Given that WindowsForm is an extremely uncommon use case, this will not be fixed unless someone contributes a patch.
