### ISSUE TITLE
Webserver .exe shipped with generated tours incorrectly flagged as a virus/trojan

### ISSUE THREAD

**Issue by kenthaug** [google/marzipano#80]
Hi
My Anti-Virus suddenly stated to report Marzipano Tools as an:

Category:	Malware
Type:	Trojan
Platform:	W32
Aliases:	trojan.generic, gen:trojan.369260

Anyone else?

**Comment by tjgq** [comment]
This is very likely a false positive. The webserver executable included in the zip files produced by the tool is a Go binary, and these have been incorrectly flagged as malware in the past: https://github.com/golang/go/issues/18699.

**Comment by Gerboa** [comment]
I get the same from Symantec:
Security Risk Found!WS.Malware.1 in File: webserver-windows.exe by: Auto-Protect scan.  Action: Cleaned by Deletion

**Comment by tjgq** [comment]
Due to the number of issues it was causing, we decided to omit the .exe file from generated tours.

**Comment by mbukejlovic** [comment]
Please make it optional :( I found that tool so useful, it really helped quickly showcase the work.
Maybe if you would maybe add some instructions how can we quickly compile that exe/binary ourselves (or run the Go/Ruby/Python script for that)?

**Comment by tjgq** [comment]
Unfortunately, the executable made the tool essentially unusable for a lot of people, so we'd rather not add it back.

If you have Python installed (on MacOS it comes installed out of the box), you can run this inside the tour directory to get a web server running:

`python -m SimpleHTTPServer 8000`

**Comment by mbukejlovic** [comment]
That's awesome! :) Thanks :) Maybe just add that to the README. It won't hurt people, but it might be useful for those that miss this binary?
