### ISSUE TITLE
Compass in 360 panorama?

### ISSUE THREAD

**Issue by jmprovencher** [google/marzipano#81]
Would it be possible to implement a compass in 360 panoramas? Any idead how it could be done?
![capture d ecran 2017-05-03 a 10 20 43](https://cloud.githubusercontent.com/assets/12234108/25665129/b18bbf82-2fea-11e7-9106-fd993b4a387b.png)

**Comment by tjgq** [comment]
You can listen for the `viewChange` event on the `Viewer` object, which will give you the yaw value you are currently looking at, and update your compass widget based on it. Unless all your panos are centered at north, you will need to subtract the appropriate offset from the yaw.
