### ISSUE TITLE
Hotspots with extraRotations don't work as expected

### ISSUE THREAD

**Issue by jasperswart** [google/marzipano#82]
When I add a hotspot like tis:

var position = {
    yaw: someYaw,
    pitch: somePitch
};

var hs = container.createHotspot(
    template,
    position
);

hs.setPerspective({
    extraRotations: 'rotateX(0.5rad)'
}); 

I expert the hotspots to be rotated 90 degrees so it will look as if they are on the floor.

The extra rotation are not added to the hotspot parent element.

Why does this not happen?

**Comment by manuelcabral** [comment]
`radius` also needs to be set when you call `setPerspective`, otherwise `extraRotations` will be ignored.

**Comment by jasperswart** [comment]
what does the radius have to be?

**Comment by tjgq** [comment]
Have a look at this post in our discussion group: https://groups.google.com/d/msg/marzipano/MEmXVf-h-So/lYwQZRhABwAJ
