### ISSUE TITLE
Marzipano with android chrome issue

### ISSUE THREAD

**Issue by MunishTXL** [google/marzipano#85]
Hi

We have implemented marzipano in our web site for 360 view it is working fine in all devices and web also except some android device on chrome (moto G4plus, sony experia). These devices show 360 view at a corner of screen.  
Even we have tested marzipano official website demo link in these devices it have same issue.  You can check http://www.marzipano.net/demos/side-by-side/index.html in any of these devices it will produce same issue. 
I have attached a screenshot regarding this.
![marzipanoanrdoid](https://cloud.githubusercontent.com/assets/21051999/26545677/26a1ea28-4484-11e7-953b-dd04ed1bfa8b.PNG)

Please provide any solution this.

Thanks
Munish Soni

**Comment by gggauravgandhi** [comment]
I am facing same problems on Moto G4 and Moto E3 Power. 
I have tested with One Plus series its working fine. Tested with some lower brands, it works fine. 
But on my both moto devices it's not working. 

I tried many different Implementation, all yields same result.

I also tried doing inspect element by connecting phone over USB, no extra errors or warning or violations.

Don;t know what to do now ...

**Comment by gggauravgandhi** [comment]
@manuelcabral It works smooth in Firefox and in Chrome Beta too.

**Comment by Richacinas** [comment]
Same problem here with the demos! I'm using a Xiaomi mi5 with updated chrome.

**Comment by JacksonWolff** [comment]
Same problem here with Moto G4 Plus. Chrome updated. Working in Chrome beta and Firefox too.

**Comment by Richacinas** [comment]
I have a feeling that this could be an issue with the last Chrome update. I'm not sure..

**Comment by JacksonWolff** [comment]
I'm really needing this fix. :/

**Comment by CBillings92** [comment]
I'll say I'm having the same issue w/ Android (os version 7) w/ Chrome 58

**Comment by JacksonWolff** [comment]
With a new update of Google Chrome today, it's working now.

**Comment by Richacinas** [comment]
Cool @JacksonWolff, happy to know!

**Comment by tjgq** [comment]
The easiest way to get started is to use the [Marzipano Tool](http://www.marzipano.net/tool/), which will generate a complete virtual tour ready to be uploaded into your web site.
