### ISSUE TITLE
Love Marzipano but...

### ISSUE THREAD

**Issue by digitonAV** [google/marzipano#90]
Not sure if its ok to post this here. But i love Marzipanos as its easy to use. I have older co-workers and they love using Marzipano and creating Spheres. My question is, will there be a software version? I would love to be able to use Marzipano offline without the need of coding.

**Comment by tjgq** [comment]
We don't have plans to implement a native (non-web) version of the Marzipano Tool, sorry. Note, however, that all processing done by the tool occurs locally on the browser. The panoramas are never sent to a remote server.
