### ISSUE TITLE
What's the folder/file structure for marzipano's  flat demo?

### ISSUE THREAD

**Issue by thriskel** [google/marzipano#91]
Title tells my question, I need to know the folder/file structure as cube images have it for flat images

**Comment by tjgq** [comment]
The folder structure for the flat demo is determined by the `tileUrl` function defined here:

https://github.com/google/marzipano/blob/master/demos/flat/index.js#L26

This function receives as arguments the zoom, x and y coordinates of the tile (x=0 and y=0 is the tile in the top left; zoom=0 is the first zoom level), and returns the URL for the tile. You can use any other folder structure, as long as you rewrite this function accordingly.
