### ISSUE TITLE
Source download, local open Browser not view image

### ISSUE THREAD

**Issue by JeongHyeongJin** [google/marzipano#92]
Hi. Please understand that my low level wrote English.

Git Site download marzipano-master.zip(demo include) .

marzipano-master\marzipano-master\demos\sample-tour in index.html put in Browser not work, 

And marzipano-master/marzipano-master\build make folder after copy to marzipano.js

not viewed image. 

Sample. demos\sample-tour\index.html 

![20170630_121747](https://user-images.githubusercontent.com/18202214/27719556-3856f344-5d8e-11e7-8f86-4fb9b9bd4921.png)

**Comment by tjgq** [comment]
Chrome (and possibly other browsers) does not support WebGL content on a file:// URL.

In order for the demo to work correctly, you must open the demo through an http:// URL, either by running a web server locally on your machine, or by uploading the demo files into a web hosting service.

**Comment by JeongHyeongJin** [comment]
Thank you. I solved it because of tjgq.
