### ISSUE TITLE
Export button unresponsive if template files fail to be downloaded

### ISSUE THREAD

**Issue by andrewminchew** [google/marzipano#93]
I load in a few images, or even just a single image (equirectangular, shot on Ricoh Theta S), wait for it to process (it renders fine in the browser), click the export button, and nothing happens (no error dialogs or anything).

Google Chrome
MacOS Sierra 10.12.5
Mid 2010 iMac 21.5inch
3.2 GHz Intel Core i3
16GB Ram
ATI Radeon HD 5670 512 MB

I've tried on another machine (similar setup, might have been 2011 21.5inch 16gb ram), and get the same response. Other machines (Late 2015 iMac w Sierra, Early 2015 MBP w El Capitan) have no problem (using same images).

Any ideas / suggestions?

**Comment by andrewminchew** [comment]
having the same issue on a windows 7 system, details attached...
![system](https://user-images.githubusercontent.com/26171744/27968883-683aea0e-630e-11e7-9610-7e2b9395b0f8.PNG)

**Comment by tjgq** [comment]
Do any error messages appear in the developer console (Ctrl-Shift-J)?

**Comment by andrewminchew** [comment]
Is this what you needed to see?

Andrew Minchew

**Comment by tjgq** [comment]
I don't see anything, sorry. Did you forget an attachment?

**Comment by andrewminchew** [comment]
I included the attachments, I guess they didn't go through? Here's a
dropbox folder with two screenshots in it.

https://www.dropbox.com/sh/0tj3divwozla6ch/AADAZWjbgIIF4IkFiIyCbqPSa?dl=0

Andrew Minchew

**Comment by tjgq** [comment]
My guess is that an overly-aggressive antivirus or content filtering system is preventing the page from downloading an .exe file. This is a small, self-contained webserver executable that we include in generated tours.

**Comment by andrewminchew** [comment]
A Mac would ignore the .exe file altogether though right?

**Comment by tjgq** [comment]
No, the tool downloads both executables (Windows and Mac) and adds them to the zip file regardless of the platform it is running on.

**Comment by andrewminchew** [comment]
Ah, so it's rejecting the zip file because it sees the .exe inside?

**Comment by tjgq** [comment]
No, the zip file is never created.

The tool downloads files to be included in the zip file (the .exe is one of them), and then generates the zip file locally when you click the Export button.

Because the .exe file fails to be retrieved (this is the first console error), the code that generates the zip file crashes (this is the second console error, "Template files not loaded").

We should probably pop up an alert dialog if some of the files fail to be downloaded, since export is guaranteed to fail when that happens.

**Comment by andrewminchew** [comment]
Got it! I'll tell IT to ease up on us :) thanks! And great work! I'd love
to be able to pay for hosting and being able to come back later and edit
through the same interface! Keep up the good work!

**Comment by tjgq** [comment]
Due to the number of issues it was causing, we decided to omit the .exe file from generated tours. This should make export work again.
