### ISSUE TITLE
Adding images of our choice in Marzipano sample-tour

### ISSUE THREAD

**Issue by PhilipTheVictor** [google/marzipano#94]
@tjgq : How can one add his own images of choice to sample-tour in order to display in a web page? Where will one put the url of his images in directory structure of sample-tour?
As an example I want to display a pano from https://upload.wikimedia.org/wikipedia/commons/f/f4/360-degree_Panorama_of_the_Southern_Sky.jpg. How will I add it to marzipano sample-tour to be dispalyed on a web-page?

**Comment by tjgq** [comment]
You can use the [Marzipano Tool](http://www.marzipano.net/tool/) to create a tour from that panorama in your browser and download it as a zip file.

Note that the tool requires equirectangular panoramas to have an aspect ratio of exactly 2:1. The one you mentioned has the wrong aspect ratio, so you will have to pad it with black pixels at the bottom.
