### ISSUE TITLE
How to get yaw/pitch mouse click event?

### ISSUE THREAD

**Issue by JeongHyeongJin** [google/marzipano#95]
Hi. 
Mouse click event is How to get yaw/pitch value ?

I want absolute get yaw/pitch value.

example) hotspot-styles is demo in source expand.js contents scene.hotspotContainer().createHotspot(document.querySelector("#expand"), { yaw: 0.42, pitch: -0.03 });

yaw : 0.43, pitch : -0.03 -->> mouse click event get??

**Comment by tjgq** [comment]
You can use the [RectilinearView#screenToCoordinates](http://www.marzipano.net/reference/RectilinearView.html#screenToCoordinates) method to convert x and y pixel coordinates into yaw and pitch.

**Comment by tjgq** [comment]
Your code instantiates a new View. Instead, retrieve the view for the current scene from the Viewer instance. You probably also want to use clientX/clientY instead of x/y, because the latter don't work everywhere.

```
var view = viewer.view();
console.log(view.screenToCoordinates({x: e.clientX, y: e.clientY});
```
