### ISSUE TITLE
Download blocked

### ISSUE THREAD

**Issue by wishie** [google/marzipano#98]
After using the Marzipano Tool, Google is now blocking the downloaded file, claiming its malicious. I cant find a way to disable this, either.

**Comment by tjgq** [comment]
Can you attach a screenshot?

**Comment by melmilloway** [comment]
Mine has been blocked too. Here's a screenshot of the alert at the bottom of the screen and also the Google page it leads to.
<img width="933" alt="screen shot 2017-08-25 at 7 39 25 am" src="https://user-images.githubusercontent.com/15130275/29718770-ac7d655e-8968-11e7-8cd8-959389206131.png">

**Comment by IanJohnsonPhoto** [comment]
I'm getting the Block message as well, is there a work around?

**Comment by melmilloway** [comment]
I just downloaded via FireFox. No block on there.

**Comment by tjgq** [comment]
Due to the number of issues it was causing, we decided to omit the webserver executable from generated tours. Let us know if the error persists.

**Comment by IanJohnsonPhoto** [comment]
Thanks @melmilloway  that worked ... and I just retried Chrome and that works now @tjgq   Thanks for the help
